import type { Stage } from "./types";

// ===== HAJIMARI CHAPTER 2: KATAKANA =====
// 10 more stages (11-20) covering Katakana - the second aksara set.
// Story: After defeating the Shadow King, the village elder reveals
// that a second set of aksara (Katakana) exists for foreign words.
// A new threat arises: "The Mirror Phantom" who has stolen the katakana.

export const KATAKANA_STAGES: Stage[] = [
  // ===== STAGE 11: KATAKANA VOWELS =====
  {
    id: "hajimari-11",
    worldId: "hajimari",
    index: 11,
    chapter: 2,
    title: "Cermin Tujuh Huruf",
    subtitle: "Katakana Vokal (アイウエオ)",
    type: "lesson",
    intro: [
      "**Malam Kedua di Hajimari**",
      "Setelah pertarungan dengan Raja Bayangan, kau kembali ke desa. Penduduk merayakanmu sebagai pahlawan.",
      "Tapi malam itu, sesosok bayangan berwajah cermin muncul di danau desa. 「Kau menguasai Hiragana, tapi Katakana milikku!」",
      "**Phantom Cermin**: 「Tanpa Katakana, tak ada kata asing yang bisa diucapkan. Nama-nama asing, kata serapan... semua milikku!」",
      "Yuki: 「Katakana adalah aksara saudari Hiragana. Digunakan untuk kata serapan, nama asing, dan onomatope. Pelajari dulu lima vokalnya.」",
    ],
    outro: [
      "Phantom Cermin mundur ke dalam danau. 「Hmph. Vokal saja tidak cukup...」",
      "Yuki: «Bagus! Pola Katakana sama persis dengan Hiragana, hanya bentuknya yang berbeda - lebih bersudut dan tegas.」",
      "**Stage 11 selesai! +60 XP, 20 koin**",
    ],
    lesson: {
      title: "Katakana Vokal (アイウエオ)",
      rows: [
        { kana: "ア", romaji: "a", meaning: "Katakana 'a'" },
        { kana: "イ", romaji: "i", meaning: "Katakana 'i'" },
        { kana: "ウ", romaji: "u", meaning: "Katakana 'u'" },
        { kana: "エ", romaji: "e", meaning: "Katakana 'e'" },
        { kana: "オ", romaji: "o", meaning: "Katakana 'o'" },
      ],
      note: "Katakana vokal bentuknya lebih tegas & bersudut dibanding Hiragana. Tapi romaji-nya SAMA PERSIS!",
    },
    enemies: [
      {
        id: "mirror-echo",
        name: "Echo Cermin",
        nameJp: "エコー",
        sprite: "🪞",
        hp: 4,
        attack: 2,
        description: "Bayangan cermin yang memantulkan kata.",
        color: "#b0bec5",
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Katakana apa ini?",
        kana: "ア",
        options: ["a", "i", "u", "e"],
        answer: 0,
        hint: "Sama romaji-nya dengan あ",
      },
      {
        type: "choice",
        prompt: "Pilih Katakana 'i':",
        options: ["ア", "イ", "ウ", "エ"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk ウ?",
        kana: "ウ",
        answer: ["u"],
      },
      {
        type: "typing",
        prompt: "Romaji untuk エ?",
        kana: "エ",
        answer: ["e"],
      },
      {
        type: "typing",
        prompt: "Romaji untuk オ?",
        kana: "オ",
        answer: ["o"],
      },
    ],
    reward: { xp: 60 },
  },

  // ===== STAGE 12: KATAKANA K, S, T =====
  {
    id: "hajimari-12",
    worldId: "hajimari",
    index: 12,
    chapter: 2,
    title: "Serangan Tiga Deret",
    subtitle: "Katakana K, S, T",
    type: "battle",
    intro: [
      "**Pinggir Danau**",
      "Phantom Cermin memanggil tiga monster: K-Beast, S-Wraith, T-Golem.",
      "「Kau harus menguasai tiga deret Katakana sekaligus untuk melewati mereka!」",
      "Yuki: 「Tenang, pola sama dengan Hiragana. Hanya bentuk yang beda.」",
    ],
    outro: [
      "Tiga monster hancur. Phantom Cermin terlihat terkejut.",
      "「Kau... cepat belajar.」",
      "**Stage 12 selesai! +80 XP, 25 koin**",
    ],
    lesson: {
      title: "Katakana K, S, T",
      rows: [
        { kana: "カ", romaji: "ka", meaning: "K+A" },
        { kana: "キ", romaji: "ki", meaning: "K+I" },
        { kana: "ク", romaji: "ku", meaning: "K+U" },
        { kana: "ケ", romaji: "ke", meaning: "K+E" },
        { kana: "コ", romaji: "ko", meaning: "K+O" },
        { kana: "サ", romaji: "sa", meaning: "S+A" },
        { kana: "シ", romaji: "shi", meaning: "S+I (shi!)" },
        { kana: "ス", romaji: "su", meaning: "S+U" },
        { kana: "タ", romaji: "ta", meaning: "T+A" },
        { kana: "チ", romaji: "chi", meaning: "T+I (chi!)" },
        { kana: "ツ", romaji: "tsu", meaning: "T+U (tsu!)" },
      ],
      note: "Pengecualian tetap sama: shi (シ), chi (チ), tsu (ツ). Romaji identik dengan Hiragana!",
    },
    enemies: [
      {
        id: "k-beast",
        name: "K-Beast",
        nameJp: "カビースト",
        sprite: "🐺",
        hp: 6,
        attack: 3,
        color: "#ef5350",
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Katakana 'ka' adalah?",
        options: ["カ", "キ", "ク", "ケ"],
        answer: 0,
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "シ",
        answer: ["shi"],
        hint: "Sama pengecualiannya dengan し",
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "チ",
        answer: ["chi"],
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ツ",
        answer: ["tsu"],
      },
      {
        type: "choice",
        prompt: "Pilih 'su':",
        options: ["サ", "シ", "ス", "ソ"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "コ",
        answer: ["ko"],
      },
    ],
    reward: { xp: 80 },
  },

  // ===== STAGE 13: KATAKANA N, H =====
  {
    id: "hajimari-13",
    worldId: "hajimari",
    index: 13,
    chapter: 2,
    title: "Bayangan Berbisik N & H",
    subtitle: "Katakana N, H",
    type: "battle",
    intro: [
      "**Hutan Bambu Kedua**",
      "Phantom Cermin: 「Coba hadapi deret N dan H! Bayangan yang sama akan menyergapmu.」",
      "「Tapi kali ini, aku akan mengacaukan pendengaranmu!」",
      "Yuki: 「Fokus. Ingat pola vokal A-I-U-E-O.」",
    ],
    outro: [
      "Bayangan N & H dapat dikalahkan. Hutan kembali tenang.",
      "Yuki: 「Hebat! 'fu' (フ) masih jadi pengecualian seperti Hiragana.」",
      "**Stage 13 selesai! +90 XP, 30 koin**",
    ],
    lesson: {
      title: "Katakana N & H",
      rows: [
        { kana: "ナ", romaji: "na", meaning: "N+A" },
        { kana: "ニ", romaji: "ni", meaning: "N+I" },
        { kana: "ヌ", romaji: "nu", meaning: "N+U" },
        { kana: "ネ", romaji: "ne", meaning: "N+E" },
        { kana: "ノ", romaji: "no", meaning: "N+O" },
        { kana: "ハ", romaji: "ha", meaning: "H+A" },
        { kana: "ヒ", romaji: "hi", meaning: "H+I" },
        { kana: "フ", romaji: "fu", meaning: "H+U (fu, bukan hu!)" },
        { kana: "ヘ", romaji: "he", meaning: "H+E" },
        { kana: "ホ", romaji: "ho", meaning: "H+O" },
      ],
      note: "フ dibaca 'fu' (bukan 'hu') - sama seperti ふ di Hiragana.",
    },
    enemies: [
      {
        id: "shadow-nh",
        name: "Bayangan NH",
        nameJp: "シャドー",
        sprite: "👁",
        hp: 7,
        attack: 3,
        color: "#7e57c2",
      },
    ],
    questions: [
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ナ",
        answer: ["na"],
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ニ",
        answer: ["ni"],
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ヌ",
        answer: ["nu"],
      },
      {
        type: "choice",
        prompt: "Romaji untuk フ?",
        options: ["hu", "fu", "ha", "ho"],
        answer: 1,
        hint: "Pengecualian! Sama seperti ふ",
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ホ",
        answer: ["ho"],
      },
      {
        type: "choice",
        prompt: "Pilih 'ne':",
        options: ["ナ", "ニ", "ネ", "ノ"],
        answer: 2,
      },
    ],
    reward: { xp: 90 },
  },

  // ===== STAGE 14: KATAKANA M, Y, R =====
  {
    id: "hajimari-14",
    worldId: "hajimari",
    index: 14,
    chapter: 2,
    title: "Tiga Bersaudara M, Y, R",
    subtitle: "Katakana M, Y, R",
    type: "battle",
    intro: [
      "**Lapangan Desa**",
      "Phantom Cermin mengirim tiga sosok: M-Witch, Y-Sprite, R-Knight.",
      "「Tiga deret sekaligus. Bisa kau tangani?」",
      "Yuki: 「Y hanya tiga huruf (ya, yu, yo) - sama seperti Hiragana.」",
    ],
    outro: [
      "Tiga sosok hancur bersamaan. Phantom Cermin mundur ke kuil tua.",
      "Yuki: «Hanya dua deret lagi dan kamu siap menghadapinya!»",
      "**Stage 14 selesai! +100 XP, 35 koin**",
    ],
    lesson: {
      title: "Katakana M, Y, R",
      rows: [
        { kana: "マ", romaji: "ma", meaning: "M+A" },
        { kana: "ミ", romaji: "mi", meaning: "M+I" },
        { kana: "ム", romaji: "mu", meaning: "M+U" },
        { kana: "メ", romaji: "me", meaning: "M+E" },
        { kana: "モ", romaji: "mo", meaning: "M+O" },
        { kana: "ヤ", romaji: "ya", meaning: "Y+A" },
        { kana: "ユ", romaji: "yu", meaning: "Y+U" },
        { kana: "ヨ", romaji: "yo", meaning: "Y+O" },
        { kana: "ラ", romaji: "ra", meaning: "R+A" },
        { kana: "リ", romaji: "ri", meaning: "R+I" },
        { kana: "ル", romaji: "ru", meaning: "R+U" },
        { kana: "レ", romaji: "re", meaning: "R+E" },
        { kana: "ロ", romaji: "ro", meaning: "R+O" },
      ],
      note: "Deret Y tetap hanya 3: ya, yu, yo. Tidak ada yi atau ye.",
    },
    enemies: [
      {
        id: "three-siblings",
        name: "Tiga Bersaudara",
        nameJp: "三人組",
        sprite: "👹",
        hp: 8,
        attack: 4,
        color: "#ffa726",
      },
    ],
    questions: [
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "マ",
        answer: ["ma"],
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ミ",
        answer: ["mi"],
      },
      {
        type: "choice",
        prompt: "Pilih 'me':",
        options: ["マ", "ミ", "メ", "モ"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ユ",
        answer: ["yu"],
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ラ",
        answer: ["ra"],
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "リ",
        answer: ["ri"],
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ロ",
        answer: ["ro"],
      },
    ],
    reward: { xp: 100 },
  },

  // ===== STAGE 15: MINI-BOSS - KATAKANA W, N & TEST =====
  {
    id: "hajimari-15",
    worldId: "hajimari",
    index: 15,
    chapter: 2,
    title: "Ujian Cermin Pertama",
    subtitle: "Mini-Boss: W, N & Review",
    type: "mini-boss",
    intro: [
      "**Kuil Tua Hajimari**",
      "Phantom Cermin menunggumu di dalam kuil. 「Lewati ujian ini, dan aku akan mengakui kemampuanmu.」",
      "「Deret W (ワ, ヲ, ン) dan ujian semua yang telah kau pelajari!」",
      "Yuki: 「ワ, ヲ, ン - terakhir! ヲ dibaca 'o' sebagai partikel objek. ン adalah konsonan akhir 'n'.」",
    ],
    outro: [
      "Phantom Cermin mundur. 「Kau... benar-benar serius. Pertarungan akhir menanti.」",
      "Ia mundur ke cermin besar di belakang kuil.",
      "**Stage 15 selesai! +150 XP, 50 koin, Badge: Lulus Ujian Katakana**",
    ],
    lesson: {
      title: "Katakana W & Sisa",
      rows: [
        { kana: "ワ", romaji: "wa", meaning: "W+A (partikel topik)" },
        { kana: "ヲ", romaji: "wo", meaning: "partikel objek (dibaca 'o')" },
        { kana: "ン", romaji: "n", meaning: "konsonan akhir 'n'" },
      ],
      note: "ン (n) mirip dengan ン vs シ - hati-hati! ヲ ditulis 'wo' tapi diucapkan 'o'.",
    },
    enemies: [
      {
        id: "mirror-test",
        name: "Cermin Ujian",
        nameJp: "鏡",
        sprite: "🪞",
        hp: 12,
        attack: 4,
        description: "Mini-boss: ujian 15 huruf Katakana.",
        color: "#90a4ae",
      },
    ],
    questions: [
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ワ",
        answer: ["wa"],
      },
      {
        type: "choice",
        prompt: "ン dibaca sebagai?",
        options: ["n", "wa", "wo", "u"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "「Review」 Romaji untuk カ?",
        options: ["ka", "ki", "ku", "ko"],
        answer: 0,
      },
      {
        type: "typing",
        prompt: "「Review」 Romaji:",
        kana: "シ",
        answer: ["shi"],
      },
      {
        type: "choice",
        prompt: "「Review」 Pilih 'fu':",
        options: ["ハ", "ヒ", "フ", "ホ"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "「Review」 Romaji:",
        kana: "ツ",
        answer: ["tsu"],
      },
      {
        type: "typing",
        prompt: "「Review」 Romaji:",
        kana: "ヨ",
        answer: ["yo"],
      },
      {
        type: "typing",
        prompt: "「Akhir」 Romaji:",
        kana: "ロ",
        answer: ["ro"],
      },
    ],
    reward: { xp: 150, badge: "Lulus Ujian Katakana" },
  },

  // ===== STAGE 16: DAKUTEN K =====
  {
    id: "hajimari-16",
    worldId: "hajimari",
    index: 16,
    chapter: 2,
    title: "Tanda Dakuten - Suara Bergetar",
    subtitle: "Dakuten: ガギグゲゴ",
    type: "lesson",
    intro: [
      "**Malam di Kuil**",
      "Phantom Cermin menghilang, tapi pintu kuil terkunci.",
      "Pendeta tua muncul: 「Untuk membuka pintu ini, kau harus menguasai Dakuten - tanda dua titik yang mengubah suara.」",
      "「K + Dakuten = G. Pelajari ini untuk membuka jalan.」",
    ],
    outro: [
      "Pintu kuil terbuka berderit.",
      "Pendeta: «Bagus! Dakuten mengubah K→G, S→Z, T→D, H→B. Ingat pola ini!»",
      "**Stage 16 selesai! +80 XP, 30 koin**",
    ],
    lesson: {
      title: "Dakuten Deret K (ガギグゲゴ)",
      rows: [
        { kana: "ガ", romaji: "ga", meaning: "カ + dakuten = G+A" },
        { kana: "ギ", romaji: "gi", meaning: "G+I" },
        { kana: "グ", romaji: "gu", meaning: "G+U" },
        { kana: "ゲ", romaji: "ge", meaning: "G+E" },
        { kana: "ゴ", romaji: "go", meaning: "G+O" },
      ],
      note: "Dakuten (゛) mengubah konsonan tidak bersuara menjadi bersuara: K→G, S→Z, T→D, H→B.",
    },
    enemies: [
      {
        id: "locked-door",
        name: "Pintu Terkunci",
        nameJp: "扉",
        sprite: "🚪",
        hp: 5,
        attack: 2,
        color: "#8d6e63",
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "ガ dibaca?",
        options: ["ka", "ga", "ta", "da"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ギ",
        answer: ["gi"],
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "グ",
        answer: ["gu"],
      },
      {
        type: "choice",
        prompt: "Pilih 'go':",
        options: ["ガ", "ギ", "ゴ", "ゲ"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ゲ",
        answer: ["ge"],
      },
    ],
    reward: { xp: 80 },
  },

  // ===== STAGE 17: DAKUTEN S, T, H =====
  {
    id: "hajimari-17",
    worldId: "hajimari",
    index: 17,
    chapter: 2,
    title: "Tiga Dakuten Bertubi",
    subtitle: "Dakuten Z, D, B",
    type: "battle",
    intro: [
      "** lorong Bawah Tanah Kuil**",
      "Tiga patung batu hidup dan menghalangi jalan: S→Z, T→D, H→B.",
      "Phantom Cermin tertawa dari kejauhan: 「Tiga dakuten sekaligus, hero!」",
      "Yuki: 「S+Dakuten=Z, T+Dakuten=D, H+Dakuten=B. Tetap fokus!」",
    ],
    outro: [
      "Tiga patung hancur. Lorong terbuka lebar.",
      "Yuki: «Hampir sampai ke cermin utama!»",
      "**Stage 17 selesai! +100 XP, 35 koin**",
    ],
    lesson: {
      title: "Dakuten Z, D, B",
      rows: [
        { kana: "ザ", romaji: "za", meaning: "サ + dakuten" },
        { kana: "ジ", romaji: "ji", meaning: "shi→ji (pengecualian!)" },
        { kana: "ズ", romaji: "zu", meaning: "su→zu" },
        { kana: "ダ", romaji: "da", meaning: "タ + dakuten" },
        { kana: "ヂ", romaji: "ji", meaning: "chi→ji (jarang dipakai)" },
        { kana: "ヅ", romaji: "zu", meaning: "tsu→zu (jarang dipakai)" },
        { kana: "バ", romaji: "ba", meaning: "ハ + dakuten" },
        { kana: "ビ", romaji: "bi", meaning: "B+I" },
        { kana: "ブ", romaji: "bu", meaning: "B+U" },
      ],
      note: "ジ (ji) dan ヂ (ji) bunyinya sama. Begitu juga ズ (zu) dan ヅ (zu). ヅ/ヂ jarang dipakai.",
    },
    enemies: [
      {
        id: "stone-trio",
        name: "Tiga Patung Batu",
        nameJp: "石像",
        sprite: "🗿",
        hp: 9,
        attack: 4,
        color: "#795548",
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "ジ dibaca?",
        options: ["shi", "ji", "zi", "di"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ズ",
        answer: ["zu"],
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ダ",
        answer: ["da"],
      },
      {
        type: "choice",
        prompt: "Pilih 'ba':",
        options: ["バ", "ビ", "ブ", "ボ"],
        answer: 0,
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ビ",
        answer: ["bi"],
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ブ",
        answer: ["bu"],
      },
    ],
    reward: { xp: 100 },
  },

  // ===== STAGE 18: HANDAKUTEN (P) =====
  {
    id: "hajimari-18",
    worldId: "hajimari",
    index: 18,
    chapter: 2,
    title: "Tanda Handakuten - P",
    subtitle: "Handakuten: パピプペポ",
    type: "battle",
    intro: [
      "**Aula Cermin**",
      "Phantom Cermin menunggu di tengah aula penuh cermin.",
      "「Kau tahu Dakuten. Tapi tahukah kau Handakuten? Tanda lingkaran kecil yang mengubah H menjadi P!」",
      "Yuki: 「H + Handakuten (゜) = P. Hanya deret H yang bisa dapat Handakuten.」",
    ],
    outro: [
      "Cermin-cermin di aula retak satu per satu.",
      "Phantom Cermin: 「Tidak mungkin... kau bisa menguasai semuanya!」",
      "**Stage 18 selesai! +110 XP, 40 koin**",
    ],
    lesson: {
      title: "Handakuten Deret H (パピプペポ)",
      rows: [
        { kana: "パ", romaji: "pa", meaning: "ハ + handakuten" },
        { kana: "ピ", romaji: "pi", meaning: "P+I" },
        { kana: "プ", romaji: "pu", meaning: "P+U" },
        { kana: "ペ", romaji: "pe", meaning: "P+E" },
        { kana: "ポ", romaji: "po", meaning: "P+O" },
      ],
      note: "Handakuten (゜) hanya untuk deret H: H→P. Kontras dengan dakuten H→B.",
    },
    enemies: [
      {
        id: "mirror-horde",
        name: "Pasukan Cermin",
        nameJp: "鏡軍",
        sprite: "🔲",
        hp: 10,
        attack: 4,
        color: "#cfd8dc",
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "パ dibaca?",
        options: ["ha", "ba", "pa", "ma"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ピ",
        answer: ["pi"],
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "プ",
        answer: ["pu"],
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ペ",
        answer: ["pe"],
      },
      {
        type: "typing",
        prompt: "Romaji:",
        kana: "ポ",
        answer: ["po"],
      },
      {
        type: "choice",
        prompt: "「Pengecualian」 ジ vs ヂ, mana yang lebih sering dipakai?",
        options: ["ジ", "ヂ", "sama saja", "tidak dipakai"],
        answer: 0,
      },
    ],
    reward: { xp: 110 },
  },

  // ===== STAGE 19: KATA SERAPAN =====
  {
    id: "hajimari-19",
    worldId: "hajimari",
    index: 19,
    chapter: 2,
    title: "Kata Serapan dari Dunia",
    subtitle: "Katakana Words: Coffee, TV, etc.",
    type: "battle",
    intro: [
      "**Aula Cermin - Pertarungan Akhir Dimulai**",
      "Phantom Cermin: 「Kau tahu hurufnya. Tapi bisa kau baca kata serapan?」",
      "「Katakana dipakai untuk kata asing! Misal: コーヒー (ko-hi-, kopi), テレビ (terebi, TV).」",
      "Yuki: 「Ini ujian sebelum menghadap Phantom asli. Gabungkan huruf menjadi kata!」",
    ],
    outro: [
      "Phantom Cermin mundur ke cermin terakhir. «Pertarungan akhir...»",
      "**Stage 19 selesai! +130 XP, 50 koin**",
    ],
    lesson: {
      title: "Kata Serapan Katakana",
      rows: [
        { kana: "コーヒー", romaji: "ko-hi-", meaning: "kopi (coffee)" },
        { kana: "テレビ", romaji: "terebi", meaning: "TV (television)" },
        { kana: "ペン", romaji: "pen", meaning: "pulpen (pen)" },
        { kana: "ミルク", romaji: "miruku", meaning: "susu (milk)" },
        { kana: "アイス", romaji: "aisu", meaning: "es krim (ice)" },
        { kana: "カメラ", romaji: "kamera", meaning: "kamera (camera)" },
      ],
      note: "Kata serapan di-Jepang-kan dengan Katakana. Bunyi disesuaikan: 'coffee'→'koohii', 'TV'→'terebi'.",
    },
    enemies: [
      {
        id: "word-phantom",
        name: "Phantom Kata",
        nameJp: "ファントム",
        sprite: "👻",
        hp: 11,
        attack: 5,
        color: "#b39ddb",
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Apa arti コーヒー?",
        kana: "コーヒー",
        options: ["kopi", "teh", "susu", "jus"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "Apa arti テレビ?",
        kana: "テレビ",
        options: ["telepon", "TV", "radio", "komputer"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk ペン (pulpen):",
        kana: "ペン",
        answer: ["pen"],
      },
      {
        type: "choice",
        prompt: "ミルク berarti?",
        options: ["roti", "susu", "mentega", "keju"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk カメラ:",
        kana: "カメラ",
        answer: ["kamera"],
      },
      {
        type: "choice",
        prompt: "「Tantangan」 カ + ラ + ス = ?",
        options: ["karasu (gagak)", "kurasu (kelas)", "karasu (hujan)", "kurasu (luluh)"],
        answer: 1,
        hint: "Kata serapan dari 'class'",
      },
    ],
    reward: { xp: 130 },
  },

  // ===== STAGE 20: BOSS - PHANTOM CERMIN =====
  {
    id: "hajimari-20",
    worldId: "hajimari",
    index: 20,
    chapter: 2,
    title: "Phantom Cermin Terakhir",
    subtitle: "Bos Akhir Bab 2",
    type: "boss",
    intro: [
      "**Cermin Utama - Aula Pusat**",
      "Phantom Cermin muncul dalam wujud sebenarnya - sesosok raksasa cermin dengan 7 wajah.",
      "「Aku adalah bayangan semua huruf asing yang tidak kau pelajari.」",
      "「Tapi kau... kau sudah mempelajari Hiragana DAN Katakana. Kau bukan lagi pemula!」",
      "Yuki: «Pertarungan akhir Bab Katakana! Tunjukkan apa yang kau tahu!»",
      "**PERTARUNGAN AKHIR DIMULAI**",
    ],
    outro: [
      "Phantom Cermin pecah menjadi 7 serpihan cahaya.",
      "「Kau... menguasai dua aksara sekaligus... aku... lega...」",
      "Serpihan itu berkumpul menjadi permata keemasan - **Permata Aksara**.",
      "Yuki: «Kau benar-benar pahlawan Hajimari! Sekarang kau siap ke kerajaan manusia - Vassal Kingdom!»",
      "Penduduk desa berkumpul, merayakanmu. Paspor Petualang kini bersinar dengan dua warna.",
      "**BAB 2 SELESAI! +600 XP, 200 koin, Badge: Master Aksara, Item: Permata Aksara**",
      "**Dunia baru sepenuhnya terbuka: Vassal Kingdom (JLPT N5)**",
    ],
    lesson: {
      title: "Ujian Akhir Katakana",
      rows: [
        { kana: "ア", romaji: "a", meaning: "vokal" },
        { kana: "カ", romaji: "ka", meaning: "deret K" },
        { kana: "サ", romaji: "sa", meaning: "deret S" },
        { kana: "ガ", romaji: "ga", meaning: "dakuten K" },
        { kana: "パ", romaji: "pa", meaning: "handakuten H" },
        { kana: "ン", romaji: "n", meaning: "konsonan akhir" },
      ],
      note: "Gabungkan semua: vokal + konsonan + dakuten + handakuten = lengkap!",
    },
    enemies: [
      {
        id: "mirror-phantom",
        name: "Phantom Cermin Tujuh Wajah",
        nameJp: "鏡の怪",
        sprite: "🔮",
        hp: 16,
        attack: 5,
        description: "Bos akhir Bab 2. Wujud bayangan semua kata asing yang tak dipelajari.",
        color: "#7c4dff",
      },
    ],
    questions: [
      // Final review covering all Katakana
      {
        type: "typing",
        prompt: "「Vokal」 Romaji untuk オ?",
        kana: "オ",
        answer: ["o"],
      },
      {
        type: "choice",
        prompt: "「Deret K」 Pilih 'ki':",
        options: ["カ", "キ", "ク", "コ"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "「Pengecualian」 Romaji untuk シ?",
        kana: "シ",
        answer: ["shi"],
      },
      {
        type: "choice",
        prompt: "「Dakuten」 ガ dibaca?",
        options: ["ka", "ga", "ta", "da"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "「Handakuten」 パ dibaca?",
        options: ["ha", "ba", "pa", "ma"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "「Akhir」 Romaji untuk ン?",
        kana: "ン",
        answer: ["n"],
      },
      {
        type: "choice",
        prompt: "「Kata」 コーヒー artinya?",
        kana: "コーヒー",
        options: ["kopi", "teh", "jus", "soda"],
        answer: 0,
      },
      {
        type: "typing",
        prompt: "「Kata」 Romaji テレビ:",
        kana: "テレビ",
        answer: ["terebi"],
      },
      {
        type: "choice",
        prompt: "「Akhir」 Mana yang merupakan KATAKANA?",
        options: ["あ", "ア", "安", "a"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "「Selamat tinggal, Phantom」 Romaji: カメラ",
        kana: "カメラ",
        answer: ["kamera"],
      },
    ],
    reward: { xp: 600, badge: "Master Aksara", item: "Permata Aksara" },
  },
];
