import type { Stage } from "./types";

// ===== MINATO PORT - Tingkat Madya Bawah (20 STAGES, 2 CHAPTERS) =====
// Chapter 1 (Stage 1-10): Verb forms (te/nai/ta), daily conversation, basic kanji 100-200
// Chapter 2 (Stage 11-20): Advanced grammar, more kanji 200-300, complex sentences
// Story: Player arrives at Minato Port, helps sailors & merchants, fixes ships, explores islands

export const N4_STAGES: Stage[] = [
  // ===== STAGE 1: Tiba di Minato Port =====
  {
    id: "n4-1",
    worldId: "n4",
    index: 1,
    chapter: 1,
    title: "Tiba di Minato Port",
    subtitle: "Salam & Perkenalan Lanjutan",
    type: "lesson",
    intro: [
      "**Dermaga Minato Port - Pagi**",
      "Setelah perjalanan dari Vassal Kingdom, kau tiba di pelabuhan ramai Minato. Bau garam laut dan ikan segar menyapa.",
      "Pelaut tua menyapa: ãããã£ãããã¾ã! Selamat datang, pengelana!ã",
      "ãDi sini orang pakai bahasa lebih sopan. Pelajari salam formal & percakapan pelaut.ã",
    ],
    outro: [
      "Pelaut tersenyum. ãããã£ãããã¾ã! Silakan masuk ke pelabuhan.ã",
      "**Stage 1 selesai! +80 XP**",
    ],
    lesson: {
      title: "Salam Formal N4",
      rows: [
        { kana: "ããã£ãããã¾ã", romaji: "irasshaimase", meaning: "selamat datang (formal, toko)" },
        { kana: "ããã ãã¾ã", romaji: "itadakimasu", meaning: "selamat makan (sebelum)" },
        { kana: "ãã¡ãããã¾", romaji: "gochisousama", meaning: "terima kasih untuk makanan" },
        { kana: "ãããã¿ãªãã", romaji: "oyasuminasai", meaning: "selamat malam (sebelum tidur)" },
        { kana: "ã¯ããã¾ãã¦", romaji: "hajimemashite", meaning: "senang berkenalan" },
        { kana: "ããããã§ãã", romaji: "ogenki desu ka", meaning: "apa kabar (formal)" },
        { kana: "ããããã ãã", romaji: "okake kudasai", meaning: "silakan duduk" },
        { kana: "ãã¤ãããã¾ã", romaji: "shitsurei shimasu", meaning: "permisi / maaf (masuk ruangan)" },
      ],
      note: "Salam formal N4 lebih panjang dari N5. 'irasshaimase' dipakai di toko/restoran.",
    },
    enemies: [
      {
        id: "dock-guard",
        name: "Penjaga Dermaga",
        sprite: "ð§ââï¸",
        hp: 8,
        attack: 3,
        color: "#4fc3f7",
        abilities: ["regen"],
      },
    ],
    questions: [
      { type: "choice", prompt: "ãããã£ãããã¾ãã dipakai di?", kana: "ããã£ãããã¾ã", options: ["Toko/restoran", "Sekolah", "Rumah", "Kuil"], answer: 0 },
      { type: "typing", prompt: "Romaji 'selamat makan (sebelum)':", kana: "ããã ãã¾ã", answer: ["itadakimasu"] },
      { type: "choice", prompt: "ããã¡ãããã¾ã artinya?", kana: "ãã¡ãããã¾", options: ["Selamat makan sebelum", "Terima kasih makanan", "Selamat malam", "Selamat tinggal"], answer: 1 },
      { type: "typing", prompt: "Romaji 'selamat malam (sebelum tidur)':", kana: "ãããã¿ãªãã", answer: ["oyasuminasai"] },
      { type: "choice", prompt: "ãããããã§ããã artinya?", kana: "ããããã§ãã", options: ["Apa kabar (formal)", "Siapa kamu", "Dimana", "Kapan"], answer: 0 },
    ],
    reward: { xp: 80 },
  },

  // ===== STAGE 2: Verb te-form basics =====
  {
    id: "n4-2",
    worldId: "n4",
    index: 2,
    chapter: 1,
    title: "Bentuk ã¦ (te-form)",
    subtitle: "Kata Kerja Bentuk te",
    type: "battle",
    intro: [
      "**Toko Perbekalan Pelaut**",
      "Pemilik toko: ãããã ã¿ã¦ ãã ãã! Lihat ini!ã",
      "ãBentuk ã¦ (te) penting untuk: permintaan, urutan aksi, hubungan. Pelajari!ã",
    ],
    outro: ["Pemilik toko: ãSekarang kau bisa minta & cerita urutan!ã", "**Stage 2 selesai! +90 XP**"],
    lesson: {
      title: "te-form Dasar",
      rows: [
        { kana: "ãã¹ã¦", romaji: "tabete", meaning: "makan (te-form)" },
        { kana: "ã®ãã§", romaji: "nonde", meaning: "minum (te-form)" },
        { kana: "ãã£ã¦", romaji: "itte", meaning: "pergi (te-form)" },
        { kana: "ãã¦", romaji: "kite", meaning: "datang (te-form)" },
        { kana: "ã¿ã¦", romaji: "mite", meaning: "lihat (te-form)" },
        { kana: "ãã¦", romaji: "shite", meaning: "lakukan (te-form)" },
        { kana: "ããã¦", romaji: "kaite", meaning: "tulis (te-form)" },
        { kana: "ããã§", romaji: "yonde", meaning: "baca (te-form)" },
      ],
      note: "te-form dipakai untuk: permintaan (ãã¦ ãã ãã), urutan (ãã¦ãã), sedang (ãã¦ãã).",
    },
    enemies: [
      { id: "verb-spirit", name: "Roh Kata Kerja", sprite: "ð»", hp: 10, attack: 4, color: "#7e57c2", abilities: ["multi-attack"] },
    ],
    questions: [
      { type: "typing", prompt: "te-form dari ãã¹ã (makan):", kana: "ãã¹ã¦", answer: ["tabete"] },
      { type: "typing", prompt: "te-form dari ã®ã (minum):", kana: "ã®ãã§", answer: ["nonde"] },
      { type: "typing", prompt: "te-form dari ãã (pergi):", kana: "ãã£ã¦", answer: ["itte"] },
      { type: "typing", prompt: "te-form dari ã¿ã (lihat):", kana: "ã¿ã¦", answer: ["mite"] },
      { type: "typing", prompt: "te-form dari ãã (lakukan):", kana: "ãã¦", answer: ["shite"] },
      { type: "typing", prompt: "te-form dari ãã (tulis):", kana: "ããã¦", answer: ["kaite"] },
    ],
    reward: { xp: 90 },
  },

  // ===== STAGE 3: te-form request =====
  {
    id: "n4-3",
    worldId: "n4",
    index: 3,
    chapter: 1,
    title: "Permintaan dengan ã¦",
    subtitle: "ãã¦ ãã ãã (mohon)",
    type: "battle",
    intro: [
      "**Dermaga Perbaikan Kapal**",
      "Tukang kayu: ãããã ãªããã¦ ãã ãã! Perbaiki ini!Â»",
      "ãBentuk ãã¦ ãã ãã = mohon/permintaan sopan. Pelajari!Â»",
    ],
    outro: ["Kapal terpasang. Tukang: Â«Terima kasih, pengelana!Â»", "**Stage 3 selesai! +100 XP**"],
    lesson: {
      title: "ãã¦ ãã ãã (Permintaan)",
      rows: [
        { kana: "ãã¹ã¦ ãã ãã", romaji: "tabete kudasai", meaning: "mohon makan" },
        { kana: "ã®ãã§ ãã ãã", romaji: "nonde kudasai", meaning: "mohon minum" },
        { kana: "ãã£ã¦ ãã ãã", romaji: "itte kudasai", meaning: "mohon pergi" },
        { kana: "ã¿ã¦ ãã ãã", romaji: "mite kudasai", meaning: "mohon lihat" },
        { kana: "ããã¦ ãã ãã", romaji: "kiite kudasai", meaning: "mohon dengar" },
        { kana: "ã¾ã£ã¦ ãã ãã", romaji: "matte kudasai", meaning: "mohon tunggu" },
      ],
      note: "ãã¦ ãã ãã = mohon/silakan (permintaan sopan). Lebih sopan dari perintah langsung.",
    },
    enemies: [
      { id: "ship-breaker", name: "Penghancur Kapal", sprite: "ð¦", hp: 12, attack: 4, color: "#26a69a", abilities: ["enrage"] },
    ],
    questions: [
      { type: "choice", prompt: "ããã¹ã¦ ãã ããã artinya?", kana: "ãã¹ã¦ ãã ãã", options: ["Mohon makan", "Mohon minum", "Mohon pergi", "Mohon tunggu"], answer: 0 },
      { type: "typing", prompt: "Romaji 'mohon tunggu':", kana: "ã¾ã£ã¦ ãã ãã", answer: ["matte kudasai"] },
      { type: "typing", prompt: "te-form + kudasai dari ã®ã:", kana: "ã®ãã§ ãã ãã", answer: ["nonde kudasai"] },
      { type: "choice", prompt: "ãã¿ã¦ ãã ããã artinya?", kana: "ã¿ã¦ ãã ãã", options: ["Mohon lihat", "Mohon dengar", "Mohon tunggu", "Mohon pergi"], answer: 0 },
      { type: "typing", prompt: "te-form + kudasai dari ãã (dengar):", kana: "ããã¦ ãã ãã", answer: ["kiite kudasai"] },
    ],
    reward: { xp: 100 },
  },

  // ===== STAGE 4: nai-form (negative) =====
  {
    id: "n4-4",
    worldId: "n4",
    index: 4,
    chapter: 1,
    title: "Bentuk Negatif ãªã",
    subtitle: "ããªã (tidak)",
    type: "battle",
    intro: [
      "**Pasar Ikan**",
      "Pedagang ikan: ããããªã ãã¹ãªã? Tidak makan ikan?Â»",
      "ãBentuk ããªã = negatif kata kerja. Pelajari!Â»",
    ],
    outro: ["Pedagang: Â«Paham negatif sekarang!Â»", "**Stage 4 selesai! +110 XP**"],
    lesson: {
      title: "nai-form (Negatif)",
      rows: [
        { kana: "ãã¹ãªã", romaji: "tabenai", meaning: "tidak makan" },
        { kana: "ã®ã¾ãªã", romaji: "nomanai", meaning: "tidak minum" },
        { kana: "ãããªã", romaji: "ikanai", meaning: "tidak pergi" },
        { kana: "ããªã", romaji: "konai", meaning: "tidak datang" },
        { kana: "ã¿ãªã", romaji: "minai", meaning: "tidak lihat" },
        { kana: "ããªã", romaji: "shinai", meaning: "tidak lakukan" },
        { kana: "ãããªã", romaji: "kakanai", meaning: "tidak tulis" },
        { kana: "ãã¾ãªã", romaji: "yomanai", meaning: "tidak baca" },
      ],
      note: "nai-form = negatif. Pola: ganti akhir â ããªã. Untuk ãã¾ã: tabeMASU â tabeNAI.",
    },
    enemies: [
      { id: "negation-shade", name: "Bayangan Negasi", sprite: "ð«", hp: 14, attack: 5, color: "#607d8b", abilities: ["poison", "shield"] },
    ],
    questions: [
      { type: "typing", prompt: "nai-form dari ãã¹ã:", kana: "ãã¹ãªã", answer: ["tabenai"] },
      { type: "typing", prompt: "nai-form dari ã®ã:", kana: "ã®ã¾ãªã", answer: ["nomanai"] },
      { type: "typing", prompt: "nai-form dari ãã:", kana: "ãããªã", answer: ["ikanai"] },
      { type: "typing", prompt: "nai-form dari ãã (datang):", kana: "ããªã", answer: ["konai"] },
      { type: "typing", prompt: "nai-form dari ãã:", kana: "ããªã", answer: ["shinai"] },
      { type: "choice", prompt: "ããã¾ãªãã artinya?", kana: "ãã¾ãªã", options: ["Tidak baca", "Tidak tulis", "Tidak lihat", "Tidak dengar"], answer: 0 },
    ],
    reward: { xp: 110 },
  },

  // ===== STAGE 5: ta-form (past) =====
  {
    id: "n4-5",
    worldId: "n4",
    index: 5,
    chapter: 1,
    title: "Bentuk Lampau ã",
    subtitle: "ãã (sudah)",
    type: "lesson",
    intro: [
      "**Warung Soba**",
      "Pelayan: ããã ãã¹ã? Sudah makan?Â»",
      "ãBentuk ãã = lampau (sudah). Pelajari!Â»",
    ],
    outro: ["Pelayan: Â«Sekarang bisa cerita masa lalu!Â»", "**Stage 5 selesai! +120 XP**"],
    lesson: {
      title: "ta-form (Lampau)",
      rows: [
        { kana: "ãã¹ã", romaji: "tabeta", meaning: "sudah makan" },
        { kana: "ã®ãã ", romaji: "nonda", meaning: "sudah minum" },
        { kana: "ãã£ã", romaji: "itta", meaning: "sudah pergi" },
        { kana: "ãã", romaji: "kita", meaning: "sudah datang" },
        { kana: "ã¿ã", romaji: "mita", meaning: "sudah lihat" },
        { kana: "ãã", romaji: "shita", meaning: "sudah lakukan" },
        { kana: "ããã", romaji: "kaita", meaning: "sudah tulis" },
        { kana: "ããã ", romaji: "yonda", meaning: "sudah baca" },
      ],
      note: "ta-form = lampau. Pola: te-form ganti ã¦âã. tabeteâtabeta, nondeânonda.",
    },
    enemies: [
      { id: "time-echo", name: "Gema Waktu", sprite: "â³", hp: 16, attack: 5, color: "#cddc39", abilities: ["shield", "regen"] },
    ],
    questions: [
      { type: "typing", prompt: "ta-form dari ãã¹ã:", kana: "ãã¹ã", answer: ["tabeta"] },
      { type: "typing", prompt: "ta-form dari ã®ã:", kana: "ã®ãã ", answer: ["nonda"] },
      { type: "typing", prompt: "ta-form dari ãã:", kana: "ãã£ã", answer: ["itta"] },
      { type: "typing", prompt: "ta-form dari ãã:", kana: "ãã", answer: ["kita"] },
      { type: "typing", prompt: "ta-form dari ãã:", kana: "ãã", answer: ["shita"] },
      { type: "choice", prompt: "ãããã ã artinya?", kana: "ããã ", options: ["Sudah baca", "Sudah tulis", "Sudah lihat", "Sudah dengar"], answer: 0 },
    ],
    reward: { xp: 120 },
  },

  // ===== STAGE 6: Mini-boss - verb conjugation master =====
  {
    id: "n4-6",
    worldId: "n4",
    index: 6,
    chapter: 1,
    title: "Ujian Konjugasi",
    subtitle: "Mini-Boss: Master Konjugasi",
    type: "mini-boss",
    intro: [
      "**Gudang Pelabuhan**",
      "Sesosok pria tua berjanggut muncul: ãAku **Konju**, master konjugasi. Lemati ujianku!Â»",
      "ãKau harus menguasai semua bentuk: ã¾ã, ã¦, ãªã, ã. Mulai!Â»",
    ],
    outro: ["Konju: Â«Kau lulus! Lanjut ke pulau utama.Â»", "**Stage 6 selesai! +180 XP, Badge: Lulus Konjugasi**"],
    lesson: undefined,
    enemies: [
      { id: "konju", name: "Konju Master Konjugasi", sprite: "ð§ââï¸", hp: 40, attack: 6, color: "#7c4dff", abilities: ["enrage", "shield", "counter"] },
    ],
    questions: [
      { type: "choice", prompt: "ãte-form dari ãã¹ãã", options: ["ãã¹ã¦", "ãã¹ã", "ãã¹ãªã", "ãã¹ã¾ã"], answer: 0 },
      { type: "choice", prompt: "ãnai-form dari ã®ãã", options: ["ã®ãã§", "ã®ã¾ãªã", "ã®ãã ", "ã®ã¿ã¾ã"], answer: 1 },
      { type: "choice", prompt: "ãta-form dari ããã", options: ["ãã£ã¦", "ãããªã", "ãã£ã", "ããã¾ã"], answer: 2 },
      { type: "typing", prompt: "te-form + kudasai dari ã¿ã:", kana: "ã¿ã¦ ãã ãã", answer: ["mite kudasai"] },
      { type: "typing", prompt: "nai-form dari ãã:", kana: "ããªã", answer: ["shinai"] },
      { type: "typing", prompt: "ta-form dari ãã:", kana: "ããã", answer: ["kaita"] },
      { type: "choice", prompt: "ãã¾ã£ã¦ ãã ããã artinya?", kana: "ã¾ã£ã¦ ãã ãã", options: ["Mohon tunggu", "Mohon lihat", "Mohon dengar", "Mohon pergi"], answer: 0 },
      { type: "typing", prompt: "nai-form dari ãã:", kana: "ãã¾ãªã", answer: ["yomanai"] },
    ],
    reward: { xp: 180, badge: "Lulus Konjugasi" },
  },

  // ===== STAGE 7: Particles ã«, ã§, ã¸ =====
  {
    id: "n4-7",
    worldId: "n4",
    index: 7,
    chapter: 1,
    title: "Partikel Arah & Lokasi",
    subtitle: "ã«, ã§, ã¸",
    type: "battle",
    intro: [
      "**Peta Pelabuhan**",
      "Navigator: ãã©ãã¸ ããã¾ãã? Mau ke mana?Â»",
      "ãPartikel ã« (tujuan), ã§ (lokasi aksi), ã¸ (arah). Pelajari!Â»",
    ],
    outro: ["Navigator: Â«Sekarang kau bisa cari arah!Â»", "**Stage 7 selesai! +130 XP**"],
    lesson: {
      title: "Partikel ã«ã»ã§ã»ã¸",
      rows: [
        { kana: "ãã£ããã« ãã", romaji: "gakkou ni iku", meaning: "pergi ke sekolah (tujuan)" },
        { kana: "ã¿ãã§ ãã", romaji: "mise de kau", meaning: "beli di toko (lokasi aksi)" },
        { kana: "ãã¿ã¸ ãã", romaji: "umi e iku", meaning: "pergi ke laut (arah)" },
        { kana: "ããã« ããã", romaji: "ie ni kaeru", meaning: "pulang ke rumah" },
        { kana: "ã¨ããããã§ ã¹ãããããã", romaji: "toshokan de benkyou suru", meaning: "belajar di perpustakaan" },
      ],
      note: "ã« = tujuan/waktu, ã§ = lokasi aksi/tempat, ã¸ = arah (dibaca 'e').",
    },
    enemies: [
      { id: "lost-sailor", name: "Pelaut Tersesat", sprite: "ð§­", hp: 18, attack: 5, color: "#4fc3f7", abilities: ["time-pressure"] },
    ],
    questions: [
      { type: "choice", prompt: "ããã£ãã___ããã partikel yang benar?", kana: "ãã£ããã« ãã", options: ["ã«", "ã§", "ã", "ã"], answer: 0 },
      { type: "choice", prompt: "ãã¿ã___ããã partikel yang benar?", kana: "ã¿ãã§ ãã", options: ["ã«", "ã§", "ã¸", "ã"], answer: 1 },
      { type: "choice", prompt: "ããã¿___ããã partikel yang benar?", kana: "ãã¿ã¸ ãã", options: ["ã«", "ã§", "ã¸", "ã"], answer: 2 },
      { type: "choice", prompt: "Partikel 'tujuan/waktu':", options: ["ã«", "ã§", "ã¸", "ã"], answer: 0 },
      { type: "choice", prompt: "Partikel 'lokasi aksi':", options: ["ã«", "ã§", "ã¸", "ã"], answer: 1 },
      { type: "typing", prompt: "Romaji 'pulang ke rumah':", kana: "ããã« ããã", answer: ["ie ni kaeru"] },
    ],
    reward: { xp: 130 },
  },

  // ===== STAGE 8: Adjective past form =====
  {
    id: "n4-8",
    worldId: "n4",
    index: 8,
    chapter: 1,
    title: "Kata Sifat Lampau",
    subtitle: "Sifat -i & -na bentuk lampau",
    type: "battle",
    intro: [
      "**Toko Pakaian**",
      "Penjahit: ããã® ãµãã¯ ãããã£ã! Baju ini mahal!Â»",
      "ãSifat -i bentuk lampau: ããã£ã. Sifat -na: ãã ã£ã. Pelajari!Â»",
    ],
    outro: ["Penjahit: Â«Sekarang bisa deskripsi masa lalu!Â»", "**Stage 8 selesai! +140 XP**"],
    lesson: {
      title: "Sifat Lampau",
      rows: [
        { kana: "ãããã£ã", romaji: "takakatta", meaning: "mahal (lampau -i)" },
        { kana: "ãã®ããã£ã", romaji: "tanoshikatta", meaning: "seru (lampau -i)" },
        { kana: "ããããã£ã", romaji: "oishikatta", meaning: "enak (lampau -i)" },
        { kana: "ãããã ã£ã", romaji: "shizuka datta", meaning: "tenang (lampau -na)" },
        { kana: "ãããã ã£ã", romaji: "kirei datta", meaning: "cantik (lampau -na)" },
        { kana: "ãããã ã£ã", romaji: "genki datta", meaning: "sehat (lampau -na)" },
      ],
      note: "Sifat -i lampau: ganti ãâãã£ã (ãããâãããã£ã). Sifat -na lampau: ãã ã£ã.",
    },
    enemies: [
      { id: "fashion-critic", name: "Kritikus Mode", sprite: "ð", hp: 20, attack: 6, color: "#e91e63", abilities: ["crit", "shield"] },
    ],
    questions: [
      { type: "typing", prompt: "Lampau dari ããã (mahal):", kana: "ãããã£ã", answer: ["takakatta"] },
      { type: "typing", prompt: "Lampau dari ãã®ãã (seru):", kana: "ãã®ããã£ã", answer: ["tanoshikatta"] },
      { type: "typing", prompt: "Lampau dari ããã (cantik, -na):", kana: "ãããã ã£ã", answer: ["kirei datta"] },
      { type: "choice", prompt: "Lampau dari sifat -i, polanya?", options: ["ããã£ã", "ãã ã£ã", "ãã", "ãã"], answer: 0 },
      { type: "choice", prompt: "Lampau dari sifat -na, polanya?", options: ["ããã£ã", "ãã ã£ã", "ãã", "ãã¦"], answer: 1 },
      { type: "typing", prompt: "Lampau dari ããã (sehat, -na):", kana: "ãããã ã£ã", answer: ["genki datta"] },
    ],
    reward: { xp: 140 },
  },

  // ===== STAGE 9: Want to / want to do =====
  {
    id: "n4-9",
    worldId: "n4",
    index: 9,
    chapter: 1,
    title: "Keinginan ãã",
    subtitle: "ããã (ingin)",
    type: "battle",
    intro: [
      "**Kafe Pelabuhan**",
      "Anak kecil: ãã¢ã¤ã¹ã¯ãªã¼ã ã ãã¹ãã! Ingin makan es krim!Â»",
      "ãBentuk ããã = ingin. Pelajari!Â»",
    ],
    outro: ["Anak kecil tersenyum: Â«Paham keinginan sekarang!Â»", "**Stage 9 selesai! +150 XP**"],
    lesson: {
      title: "ããã (Ingin)",
      rows: [
        { kana: "ãã¹ãã", romaji: "tabetai", meaning: "ingin makan" },
        { kana: "ã®ã¿ãã", romaji: "nomitai", meaning: "ingin minum" },
        { kana: "ãããã", romaji: "ikitai", meaning: "ingin pergi" },
        { kana: "ã¿ãã", romaji: "mitai", meaning: "ingin lihat" },
        { kana: "ãããã®ã ããã", romaji: "kaimono o shitai", meaning: "ingin belanja" },
      ],
      note: "ããã = ingin. Pola: stem + ãã. Bisa konjugasi: ããã£ã (lampau), ãããªã (negatif).",
    },
    enemies: [
      { id: "wish-thief", name: "Pencuri Keinginan", sprite: "ð­", hp: 22, attack: 6, color: "#9c27b0", abilities: ["poison", "multi-attack"] },
    ],
    questions: [
      { type: "typing", prompt: "ãingin makanã:", kana: "ãã¹ãã", answer: ["tabetai"] },
      { type: "typing", prompt: "ãingin minumã:", kana: "ã®ã¿ãã", answer: ["nomitai"] },
      { type: "typing", prompt: "ãingin pergiã:", kana: "ãããã", answer: ["ikitai"] },
      { type: "choice", prompt: "ãã¿ããã artinya?", kana: "ã¿ãã", options: ["Ingin lihat", "Ingin makan", "Ingin pergi", "Ingin minum"], answer: 0 },
      { type: "typing", prompt: "Romaji 'ingin belanja':", kana: "ãããã®ã ããã", answer: ["kaimono o shitai"] },
    ],
    reward: { xp: 150 },
  },

  // ===== STAGE 10: Boss Chapter 1 =====
  {
    id: "n4-10",
    worldId: "n4",
    index: 10,
    chapter: 1,
    title: "Captain Maru",
    subtitle: "Bos Akhir Bab 1 N4",
    type: "boss",
    intro: [
      "**Kapal Besar di Dermaga**",
      "Di kapal terbesar, **Captain Maru** menunggu. ãPengelana, kalahkan aku untuk dapat tiket ke pulau utama!Â»",
      "ãUjian akhir Bab 1: gabungan verb forms, particles, sifat, keinginan!Â»",
      "**PERTARUNGAN AKHIR BAB 1 N4**",
    ],
    outro: [
      "Captain Maru tertawa: Â«Kau hebat! Tiket ke pulau utama adalah milikmu!Â»",
      "**BAB 1 N4 SELESAI! +500 XP, Badge: Pengelana Pelabuhan, Item: Tiket Pulau**",
    ],
    lesson: undefined,
    enemies: [
      { id: "captain-maru", name: "Captain Maru", sprite: "ð§âð¦²", hp: 108, attack: 8, color: "#ff9800", abilities: ["enrage", "heal", "crit", "shield", "multi-attack", "counter"] },
    ],
    questions: [
      { type: "typing", prompt: "te-form dari ãã¹ã:", kana: "ãã¹ã¦", answer: ["tabete"] },
      { type: "typing", prompt: "nai-form dari ã®ã:", kana: "ã®ã¾ãªã", answer: ["nomanai"] },
      { type: "typing", prompt: "ta-form dari ãã:", kana: "ãã£ã", answer: ["itta"] },
      { type: "choice", prompt: "ãã¿ã___ããã partikel?", kana: "ã¿ãã§ ãã", options: ["ã«", "ã§", "ã¸", "ã"], answer: 1 },
      { type: "typing", prompt: "Lampau dari ãã®ãã (seru):", kana: "ãã®ããã£ã", answer: ["tanoshikatta"] },
      { type: "typing", prompt: "ãingin pergiã:", kana: "ãããã", answer: ["ikitai"] },
      { type: "typing", prompt: "te-form + kudasai dari ã¾ã¤ (tunggu):", kana: "ã¾ã£ã¦ ãã ãã", answer: ["matte kudasai"] },
      { type: "choice", prompt: "ããããã£ãã artinya?", kana: "ãããã£ã", options: ["Mahal (lampau)", "Mahal (sekarang)", "Murah (lampau)", "Tinggi (sekarang)"], answer: 0 },
      { type: "typing", prompt: "nai-form dari ãã:", kana: "ããªã", answer: ["shinai"] },
      { type: "choice", prompt: "ãããã£ãããã¾ãã dipakai di?", kana: "ããã£ãããã¾ã", options: ["Toko", "Rumah", "Sekolah", "Kuil"], answer: 0 },
    ],
    reward: { xp: 500, badge: "Pengelana Pelabuhan", item: "Tiket Pulau" },
  },

  // ===== STAGE 11: Kanji angka lanjut (100, 1000) =====
  {
    id: "n4-11",
    worldId: "n4",
    index: 11,
    chapter: 2,
    title: "Pulau Utama - Kanji Angka Besar",
    subtitle: "ç¾ å ä¸",
    type: "lesson",
    intro: [
      "**Pulau Utama - Pasar Besar**",
      "Setelah sampai pulau utama, kau lihat pedagang pakai angka besar: ãç¾å! åå! ä¸å!Â»",
      "ãKanji angka besar: ç¾ (100), å (1000), ä¸ (10000). Pelajari!Â»",
    ],
    outro: ["Pedagang: Â«Sekarang kau bisa baca harga!Â»", "**Stage 11 selesai! +160 XP**"],
    lesson: {
      title: "Kanji Angka Besar",
      rows: [
        { kana: "ç¾", romaji: "hyaku", meaning: "100 (seratus)" },
        { kana: "å", romaji: "sen", meaning: "1000 (seribu)" },
        { kana: "ä¸", romaji: "man", meaning: "10000 (sepuluh ribu)" },
        { kana: "ç¾ä¸", romaji: "hyakuman", meaning: "1,000,000 (satu juta)" },
        { kana: "ä¸ç¾", romaji: "sanbyaku", meaning: "300 (perhatikan: byaku)" },
        { kana: "å­ç¾", romaji: "roppyaku", meaning: "600 (perhatikan: ppyaku)" },
        { kana: "å«ç¾", romaji: "happyaku", meaning: "800 (perhatikan: ppyaku)" },
        { kana: "ä¸å", romaji: "sanzen", meaning: "3000 (perhatikan: zen)" },
      ],
      note: "ç¾ dibaca hyaku, tapi 300=sanbyaku, 600=roppyaku, 800=happyaku. å dibaca sen, tapi 3000=sanzen.",
    },
    enemies: [
      { id: "price-math", name: "Matematika Harga", sprite: "ð¢", hp: 24, attack: 7, color: "#ff9800", abilities: ["time-pressure"] },
    ],
    questions: [
      { type: "choice", prompt: "Kanji 'ç¾' berarti?", kana: "ç¾", options: ["10", "100", "1000", "10000"], answer: 1 },
      { type: "choice", prompt: "Kanji 'å' berarti?", kana: "å", options: ["100", "1000", "10000", "100000"], answer: 1 },
      { type: "choice", prompt: "Kanji 'ä¸' berarti?", kana: "ä¸", options: ["1000", "10000", "100000", "1000000"], answer: 1 },
      { type: "typing", prompt: "Romaji 'ä¸ç¾' (hati-hati!):", kana: "ä¸ç¾", answer: ["sanbyaku"] },
      { type: "typing", prompt: "Romaji 'å­ç¾':", kana: "å­ç¾", answer: ["roppyaku"] },
      { type: "typing", prompt: "Romaji 'ä¸å':", kana: "ä¸å", answer: ["sanzen"] },
    ],
    reward: { xp: 160 },
  },

  // ===== STAGE 12: Kanji waktu/tanggal =====
  {
    id: "n4-12",
    worldId: "n4",
    index: 12,
    chapter: 2,
    title: "Kanji Waktu & Tanggal",
    subtitle: "å¹´ æ æ¥ æ å",
    type: "battle",
    intro: [
      "**Menara Jam Pulau**",
      "Penjaga jam: ãä½æã§ãã? Pukul berapa?Â»",
      "ãKanji waktu: å¹´ (tahun), æ (bulan), æ¥ (hari), æ (jam), å (menit).Â»",
    ],
    outro: ["Penjaga: Â«Sekarang bisa baca tanggal & jam!Â»", "**Stage 12 selesai! +170 XP**"],
    lesson: {
      title: "Kanji Waktu",
      rows: [
        { kana: "å¹´", romaji: "nen/toshi", meaning: "tahun" },
        { kana: "æ", romaji: "tsuki/getsu", meaning: "bulan (kalender/moon)" },
        { kana: "æ¥", romaji: "hi/nichi", meaning: "hari (tanggal/sun)" },
        { kana: "æ", romaji: "ji/toki", meaning: "jam / waktu" },
        { kana: "å", romaji: "fun/pun", meaning: "menit / bagian" },
        { kana: "æé", romaji: "jikan", meaning: "durasi waktu (jam)" },
        { kana: "ä»æ", romaji: "kesa", meaning: "tadi pagi" },
        { kana: "ä»æ©", romaji: "konban", meaning: "nanti malam" },
      ],
      note: "æ (ji) untuk jam, å (fun/pun) untuk menit. 3æ = pukul 3, 3æå = pukul 3.30.",
    },
    enemies: [
      { id: "clock-phantom", name: "Hantu Jam", sprite: "ð", hp: 26, attack: 7, color: "#cddc39", abilities: ["time-pressure", "shield"] },
    ],
    questions: [
      { type: "choice", prompt: "Kanji 'å¹´' berarti?", kana: "å¹´", options: ["Hari", "Bulan", "Tahun", "Jam"], answer: 2 },
      { type: "choice", prompt: "Kanji 'æ¥' berarti?", kana: "æ¥", options: ["Hari/tanggal", "Bulan", "Tahun", "Menit"], answer: 0 },
      { type: "choice", prompt: "Kanji 'æ' berarti?", kana: "æ", options: ["Menit", "Jam", "Hari", "Tahun"], answer: 1 },
      { type: "typing", prompt: "Romaji 'durasi waktu':", kana: "æé", answer: ["jikan"] },
      { type: "typing", prompt: "Romaji 'tadi pagi':", kana: "ä»æ", answer: ["kesa"] },
      { type: "choice", prompt: "ãåã dibaca sebagai?", kana: "å", options: ["fun/pun", "ji", "nen", "hi"], answer: 0 },
    ],
    reward: { xp: 170 },
  },

  // ===== STAGE 13: Kanji keluarga =====
  {
    id: "n4-13",
    worldId: "n4",
    index: 13,
    chapter: 2,
    title: "Kanji Keluarga",
    subtitle: "ç¶ æ¯ å å§ å¼ å¦¹",
    type: "lesson",
    intro: [
      "**Rumah Keluarga Pelaut**",
      "Keluarga pelaut menyambut: ãã¡ã¡ã¨ã¯ã¯ã¨ãã«ã¨ãã­ã¨...Â»",
      "ãKanji keluarga: ç¶ (ayah), æ¯ (ibu), å (kakak laki), å§ (kakak perempuan). Pelajari!Â»",
    ],
    outro: ["Keluarga: Â«Sekarang kenal keluarga Jepang!Â»", "**Stage 13 selesai! +180 XP**"],
    lesson: {
      title: "Kanji Keluarga",
      rows: [
        { kana: "ç¶", romaji: "chichi/otousan", meaning: "ayah" },
        { kana: "æ¯", romaji: "haha/okaasan", meaning: "ibu" },
        { kana: "å", romaji: "ani/oniisan", meaning: "kakak laki-laki" },
        { kana: "å§", romaji: "ane/oneesan", meaning: "kakak perempuan" },
        { kana: "å¼", romaji: "otouto", meaning: "adik laki-laki" },
        { kana: "å¦¹", romaji: "imouto", meaning: "adik perempuan" },
        { kana: "ç¥ç¶", romaji: "sofu", meaning: "kakek" },
        { kana: "ç¥æ¯", romaji: "sobo", meaning: "nenek" },
      ],
      note: "Versi sendiri: chichi/haha (ayah/ibu). Versi orang lain: otousan/okaasan. å=ani, å§=ane.",
    },
    enemies: [
      { id: "family-tree", name: "Pohon Keluarga", sprite: "ð³", hp: 28, attack: 7, color: "#4caf50", abilities: ["regen", "shield"] },
    ],
    questions: [
      { type: "choice", prompt: "Kanji 'ç¶' berarti?", kana: "ç¶", options: ["Ibu", "Ayah", "Kakak", "Adik"], answer: 1 },
      { type: "choice", prompt: "Kanji 'æ¯' berarti?", kana: "æ¯", options: ["Ibu", "Ayah", "Nenek", "Tante"], answer: 0 },
      { type: "choice", prompt: "Kanji 'å' berarti?", kana: "å", options: ["Adik laki", "Kakak laki", "Adik perempuan", "Kakak perempuan"], answer: 1 },
      { type: "choice", prompt: "Kanji 'å§' berarti?", kana: "å§", options: ["Adik laki", "Kakak laki", "Adik perempuan", "Kakak perempuan"], answer: 3 },
      { type: "typing", prompt: "Romaji 'adik perempuan':", kana: "å¦¹", answer: ["imouto"] },
      { type: "typing", prompt: "Romaji 'kakek':", kana: "ç¥ç¶", answer: ["sofu"] },
    ],
    reward: { xp: 180 },
  },

  // ===== STAGE 14: Kanji alam =====
  {
    id: "n4-14",
    worldId: "n4",
    index: 14,
    chapter: 2,
    title: "Kanji Alam",
    subtitle: "å±± å· æµ· ç©º é¨",
    type: "battle",
    intro: [
      "**Bukit Pulau**",
      "Pemandu: ããã¾ã¨ãã¿ã¨ãã! Gunung, laut, langit!Â»",
      "ãKanji alam: å±± (gunung), å· (sungai), æµ· (laut), ç©º (langit), é¨ (hujan).Â»",
    ],
    outro: ["Pemandu: Â«Pemandangan pulau kini bisa deskripsikan!Â»", "**Stage 14 selesai! +190 XP**"],
    lesson: {
      title: "Kanji Alam",
      rows: [
        { kana: "å±±", romaji: "yama", meaning: "gunung" },
        { kana: "å·", romaji: "kawa", meaning: "sungai" },
        { kana: "æµ·", romaji: "umi", meaning: "laut" },
        { kana: "ç©º", romaji: "sora", meaning: "langit" },
        { kana: "é¨", romaji: "ame", meaning: "hujan" },
        { kana: "é¢¨", romaji: "kaze", meaning: "angin" },
        { kana: "éª", romaji: "yuki", meaning: "salju" },
        { kana: "æ£®", romaji: "mori", meaning: "hutan" },
      ],
      note: "å±± (gunung), å· (sungai - 3 garis air), æµ· (laut - air + setiap), æ£® (hutan - 3 pohon).",
    },
    enemies: [
      { id: "storm-spirit", name: "Roh Badai", sprite: "â", hp: 30, attack: 8, color: "#2196f3", abilities: ["crit", "multi-attack"] },
    ],
    questions: [
      { type: "choice", prompt: "Kanji 'å±±' berarti?", kana: "å±±", options: ["Sungai", "Gunung", "Laut", "Hutan"], answer: 1 },
      { type: "choice", prompt: "Kanji 'æµ·' berarti?", kana: "æµ·", options: ["Sungai", "Danau", "Laut", "Hujan"], answer: 2 },
      { type: "typing", prompt: "Romaji 'langit':", kana: "ç©º", answer: ["sora"] },
      { type: "typing", prompt: "Romaji 'hujan':", kana: "é¨", answer: ["ame"] },
      { type: "typing", prompt: "Romaji 'hutan':", kana: "æ£®", answer: ["mori"] },
      { type: "choice", prompt: "Kanji 'é¢¨' berarti?", kana: "é¢¨", options: ["Hujan", "Angin", "Salju", "Petir"], answer: 1 },
    ],
    reward: { xp: 190 },
  },

  // ===== STAGE 15: Kanji tubuh =====
  {
    id: "n4-15",
    worldId: "n4",
    index: 15,
    chapter: 2,
    title: "Kanji Tubuh",
    subtitle: "ç® å£ æ è¶³ å¿",
    type: "battle",
    intro: [
      "**Klinik Pulau**",
      "Dokter: ããã¨ãã¡ã¨ã¦! Mata, mulut, tangan!Â»",
      "ãKanji tubuh: ç® (mata), å£ (mulut), æ (tangan), è¶³ (kaki), å¿ (hati).Â»",
    ],
    outro: ["Dokter: Â«Sekarang bisa periksa bagian tubuh!Â»", "**Stage 15 selesai! +200 XP**"],
    lesson: {
      title: "Kanji Tubuh",
      rows: [
        { kana: "ç®", romaji: "me", meaning: "mata" },
        { kana: "å£", romaji: "kuchi", meaning: "mulut" },
        { kana: "æ", romaji: "te", meaning: "tangan" },
        { kana: "è¶³", romaji: "ashi", meaning: "kaki / cukup" },
        { kana: "å¿", romaji: "kokoro", meaning: "hati (jiwa)" },
        { kana: "è³", romaji: "mimi", meaning: "telinga" },
        { kana: "é¼»", romaji: "hana", meaning: "hidung" },
        { kana: "é ­", romaji: "atama", meaning: "kepala" },
      ],
      note: "ç® (mata - gambar mata), å£ (mulut - gambar mulut), æ (tangan), è¶³ (kaki).",
    },
    enemies: [
      { id: "body-mage", name: "Penyihir Tubuh", sprite: "ð§", hp: 32, attack: 8, color: "#7e57c2", abilities: ["poison", "regen"] },
    ],
    questions: [
      { type: "choice", prompt: "Kanji 'ç®' berarti?", kana: "ç®", options: ["Mulut", "Mata", "Telinga", "Hidung"], answer: 1 },
      { type: "choice", prompt: "Kanji 'æ' berarti?", kana: "æ", options: ["Kaki", "Tangan", "Kepala", "Hati"], answer: 1 },
      { type: "typing", prompt: "Romaji 'mulut':", kana: "å£", answer: ["kuchi"] },
      { type: "typing", prompt: "Romaji 'kaki':", kana: "è¶³", answer: ["ashi"] },
      { type: "typing", prompt: "Romaji 'hati (jiwa)':", kana: "å¿", answer: ["kokoro"] },
      { type: "choice", prompt: "Kanji 'é ­' berarti?", kana: "é ­", options: ["Wajah", "Kepala", "Rambut", "Leher"], answer: 1 },
    ],
    reward: { xp: 200 },
  },

  // ===== STAGE 16: Conditional ãã =====
  {
    id: "n4-16",
    worldId: "n4",
    index: 16,
    chapter: 2,
    title: "Kondisional ãã",
    subtitle: "ããã (jika)",
    type: "lesson",
    intro: [
      "**Tavern Pulau**",
      "Pemilik tavern: ãããã ãµã£ããã ãããªã! Kalau hujan, tidak pergi!Â»",
      "ãBentuk ããã = jika. Pelajari!Â»",
    ],
    outro: ["Pemilik: Â«Sekarang bisa kalimat bersyarat!Â»", "**Stage 16 selesai! +210 XP**"],
    lesson: {
      title: "ããã (Jika)",
      rows: [
        { kana: "ãã£ãã", romaji: "ittara", meaning: "jika pergi" },
        { kana: "ãã¹ãã", romaji: "tabetara", meaning: "jika makan" },
        { kana: "ããã ãµã£ãã", romaji: "ame ga futtara", meaning: "jika hujan turun" },
        { kana: "ããã¿ã ã£ãã", romaji: "yasumi dattara", meaning: "jika libur" },
      ],
      note: "ããã = jika. Pola: ta-form + ra. tabeta + ra = tabetara. Bisa juga sifat: ãããã£ãã.",
    },
    enemies: [
      { id: "if-demon", name: "Setan Jika", sprite: "ð", hp: 34, attack: 9, color: "#e91e63", abilities: ["crit", "enrage"] },
    ],
    questions: [
      { type: "typing", prompt: "ãjika makanã (ããã dari ãã¹ã):", kana: "ãã¹ãã", answer: ["tabetara"] },
      { type: "typing", prompt: "ãjika pergiã:", kana: "ãã£ãã", answer: ["ittara"] },
      { type: "typing", prompt: "Romaji 'jika hujan turun':", kana: "ããã ãµã£ãã", answer: ["ame ga futtara"] },
      { type: "choice", prompt: "ããããã artinya?", options: ["Karena", "Jika", "Tetapi", "Sehingga"], answer: 1 },
      { type: "choice", prompt: "Pola ããã dibuat dari?", options: ["te-form + ra", "ta-form + ra", "nai-form + ra", "masu + ra"], answer: 1 },
    ],
    reward: { xp: 210 },
  },

  // ===== STAGE 17: Reason ãã / ã§ã =====
  {
    id: "n4-17",
    worldId: "n4",
    index: 17,
    chapter: 2,
    title: "Sebab & Lawan",
    subtitle: "ããã (karena) / ãã§ã (tetapi)",
    type: "battle",
    intro: [
      "**Balai Kota Pulau**",
      "Petugas: ãããã ããã ããã¾ãããã§ãã ããã ããã¾ã!Â»",
      "ããã = karena, ã§ã = tetapi. Pelajari!Â»",
    ],
    outro: ["Petugas: Â«Sekarang bisa kasih alasan & bantah!Â»", "**Stage 17 selesai! +220 XP**"],
    lesson: {
      title: "ããã»ã§ã",
      rows: [
        { kana: "ããã ãã", romaji: "ame da kara", meaning: "karena hujan" },
        { kana: "ããããã", romaji: "takai kara", meaning: "karena mahal" },
        { kana: "ã§ã", romaji: "demo", meaning: "tetapi / namun" },
        { kana: "ã¤ããããã§ãã ãã", romaji: "tsukareta. demo, iku", meaning: "Lelah. Tapi, pergi." },
      ],
      note: "ãã = karena (sebab). ã§ã = tetapi (lawan). Beda ã§ã dengan ããã¦ (dan/lalu).",
    },
    enemies: [
      { id: "logic-guard", name: "Penjaga Logika", sprite: "ð¤", hp: 36, attack: 9, color: "#607d8b", abilities: ["counter", "shield"] },
    ],
    questions: [
      { type: "choice", prompt: "ãããã artinya?", options: ["Karena", "Tetapi", "Dan", "Atau"], answer: 0 },
      { type: "choice", prompt: "ãã§ãã artinya?", options: ["Karena", "Tetapi", "Jika", "Sehingga"], answer: 1 },
      { type: "typing", prompt: "Romaji 'karena hujan':", kana: "ããã ãã", answer: ["ame da kara"] },
      { type: "choice", prompt: "ããããããã artinya?", kana: "ããããã", options: ["Karena mahal", "Tapi mahal", "Jika mahal", "Mahal dan"], answer: 0 },
      { type: "typing", prompt: "Romaji 'tetapi':", kana: "ã§ã", answer: ["demo"] },
    ],
    reward: { xp: 220 },
  },

  // ===== STAGE 18: Giving & receiving =====
  {
    id: "n4-18",
    worldId: "n4",
    index: 18,
    chapter: 2,
    title: "Memberi & Menerima",
    subtitle: "ããã / ããã / ããã",
    type: "lesson",
    intro: [
      "**Toko Hadiah**",
      "Penjaga toko: ãããã ããªãã« ããã¾ã! Ini saya berikan padamu!Â»",
      "ãããã (beri), ããã (terima), ããã (beri ke saya). Pelajari!Â»",
    ],
    outro: ["Penjaga: Â«Sekarang bisa transaksi hadiah!Â»", "**Stage 18 selesai! +230 XP**"],
    lesson: {
      title: "ãããã»ãããã»ããã",
      rows: [
        { kana: "ããã", romaji: "ageru", meaning: "memberi (ke orang lain)" },
        { kana: "ããã", romaji: "morau", meaning: "menerima (dari orang lain)" },
        { kana: "ããã", romaji: "kureru", meaning: "memberi (ke saya)" },
        { kana: "ã»ãã ããã", romaji: "hon o ageru", meaning: "memberi buku" },
        { kana: "ã»ãã ããã", romaji: "hon o morau", meaning: "menerima buku" },
      ],
      note: "ããã = saya beri ke orang lain. ããã = saya terima dari orang. ããã = orang lain beri ke saya.",
    },
    enemies: [
      { id: "gift-bandit", name: "Perampok Hadiah", sprite: "ð¥·", hp: 38, attack: 10, color: "#9c27b0", abilities: ["multi-attack", "poison"] },
    ],
    questions: [
      { type: "choice", prompt: "ããããã artinya?", kana: "ããã", options: ["Menerima", "Memberi (ke orang)", "Meminta", "Meminjam"], answer: 1 },
      { type: "choice", prompt: "ããããã artinya?", kana: "ããã", options: ["Memberi", "Menerima (dari orang)", "Membeli", "Menjual"], answer: 1 },
      { type: "choice", prompt: "ããããã dipakai kalau?", kana: "ããã", options: ["Saya beri ke orang", "Orang beri ke saya", "Saya terima", "Orang terima"], answer: 1 },
      { type: "typing", prompt: "Romaji 'memberi buku':", kana: "ã»ãã ããã", answer: ["hon o ageru"] },
      { type: "typing", prompt: "Romaji 'menerima buku':", kana: "ã»ãã ããã", answer: ["hon o morau"] },
    ],
    reward: { xp: 230 },
  },

  // ===== STAGE 19: Passive form =====
  {
    id: "n4-19",
    worldId: "n4",
    index: 19,
    chapter: 2,
    title: "Bentuk Pasif",
    subtitle: "ãããã / ããã (pasif)",
    type: "battle",
    intro: [
      "**Pengadilan Pulau**",
      "Hakim: ãã¬ãã¾ãã! Dicuri!Â»",
      "ãPasif: ãããã (grup 1), ããã (grup 2). Pelajari!Â»",
    ],
    outro: ["Hakim: Â«Sekarang bisa lapor pasif!Â»", "**Stage 19 selesai! +240 XP**"],
    lesson: {
      title: "Pasif",
      rows: [
        { kana: "ãã¹ããã", romaji: "taberareru", meaning: "dimakan (pasif)" },
        { kana: "ã¬ãã¾ãã", romaji: "nusumareru", meaning: "dicuri (pasif)" },
        { kana: "ã¿ããã", romaji: "mirareru", meaning: "dilihat (pasif)" },
        { kana: "ããã", romaji: "sareru", meaning: "dilakukan (pasif)" },
      ],
      note: "Pasif: subjek dikenai aksi. ãã¹ã â ãã¹ããã (dimakan). Pola grup 1: ããã, grup 2: ãããã.",
    },
    enemies: [
      { id: "passive-shadow", name: "Bayangan Pasif", sprite: "ð¤", hp: 40, attack: 10, color: "#37474f", abilities: ["shield", "counter", "enrage"] },
    ],
    questions: [
      { type: "typing", prompt: "Pasif dari ãã¹ã (makan):", kana: "ãã¹ããã", answer: ["taberareru"] },
      { type: "typing", prompt: "Pasif dari ãã (lakukan):", kana: "ããã", answer: ["sareru"] },
      { type: "typing", prompt: "Romaji 'dicuri':", kana: "ã¬ãã¾ãã", answer: ["nusumareru"] },
      { type: "choice", prompt: "ããã¹ãããã artinya?", kana: "ãã¹ããã", options: ["Makan", "Dimakan", "Ingin makan", "Mohon makan"], answer: 1 },
      { type: "choice", prompt: "Bentuk pasif menunjukkan?", options: ["Subjek melakukan aksi", "Subjek dikenai aksi", "Subjek ingin aksi", "Subjek minta aksi"], answer: 1 },
    ],
    reward: { xp: 240 },
  },

  // ===== STAGE 20: Boss Chapter 2 N4 =====
  {
    id: "n4-20",
    worldId: "n4",
    index: 20,
    chapter: 2,
    title: "Lord Kaizoku",
    subtitle: "Bos Akhir Bab 2 N4 - Raja Bajak Laut",
    type: "boss",
    intro: [
      "**Kapal Bajak Laut Besar**",
      "Di geladak kapal bajak laut, **Lord Kaizoku** menunggu. ãPengelana, kalahkan aku untuk kuasai seluruh N4!Â»",
      "ãUjian akhir: gabungan semua N4 - verb forms, kanji, grammar, pasif, kondisional!Â»",
      "**PERTARUNGAN AKHIR BAB 2 N4**",
    ],
    outro: [
      "Lord Kaizoku tertawa: Â«Kau benar-benar pahlawan! N4 adalah milikmu!Â»",
      "Ia menyerahkan mahkota emas. «Lanjut ke Bab 3: Ujian Akademi Pelabuhan!»",
      "**BAB 2 N4 SELESAI! +800 XP, 300 koin, Badge: Penguasa Pelabuhan, Item: Mahkota Bajak Laut**",
      "**Bab 3 terbuka: Ujian Adaptif (Stage 21-30)**",
    ],
    lesson: undefined,
    enemies: [
      { id: "lord-kaizoku", name: "Lord Kaizoku", sprite: "ð´ââ ï¸", hp: 200, attack: 12, color: "#1a1a2e", abilities: ["enrage", "heal", "crit", "shield", "multi-attack", "counter", "poison"] },
    ],
    questions: [
      { type: "typing", prompt: "te-form dari ãã¹ã:", kana: "ãã¹ã¦", answer: ["tabete"] },
      { type: "typing", prompt: "nai-form dari ã®ã:", kana: "ã®ã¾ãªã", answer: ["nomanai"] },
      { type: "typing", prompt: "ta-form dari ãã:", kana: "ãã£ã", answer: ["itta"] },
      { type: "choice", prompt: "Kanji 'ç¾' berarti?", kana: "ç¾", options: ["10", "100", "1000", "10000"], answer: 1 },
      { type: "choice", prompt: "Kanji 'æµ·' berarti?", kana: "æµ·", options: ["Sungai", "Danau", "Laut", "Hujan"], answer: 2 },
      { type: "typing", prompt: "Romaji 'karena hujan':", kana: "ããã ãã", answer: ["ame da kara"] },
      { type: "typing", prompt: "ãingin pergiã:", kana: "ãããã", answer: ["ikitai"] },
      { type: "choice", prompt: "ããããã dipakai kalau?", kana: "ããã", options: ["Saya beri", "Orang beri ke saya", "Saya terima", "Orang terima"], answer: 1 },
      { type: "typing", prompt: "Pasif dari ãã¹ã:", kana: "ãã¹ããã", answer: ["taberareru"] },
      { type: "typing", prompt: "Romaji 'tetapi':", kana: "ã§ã", answer: ["demo"] },
      { type: "choice", prompt: "ããããã artinya?", options: ["Karena", "Jika", "Tetapi", "Sehingga"], answer: 1 },
      { type: "typing", prompt: "Romaji 'adik perempuan':", kana: "å¦¹", answer: ["imouto"] },
    ],
    reward: { xp: 800, badge: "Penguasa Pelabuhan", item: "Mahkota Bajak Laut" },
  },

  // ===== BAB 3: UJIAN ADAPTIF (Stage 21-30) =====

  {
    id: "n4-21", worldId: "n4", index: 21, chapter: 3,
    title: "Akademi Pelabuhan", subtitle: "Transisi: opsi pakai kana",
    type: "lesson",
    intro: ["**Akademi Pelabuhan Minato**", "Penguji: «Selamat datang di ujian akademi. Opsi jawaban mulai pakai huruf Jepang penuh!»"],
    outro: ["Penguji: «Kau mulai terbiasa!»", "**Stage 21 selesai! +150 XP**"],
    lesson: { title: "Transisi ke Kana", rows: [
      { kana: "たべる", romaji: "taberu", meaning: "makan (kasual)" },
      { kana: "のむ", romaji: "nomu", meaning: "minum (kasual)" },
      { kana: "いく", romaji: "iku", meaning: "pergi (kasual)" },
      { kana: "みる", romaji: "miru", meaning: "lihat (kasual)" },
      { kana: "する", romaji: "suru", meaning: "lakukan (kasual)" },
    ], note: "Bentuk kasual (dictionary form) vs bentuk sopan (〜ます). taberu (kasual) = tabemasu (sopan)." },
    enemies: [{ id: "n4-exam-1", name: "Pengawas Ujian", sprite: "📋", hp: 50, attack: 10, color: "#607d8b", abilities: ["time-pressure", "shield"] }],
    questions: [
      { type: "choice", prompt: "「たべる」の いみは?", kana: "たべる", options: ["makan", "minum", "pergi", "lihat"], answer: 0 },
      { type: "choice", prompt: "Bentuk sopan dari たべる:", kana: "たべる", options: ["たべます", "たべて", "たべない", "たべた"], answer: 0 },
      { type: "choice", prompt: "Bentuk te-form dari のむ:", kana: "のむ", options: ["のんで", "のまない", "のんだ", "のみます"], answer: 0 },
      { type: "typing", prompt: "ロマジで: たべる (makan kasual)", kana: "たべる", answer: ["taberu"] },
      { type: "choice", prompt: "「する」の いみは?", kana: "する", options: ["lakukan", "makan", "minum", "pergi"], answer: 0 },
      { type: "typing", prompt: "te-form + kudasai dari みる:", kana: "みて ください", answer: ["mite kudasai"] },
    ],
    reward: { xp: 150 },
  },

  {
    id: "n4-22", worldId: "n4", index: 22, chapter: 3,
    title: "Full Kana - Verba", subtitle: "Opsi full kana, tanpa romaji",
    type: "battle",
    intro: ["**Ruang Ujian 1**", "Penguji: «Sekarang semua opsi pakai ひらがな. Tidak ada romaji!»"],
    outro: ["Penguji: «Kau bisa baca kana!»", "**Stage 22 selesai! +170 XP**"],
    lesson: { title: "Verba Sehari-hari (Kana)", rows: [
      { kana: "おきる", romaji: "okiru", meaning: "bangun (tidur)" },
      { kana: "ねる", romaji: "neru", meaning: "tidur" },
      { kana: "かう", romaji: "kau", meaning: "membeli" },
      { kana: "うる", romaji: "uru", meaning: "menjual" },
      { kana: "まつ", romaji: "matsu", meaning: "menunggu" },
      { kana: "かえる", romaji: "kaeru", meaning: "pulang" },
    ], note: "Verba sehari-hari dalam bentuk kasual. おきる (bangun), ねる (tidur), かえる (pulang)." },
    enemies: [{ id: "n4-exam-2", name: "Pembaca Verba", sprite: "📖", hp: 55, attack: 11, color: "#3f51b5", abilities: ["crit", "shield"] }],
    questions: [
      { type: "choice", prompt: "「ねる」の いみは?", kana: "ねる", options: ["ねる", "おきる", "かえる", "まつ"], answer: 0, hint: "malam" },
      { type: "choice", prompt: "「menunggu」は にほんごで?", options: ["まつ", "かう", "うる", "ねる"], answer: 0 },
      { type: "choice", prompt: "「かえる」の いみは?", kana: "かえる", options: ["pulang", "bangun", "beli", "jual"], answer: 0 },
      { type: "typing", prompt: "ロマジで: おきる (bangun)", kana: "おきる", answer: ["okiru"] },
      { type: "choice", prompt: "te-form dari かえる:", kana: "かえる", options: ["かえって", "かえらない", "かえった", "かえります"], answer: 0 },
      { type: "typing", prompt: "nai-form dari うる (jual):", kana: "うらない", answer: ["uranai"] },
    ],
    reward: { xp: 170 },
  },

  {
    id: "n4-23", worldId: "n4", index: 23, chapter: 3,
    title: "Kanji Verba", subtitle: "Kanji di soal verba",
    type: "battle",
    intro: ["**Ruang Ujian 2**", "Penguji: «Kanji verba sekarang! 食, 飲, 行, 来, 見!»"],
    outro: ["Penguji: «Kanji verba terkuasai!»", "**Stage 23 selesai! +190 XP**"],
    lesson: { title: "Kanji Verba", rows: [
      { kana: "食べる", romaji: "taberu", meaning: "makan" },
      { kana: "飲む", romaji: "nomu", meaning: "minum" },
      { kana: "行く", romaji: "iku", meaning: "pergi" },
      { kana: "来る", romaji: "kuru", meaning: "datang" },
      { kana: "見る", romaji: "miru", meaning: "lihat" },
      { kana: "書く", romaji: "kaku", meaning: "tulis" },
      { kana: "読む", romaji: "yomu", meaning: "baca" },
      { kana: "話す", romaji: "hanasu", meaning: "bicara" },
    ], note: "Kanji verba penting: 食(makan), 飲(minum), 行(pergi), 来(datang), 見(lihat), 書(tulis), 読(baca), 話(bicara)." },
    enemies: [{ id: "n4-exam-3", name: "Penguji Kanji Verba", sprite: "🔤", hp: 60, attack: 12, color: "#e91e63", abilities: ["enrage", "crit"] }],
    questions: [
      { type: "choice", prompt: "「食べる」の いみは?", kana: "食べる", options: ["makan", "minum", "pergi", "tulis"], answer: 0 },
      { type: "choice", prompt: "「飲む」の いみは?", kana: "飲む", options: ["minum", "makan", "baca", "bicara"], answer: 0 },
      { type: "choice", prompt: "「書く」の いみは?", kana: "書く", options: ["tulis", "baca", "lihat", "bicara"], answer: 0 },
      { type: "typing", prompt: "ロマジで: 読む (baca)", kana: "読む", answer: ["yomu"] },
      { type: "choice", prompt: "「話す」の いみは?", kana: "話す", options: ["bicara", "tulis", "makan", "minum"], answer: 0 },
      { type: "typing", prompt: "te-form dari 食べる:", kana: "食べて", answer: ["tabete"] },
      { type: "typing", prompt: "nai-form dari 飲む:", kana: "飲まない", answer: ["nomanai"] },
    ],
    reward: { xp: 190 },
  },

  {
    id: "n4-24", worldId: "n4", index: 24, chapter: 3,
    title: "Kalimat Kompleks", subtitle: "Kalimat dengan konjugasi",
    type: "battle",
    intro: ["**Ruang Ujian 3**", "Penguji: «Kalimat kompleks dengan konjugasi penuh!»"],
    outro: ["Penguji: «Kalimat kompleks terkuasai!»", "**Stage 24 selesai! +210 XP**"],
    lesson: { title: "Kalimat Konjugasi", rows: [
      { kana: "もう たべました", romaji: "mou tabemashita", meaning: "sudah makan" },
      { kana: "まだ たべていない", romaji: "mada tabete inai", meaning: "belum makan" },
      { kana: "たべたい ですが たべられません", romaji: "tabetai desu ga taberaremasen", meaning: "ingin makan tapi tidak bisa" },
      { kana: "たべたら いいと おもいます", romaji: "tabetara ii to omoimasu", meaning: "sebaiknya makan" },
    ], note: "Konjugasi dalam kalimat: もう〜ました (sudah), まだ〜ていない (belum), 〜たい ですが (ingin tapi), 〜たら いい (sebaiknya)." },
    enemies: [{ id: "n4-exam-4", name: "Roh Kalimat", sprite: "💬", hp: 65, attack: 13, color: "#7e57c2", abilities: ["poison", "multi-attack"] }],
    questions: [
      { type: "choice", prompt: "「もう たべました」の いみは?", kana: "もう たべました", options: ["sudah makan", "belum makan", "ingin makan", "tidak makan"], answer: 0 },
      { type: "choice", prompt: "「まだ たべていない」の いみは?", kana: "まだ たべていない", options: ["belum makan", "sudah makan", "ingin makan", "jangan makan"], answer: 0 },
      { type: "typing", prompt: "ロマジで: もう たべました", kana: "もう たべました", answer: ["mou tabemashita"] },
      { type: "choice", prompt: "「〜たい ですが」の いみは?", options: ["ingin tapi", "sudah dan", "belum atau", "jangan karena"], answer: 0 },
      { type: "choice", prompt: "「たべたら いい」の いみは?", kana: "たべたら いい", options: ["sebaiknya makan", "tidak makan", "sudah makan", "belum makan"], answer: 0 },
    ],
    reward: { xp: 210 },
  },

  {
    id: "n4-25", worldId: "n4", index: 25, chapter: 3,
    title: "Mini-Boss: Laksamana", subtitle: "Mini-Boss: Admiral Kaiyo",
    type: "mini-boss",
    intro: ["**Menara Pengawas Pelabuhan**", "**Admiral Kaiyo**: «Aku penguasa laut. Lemati ujian tengah!»", "«Semua soal pakai huruf Jepang. Tidak ada romaji. Siap?»"],
    outro: ["Admiral Kaiyo: «Kau lulus! Setengah jalan lagi!»", "**Stage 25 selesai! +300 XP, Badge: Lulus Ujian Laut**"],
    lesson: undefined,
    enemies: [{ id: "admiral-kaiyo", name: "Admiral Kaiyo", sprite: "🧑‍✈️", hp: 100, attack: 14, color: "#01579b", abilities: ["enrage", "shield", "counter", "time-pressure", "crit"] }],
    questions: [
      { type: "choice", prompt: "te-form dari 食べる:", kana: "食べて", options: ["食べて", "食べた", "食べない", "食べます"], answer: 0 },
      { type: "choice", prompt: "nai-form dari 飲む:", kana: "飲まない", options: ["飲まない", "飲んで", "飲んだ", "飲みます"], answer: 0 },
      { type: "typing", prompt: "ロマジで: もう たべました (sudah makan)", kana: "もう たべました", answer: ["mou tabemashita"] },
      { type: "choice", prompt: "「書く」の いみは?", kana: "書く", options: ["tulis", "baca", "lihat", "bicara"], answer: 0 },
      { type: "typing", prompt: "te-form + kudasai dari まつ:", kana: "まって ください", answer: ["matte kudasai"] },
      { type: "choice", prompt: "「まだ たべていない」の いみは?", kana: "まだ たべていない", options: ["belum makan", "sudah makan", "ingin makan", "tidak makan"], answer: 0 },
      { type: "choice", prompt: "ta-form dari 行く:", kana: "行った", options: ["行った", "行って", "行かない", "行きます"], answer: 0 },
      { type: "typing", prompt: "ロマジで: 読む (baca)", kana: "読む", answer: ["yomu"] },
    ],
    reward: { xp: 300, badge: "Lulus Ujian Laut" },
  },

  {
    id: "n4-26", worldId: "n4", index: 26, chapter: 3,
    title: "Kosakata Cuaca", subtitle: "Cuaca & musim",
    type: "battle",
    intro: ["**Ruang Ujian 4**", "Penguji: «Tema: cuaca & musim. Full Japanese!»"],
    outro: ["Penguji: «Cuaca terkuasai!»", "**Stage 26 selesai! +230 XP**"],
    lesson: { title: "Kosakata Cuaca", rows: [
      { kana: "はれ", romaji: "hare", meaning: "cerah" },
      { kana: "あめ", romaji: "ame", meaning: "hujan" },
      { kana: "ゆき", romaji: "yuki", meaning: "salju" },
      { kana: "くもり", romaji: "kumori", meaning: "mendung" },
      { kana: "かぜ", romaji: "kaze", meaning: "angin" },
      { kana: "なつ", romaji: "natsu", meaning: "musim panas" },
      { kana: "ふゆ", romaji: "fuyu", meaning: "musim dingin" },
      { kana: "はる", romaji: "haru", meaning: "musim semi" },
      { kana: "あき", romaji: "aki", meaning: "musim gugur" },
    ], note: "Cuaca: はれ(cerah), あめ(hujan), ゆき(salju). Musim: なつ(panas), ふゆ(dingin), はる(semi), あき(gugur)." },
    enemies: [{ id: "n4-exam-5", name: "Roh Cuaca", sprite: "🌤", hp: 70, attack: 14, color: "#4fc3f7", abilities: ["time-pressure", "regen"] }],
    questions: [
      { type: "choice", prompt: "「はれ」の いみは?", kana: "はれ", options: ["cerah", "hujan", "salju", "mendung"], answer: 0 },
      { type: "choice", prompt: "「musim panas」は?", options: ["なつ", "ふゆ", "はる", "あき"], answer: 0 },
      { type: "choice", prompt: "「ゆき」の いみは?", kana: "ゆき", options: ["salju", "hujan", "angin", "cerah"], answer: 0 },
      { type: "typing", prompt: "ロマジで: あめ (hujan)", kana: "あめ", answer: ["ame"] },
      { type: "choice", prompt: "「あき」の いみは?", kana: "あき", options: ["musim gugur", "musim semi", "musim panas", "musim dingin"], answer: 0 },
      { type: "typing", prompt: "ロマジで: かぜ (angin)", kana: "かぜ", answer: ["kaze"] },
    ],
    reward: { xp: 230 },
  },

  {
    id: "n4-27", worldId: "n4", index: 27, chapter: 3,
    title: "Kosakata Pekerjaan", subtitle: "Pekerjaan & profesi",
    type: "battle",
    intro: ["**Ruang Ujian 5**", "Penguji: «Tema: pekerjaan. Banyak kanji!»"],
    outro: ["Penguji: «Pekerjaan terkuasai!»", "**Stage 27 selesai! +250 XP**"],
    lesson: { title: "Kosakata Pekerjaan", rows: [
      { kana: "せんせい", romaji: "sensei", meaning: "guru" },
      { kana: "いしゃ", romaji: "isha", meaning: "dokter" },
      { kana: "かいしゃいん", romaji: "kaishain", meaning: "karyawan" },
      { kana: "けいさつ", romaji: "keisatsu", meaning: "polisi" },
      { kana: "りょうりにん", romaji: "ryourinin", meaning: "koki" },
      { kana: "うんてんしゅ", romaji: "untenshu", meaning: "pengemudi" },
    ], note: "Pekerjaan: せんせい(guru), いしゃ(dokter), けいさつ(polisi), りょうりにん(koki)." },
    enemies: [{ id: "n4-exam-6", name: "Penguji Profesi", sprite: "👔", hp: 75, attack: 15, color: "#607d8b", abilities: ["shield", "counter"] }],
    questions: [
      { type: "choice", prompt: "「いしゃ」の いみは?", kana: "いしゃ", options: ["dokter", "guru", "polisi", "koki"], answer: 0 },
      { type: "choice", prompt: "「polisi」は にほんごで?", options: ["けいさつ", "いしゃ", "せんせい", "かいしゃいん"], answer: 0 },
      { type: "choice", prompt: "「りょうりにん」の いみは?", kana: "りょうりにん", options: ["koki", "pengemudi", "karyawan", "dokter"], answer: 0 },
      { type: "typing", prompt: "ロマジで: せんせい (guru)", kana: "せんせい", answer: ["sensei"] },
      { type: "choice", prompt: "「かいしゃいん」の いみは?", kana: "かいしゃいん", options: ["karyawan", "dokter", "polisi", "koki"], answer: 0 },
      { type: "typing", prompt: "ロマジで: うんてんしゅ (pengemudi)", kana: "うんてんしゅ", answer: ["untenshu"] },
    ],
    reward: { xp: 250 },
  },

  {
    id: "n4-28", worldId: "n4", index: 28, chapter: 3,
    title: "Kosakata Emosi", subtitle: "Perasaan & emosi",
    type: "battle",
    intro: ["**Ruang Ujian 6**", "Penguji: «Tema: emosi. Ekspresikan perasaanmu dalam bahasa Jepang!»"],
    outro: ["Penguji: «Emosi terkuasai!»", "**Stage 28 selesai! +270 XP**"],
    lesson: { title: "Kosakata Emosi", rows: [
      { kana: "うれしい", romaji: "ureshii", meaning: "senang" },
      { kana: "かなしい", romaji: "kanashii", meaning: "sedih" },
      { kana: "おこる", romaji: "okoru", meaning: "marah" },
      { kana: "こわい", romaji: "kowai", meaning: "takut" },
      { kana: "たのしい", romaji: "tanoshii", meaning: "seru/menyenangkan" },
      { kana: "つかれた", romaji: "tsukareta", meaning: "lelah" },
    ], note: "Emosi: うれしい(senang), かなしい(sedih), おこる(marah), こわい(takut), つかれた(lelah)." },
    enemies: [{ id: "n4-exam-7", name: "Roh Emosi", sprite: "😤", hp: 80, attack: 16, color: "#e91e63", abilities: ["poison", "enrage"] }],
    questions: [
      { type: "choice", prompt: "「うれしい」の いみは?", kana: "うれしい", options: ["senang", "sedih", "marah", "takut"], answer: 0 },
      { type: "choice", prompt: "「sedih」は にほんごで?", options: ["かなしい", "うれしい", "こわい", "たのしい"], answer: 0 },
      { type: "choice", prompt: "「おこる」の いみは?", kana: "おこる", options: ["marah", "senang", "lelah", "takut"], answer: 0 },
      { type: "typing", prompt: "ロマジで: つかれた (lelah)", kana: "つかれた", answer: ["tsukareta"] },
      { type: "choice", prompt: "「こわい」の いみは?", kana: "こわい", options: ["takut", "senang", "sedih", "seru"], answer: 0 },
      { type: "typing", prompt: "ロマジで: たのしい (seru)", kana: "たのしい", answer: ["tanoshii"] },
    ],
    reward: { xp: 270 },
  },

  {
    id: "n4-29", worldId: "n4", index: 29, chapter: 3,
    title: "Review Menyeluruh", subtitle: "Review semua N4 - full Japanese",
    type: "battle",
    intro: ["**Ruang Ujian 7 - Pra-Final**", "Penguji: «Review semua! Verba, kanji, kalimat, kosakata. Full Japanese!»"],
    outro: ["Penguji: «Kau siap ujian akhir!»", "**Stage 29 selesai! +300 XP**"],
    lesson: undefined,
    enemies: [{ id: "n4-review", name: "Master Review", sprite: "📚", hp: 90, attack: 17, color: "#7c4dff", abilities: ["enrage", "shield", "counter", "crit"] }],
    questions: [
      { type: "typing", prompt: "te-form dari 食べる:", kana: "食べて", answer: ["tabete"] },
      { type: "typing", prompt: "nai-form dari 飲む:", kana: "飲まない", answer: ["nomanai"] },
      { type: "choice", prompt: "「はれ」の いみは?", kana: "はれ", options: ["cerah", "hujan", "salju", "mendung"], answer: 0 },
      { type: "choice", prompt: "「いしゃ」の いみは?", kana: "いしゃ", options: ["dokter", "guru", "polisi", "koki"], answer: 0 },
      { type: "choice", prompt: "「うれしい」の いみは?", kana: "うれしい", options: ["senang", "sedih", "marah", "takut"], answer: 0 },
      { type: "typing", prompt: "ロマジで: もう たべました (sudah makan)", kana: "もう たべました", answer: ["mou tabemashita"] },
      { type: "choice", prompt: "「書く」の いみは?", kana: "書く", options: ["tulis", "baca", "lihat", "bicara"], answer: 0 },
      { type: "typing", prompt: "ロマジで: なつ (musim panas)", kana: "なつ", answer: ["natsu"] },
    ],
    reward: { xp: 300 },
  },

  {
    id: "n4-30", worldId: "n4", index: 30, chapter: 3,
    title: "Bos Bab 3: Commodore", subtitle: "Mini-Final Bab 3",
    type: "boss",
    intro: ["**Aula Komando Pelabuhan**", "**Commodore Umi**: «Ini ujian akhir Bab 3! Lulus, dan kau masuk Bab 4: Ujian Sertifikasi!»"],
    outro: ["Commodore Umi: «Kau lulus! Bab 4 menunggu!»", "**Bab 3 SELESAI! +500 XP, Badge: Lulus Ujian Pelabuhan**"],
    lesson: undefined,
    enemies: [{ id: "commodore-umi", name: "Commodore Umi", sprite: "🎖️", hp: 130, attack: 18, color: "#01579b", abilities: ["enrage", "heal", "crit", "shield", "multi-attack", "counter"] }],
    questions: [
      { type: "typing", prompt: "te-form dari 食べる:", kana: "食べて", answer: ["tabete"] },
      { type: "typing", prompt: "nai-form のむ:", kana: "飲まない", answer: ["nomanai"] },
      { type: "choice", prompt: "「読む」の いみは?", kana: "読む", options: ["baca", "tulis", "lihat", "bicara"], answer: 0 },
      { type: "choice", prompt: "「かなしい」の いみは?", kana: "かなしい", options: ["sedih", "senang", "marah", "takut"], answer: 0 },
      { type: "typing", prompt: "ロマジで: まだ たべていない", kana: "まだ たべていない", answer: ["mada tabete inai"] },
      { type: "choice", prompt: "「なつ」の いみは?", kana: "なつ", options: ["musim panas", "musim dingin", "musim semi", "musim gugur"], answer: 0 },
      { type: "choice", prompt: "「けいさつ」の いみは?", kana: "けいさつ", options: ["polisi", "dokter", "guru", "koki"], answer: 0 },
      { type: "typing", prompt: "ロマジで: つかれた (lelah)", kana: "つかれた", answer: ["tsukareta"] },
      { type: "choice", prompt: "ta-form dari 行く:", kana: "行った", options: ["行った", "行って", "行かない", "行きます"], answer: 0 },
      { type: "choice", prompt: "「〜たら」の いみは?", options: ["jika", "karena", "tetapi", "sehingga"], answer: 0 },
    ],
    reward: { xp: 500, badge: "Lulus Ujian Pelabuhan" },
  },

  // ===== BAB 4: UJIAN SERTIFIKASI (Stage 31-40) =====

  {
    id: "n4-31", worldId: "n4", index: 31, chapter: 4,
    title: "Sertifikasi Dimulai", subtitle: "Ujian sertifikasi resmi",
    type: "lesson",
    intro: ["**Gedung Sertifikasi Pelabuhan**", "Penguji sertifikasi: «Ini ujian resmi. 10 stage tersisa. Full Japanese, soal campuran!»"],
    outro: ["Penguji: «Dimulai!»", "**Stage 31 selesai! +200 XP**"],
    lesson: { title: "Kosakata Belanja", rows: [
      { kana: "みせ", romaji: "mise", meaning: "toko" },
      { kana: "スーパー", romaji: "suupaa", meaning: "supermarket" },
      { kana: "ねだん", romaji: "nedan", meaning: "harga" },
      { kana: "たかい", romaji: "takai", meaning: "mahal/tinggi" },
      { kana: "やすい", romaji: "yasui", meaning: "murah" },
      { kana: "せんえん", romaji: "sen'en", meaning: "1000 yen" },
    ], note: "Belanja: みせ(toko), ねだん(harga), たかい(mahal), やすい(murah)." },
    enemies: [{ id: "n4-cert-1", name: "Penguji Sertifikasi", sprite: "🎓", hp: 85, attack: 16, color: "#ff9800", abilities: ["time-pressure", "shield"] }],
    questions: [
      { type: "choice", prompt: "「ねだん」の いみは?", kana: "ねだん", options: ["harga", "toko", "murah", "mahal"], answer: 0 },
      { type: "choice", prompt: "「murah」は にほんごで?", options: ["やすい", "たかい", "みせ", "ねだん"], answer: 0 },
      { type: "typing", prompt: "ロマジで: みせ (toko)", kana: "みせ", answer: ["mise"] },
      { type: "choice", prompt: "「たかい」の いみは?", kana: "たかい", options: ["mahal/tinggi", "murah", "harga", "toko"], answer: 0 },
      { type: "typing", prompt: "ロマジで: せんえん (1000 yen)", kana: "せんえん", answer: ["sen'en", "senen", "sen'en"] },
    ],
    reward: { xp: 200 },
  },

  {
    id: "n4-32", worldId: "n4", index: 32, chapter: 4,
    title: "Kosakata Sekolah", subtitle: "Sekolah & pendidikan",
    type: "battle",
    intro: ["**Ruang Sertifikasi 2**", "Penguji: «Tema: sekolah!»"],
    outro: ["Penguji: «Sekolah terkuasai!»", "**Stage 32 selesai! +220 XP**"],
    lesson: { title: "Kosakata Sekolah", rows: [
      { kana: "がっこう", romaji: "gakkou", meaning: "sekolah" },
      { kana: "べんきょう", romaji: "benkyou", meaning: "belajar" },
      { kana: "しゅくだい", romaji: "shukudai", meaning: "PR/tugas" },
      { kana: "テスト", romaji: "tesuto", meaning: "ujian" },
      { kana: "せいせき", romaji: "seiseki", meaning: "nilai" },
      { kana: "ちゅうがっこう", romaji: "chuugakkou", meaning: "SMP" },
    ], note: "Sekolah: がっこう(sekolah), べんきょう(belajar), しゅくだい(PR), テスト(ujian)." },
    enemies: [{ id: "n4-cert-2", name: "Roh Sekolah", sprite: "🏫", hp: 90, attack: 17, color: "#3f51b5", abilities: ["crit", "shield"] }],
    questions: [
      { type: "choice", prompt: "「べんきょう」の いみは?", kana: "べんきょう", options: ["belajar", "sekolah", "PR", "ujian"], answer: 0 },
      { type: "choice", prompt: "「PR/tugas」は?", options: ["しゅくだい", "べんきょう", "テスト", "せいせき"], answer: 0 },
      { type: "typing", prompt: "ロマジで: がっこう (sekolah)", kana: "がっこう", answer: ["gakkou", "gakko"] },
      { type: "choice", prompt: "「せいせき」の いみは?", kana: "せいせき", options: ["nilai", "belajar", "sekolah", "PR"], answer: 0 },
      { type: "choice", prompt: "「テスト」の いみは?", kana: "テスト", options: ["ujian", "sekolah", "belajar", "nilai"], answer: 0 },
    ],
    reward: { xp: 220 },
  },

  {
    id: "n4-33", worldId: "n4", index: 33, chapter: 4,
    title: "Kosakata Kesehatan", subtitle: "Kesehatan & medis",
    type: "battle",
    intro: ["**Ruang Sertifikasi 3**", "Penguji: «Tema: kesehatan!»"],
    outro: ["Penguji: «Kesehatan terkuasai!»", "**Stage 33 selesai! +240 XP**"],
    lesson: { title: "Kosakata Kesehatan", rows: [
      { kana: "びょうき", romaji: "byouki", meaning: "sakit" },
      { kana: "くすり", romaji: "kusuri", meaning: "obat" },
      { kana: "ねつ", romaji: "netsu", meaning: "demam" },
      { kana: "いたい", romaji: "itai", meaning: "sakit (rasa)" },
      { kana: "げんき", romaji: "genki", meaning: "sehat/bugar" },
      { kana: "びょういん", romaji: "byouin", meaning: "rumah sakit" },
    ], note: "Kesehatan: びょうき(sakit), くすり(obat), ねつ(demam), いたい(sakit rasa), げんき(sehat)." },
    enemies: [{ id: "n4-cert-3", name: "Roh Medis", sprite: "🏥", hp: 95, attack: 18, color: "#f44336", abilities: ["poison", "regen"] }],
    questions: [
      { type: "choice", prompt: "「びょうき」の いみは?", kana: "びょうき", options: ["sakit", "obat", "demam", "sehat"], answer: 0 },
      { type: "choice", prompt: "「obat」は にほんごで?", options: ["くすり", "ねつ", "びょうき", "げんき"], answer: 0 },
      { type: "typing", prompt: "ロマジで: ねつ (demam)", kana: "ねつ", answer: ["netsu"] },
      { type: "choice", prompt: "「いたい」の いみは?", kana: "いたい", options: ["sakit (rasa)", "sehat", "obat", "rumah sakit"], answer: 0 },
      { type: "typing", prompt: "ロマジで: げんき (sehat)", kana: "げんき", answer: ["genki"] },
      { type: "choice", prompt: "「びょういん」の いみは?", kana: "びょういん", options: ["rumah sakit", "obat", "demam", "sehat"], answer: 0 },
    ],
    reward: { xp: 240 },
  },

  {
    id: "n4-34", worldId: "n4", index: 34, chapter: 4,
    title: "Kosakata Waktu", subtitle: "Waktu & jam",
    type: "battle",
    intro: ["**Ruang Sertifikasi 4**", "Penguji: «Tema: waktu & jam!»"],
    outro: ["Penguji: «Waktu terkuasai!»", "**Stage 34 selesai! +260 XP**"],
    lesson: { title: "Kosakata Waktu", rows: [
      { kana: "いま", romaji: "ima", meaning: "sekarang" },
      { kana: "きのう", romaji: "kinou", meaning: "kemarin" },
      { kana: "あした", romaji: "ashita", meaning: "besok" },
      { kana: "きょう", romaji: "kyou", meaning: "hari ini" },
      { kana: "しゅうまつ", romaji: "shuumatsu", meaning: "akhir pekan" },
      { kana: "まいにち", romaji: "mainichi", meaning: "setiap hari" },
    ], note: "Waktu: いま(sekarang), きのう(kemarin), あした(besok), きょう(hari ini), しゅうまつ(akhir pekan)." },
    enemies: [{ id: "n4-cert-4", name: "Penjaga Waktu", sprite: "⏰", hp: 100, attack: 19, color: "#cddc39", abilities: ["time-pressure", "shield"] }],
    questions: [
      { type: "choice", prompt: "「きのう」の いみは?", kana: "きのう", options: ["kemarin", "besok", "hari ini", "sekarang"], answer: 0 },
      { type: "choice", prompt: "「besok」は にほんごで?", options: ["あした", "きのう", "きょう", "いま"], answer: 0 },
      { type: "typing", prompt: "ロマジで: いま (sekarang)", kana: "いま", answer: ["ima"] },
      { type: "choice", prompt: "「しゅうまつ」の いみは?", kana: "しゅうまつ", options: ["akhir pekan", "setiap hari", "kemarin", "besok"], answer: 0 },
      { type: "typing", prompt: "ロマジで: まいにち (setiap hari)", kana: "まいにち", answer: ["mainichi"] },
    ],
    reward: { xp: 260 },
  },

  {
    id: "n4-35", worldId: "n4", index: 35, chapter: 4,
    title: "Kosakata Hobi", subtitle: "Hobi & kesukaan",
    type: "battle",
    intro: ["**Ruang Sertifikasi 5**", "Penguji: «Tema: hobi & kesukaan!»"],
    outro: ["Penguji: «Hobi terkuasai!»", "**Stage 35 selesai! +280 XP**"],
    lesson: { title: "Kosakata Hobi", rows: [
      { kana: "しゅみ", romaji: "shumi", meaning: "hobi" },
      { kana: "おんがく", romaji: "ongaku", meaning: "musik" },
      { kana: "えいが", romaji: "eiga", meaning: "film" },
      { kana: "スポーツ", romaji: "supootsu", meaning: "olahraga" },
      { kana: "ほん", romaji: "hon", meaning: "buku" },
      { kana: "りょうり", romaji: "ryouri", meaning: "memasak" },
      { kana: "りょこう", romaji: "ryokou", meaning: "perjalanan" },
    ], note: "Hobi: しゅみ(hobi), おんがく(musik), えいが(film), スポーツ(olahraga), りょうり(memasak)." },
    enemies: [{ id: "n4-cert-5", name: "Roh Hobi", sprite: "🎨", hp: 105, attack: 20, color: "#9c27b0", abilities: ["multi-attack", "crit"] }],
    questions: [
      { type: "choice", prompt: "「しゅみ」の いみは?", kana: "しゅみ", options: ["hobi", "musik", "film", "buku"], answer: 0 },
      { type: "choice", prompt: "「musik」は にほんごで?", options: ["おんがく", "えいが", "ほん", "りょうり"], answer: 0 },
      { type: "typing", prompt: "ロマジで: りょこう (perjalanan)", kana: "りょこう", answer: ["ryokou", "ryoko"] },
      { type: "choice", prompt: "「スポーツ」の いみは?", kana: "スポーツ", options: ["olahraga", "musik", "film", "buku"], answer: 0 },
      { type: "typing", prompt: "ロマジで: ほん (buku)", kana: "ほん", answer: ["hon"] },
      { type: "choice", prompt: "「りょうり」の いみは?", kana: "りょうり", options: ["memasak", "perjalanan", "hobi", "musik"], answer: 0 },
    ],
    reward: { xp: 280 },
  },

  {
    id: "n4-36", worldId: "n4", index: 36, chapter: 4,
    title: "Grammar: ~ましょう", subtitle: "Ajakan sopan (~ましょう)",
    type: "battle",
    intro: ["**Ruang Sertifikasi 6**", "Penguji: «Bentuk ajakan sopan: ~ましょう. Pelajari!»"],
    outro: ["Penguji: «Ajakan terkuasai!»", "**Stage 36 selesai! +300 XP**"],
    lesson: { title: "~ましょう (Ajakan)", rows: [
      { kana: "たべましょう", romaji: "tabemashou", meaning: "mari makan" },
      { kana: "いきましょう", romaji: "ikimashou", meaning: "mari pergi" },
      { kana: "みましょう", romaji: "mimashou", meaning: "mari lihat" },
      { kana: "べんきょうしましょう", romaji: "benkyou shimashou", meaning: "mari belajar" },
    ], note: "~ましょう = mari/ajakan sopan. Pola: stem + ましょう. tabeMASHOU = mari makan." },
    enemies: [{ id: "n4-cert-6", name: "Roh Ajakan", sprite: "🤝", hp: 110, attack: 21, color: "#4caf50", abilities: ["shield", "counter"] }],
    questions: [
      { type: "choice", prompt: "「たべましょう」の いみは?", kana: "たべましょう", options: ["mari makan", "mari pergi", "mari lihat", "mari belajar"], answer: 0 },
      { type: "typing", prompt: "ロマジで: いきましょう (mari pergi)", kana: "いきましょう", answer: ["ikimashou"] },
      { type: "choice", prompt: "「~ましょう」の いみは?", options: ["mari/ajakan", "karena", "jika", "tetapi"], answer: 0 },
      { type: "typing", prompt: "~ましょう dari みる:", kana: "みましょう", answer: ["mimashou"] },
      { type: "choice", prompt: "「べんきょうしましょう」の いみは?", kana: "べんきょうしましょう", options: ["mari belajar", "mari makan", "mari pergi", "mari lihat"], answer: 0 },
    ],
    reward: { xp: 300 },
  },

  {
    id: "n4-37", worldId: "n4", index: 37, chapter: 4,
    title: "Grammar: ~つもり", subtitle: "Rencana (~つもり)",
    type: "battle",
    intro: ["**Ruang Sertifikasi 7**", "Penguji: «Bentuk rencana: ~つもり. 'Aku berencana untuk...'»"],
    outro: ["Penguji: «Rencana terkuasai!»", "**Stage 37 selesai! +320 XP**"],
    lesson: { title: "~つもり (Rencana)", rows: [
      { kana: "いく つもり です", romaji: "iku tsumori desu", meaning: "berencana pergi" },
      { kana: "たべる つもり です", romaji: "taberu tsumori desu", meaning: "berencana makan" },
      { kana: "べんきょうする つもり", romaji: "benkyou suru tsumori", meaning: "berencana belajar" },
    ], note: "~つもり です = berencana untuk. Pola: bentuk kasual + つもり です. iku tsumori = berencana pergi." },
    enemies: [{ id: "n4-cert-7", name: "Perencana", sprite: "📋", hp: 115, attack: 22, color: "#ff9800", abilities: ["enrage", "shield"] }],
    questions: [
      { type: "choice", prompt: "「いく つもり です」の いみは?", kana: "いく つもり です", options: ["berencana pergi", "berencana makan", "sudah pergi", "tidak pergi"], answer: 0 },
      { type: "typing", prompt: "ロマジで: たべる つもり です", kana: "たべる つもり です", answer: ["taberu tsumori desu"] },
      { type: "choice", prompt: "「~つもり です」の いみは?", options: ["berencana untuk", "mari/ajakan", "jika", "karena"], answer: 0 },
      { type: "typing", prompt: "ロマジで: べんきょうする つもり", kana: "べんきょうする つもり", answer: ["benkyou suru tsumori", "benkyou suru tsumori"] },
    ],
    reward: { xp: 320 },
  },

  {
    id: "n4-38", worldId: "n4", index: 38, chapter: 4,
    title: "Grammar: ~ことがある", subtitle: "Pengalaman (~ことがある)",
    type: "battle",
    intro: ["**Ruang Sertifikasi 8**", "Penguji: «Bentuk pengalaman: ~ことがある. 'Pernah...'»"],
    outro: ["Penguji: «Pengalaman terkuasai!»", "**Stage 38 selesai! +340 XP**"],
    lesson: { title: "~ことがある (Pengalaman)", rows: [
      { kana: "いった ことが あります", romaji: "itta koto ga arimasu", meaning: "pernah pergi" },
      { kana: "たべた ことが あります", romaji: "tabeta koto ga arimasu", meaning: "pernah makan" },
      { kana: "みた ことが あります", romaji: "mita koto ga arimasu", meaning: "pernah lihat" },
    ], note: "~た ことが あります = pernah. Pola: ta-form + ことが ある. itta koto = pernah pergi." },
    enemies: [{ id: "n4-cert-8", name: "Roh Pengalaman", sprite: "💭", hp: 120, attack: 23, color: "#7e57c2", abilities: ["poison", "multi-attack"] }],
    questions: [
      { type: "choice", prompt: "「いった ことが あります」の いみは?", kana: "いった ことが あります", options: ["pernah pergi", "berencana pergi", "mari pergi", "tidak pergi"], answer: 0 },
      { type: "typing", prompt: "ロマジで: たべた ことが あります", kana: "たべた ことが あります", answer: ["tabeta koto ga arimasu"] },
      { type: "choice", prompt: "「~た ことが あります」の いみは?", options: ["pernah", "berencana", "mari", "jika"], answer: 0 },
      { type: "typing", prompt: "ロマジで: みた ことが あります (pernah lihat)", kana: "みた ことが あります", answer: ["mita koto ga arimasu"] },
    ],
    reward: { xp: 340 },
  },

  {
    id: "n4-39", worldId: "n4", index: 39, chapter: 4,
    title: "Pra-Ujian Akhir", subtitle: "Review akhir - full Japanese",
    type: "battle",
    intro: ["**Ruang Sertifikasi 9 - Pra-Final**", "Penguji: «Review terakhir! Semua materi N4. Full Japanese!»"],
    outro: ["Penguji: «Kau siap ujian akhir!»", "**Stage 39 selesai! +380 XP**"],
    lesson: undefined,
    enemies: [{ id: "n4-final-review", name: "Master Final Review", sprite: "📚", hp: 130, attack: 24, color: "#7c4dff", abilities: ["enrage", "shield", "counter", "crit", "time-pressure"] }],
    questions: [
      { type: "typing", prompt: "te-form dari 食べる:", kana: "食べて", answer: ["tabete"] },
      { type: "choice", prompt: "「びょうき」の いみは?", kana: "びょうき", options: ["sakit", "obat", "demam", "sehat"], answer: 0 },
      { type: "choice", prompt: "「きのう」の いみは?", kana: "きのう", options: ["kemarin", "besok", "hari ini", "sekarang"], answer: 0 },
      { type: "typing", prompt: "ロマジで: たべましょう (mari makan)", kana: "たべましょう", answer: ["tabemashou"] },
      { type: "choice", prompt: "「しゅみ」の いみは?", kana: "しゅみ", options: ["hobi", "musik", "film", "buku"], answer: 0 },
      { type: "typing", prompt: "ロマジで: いく つもり です (berencana pergi)", kana: "いく つもり です", answer: ["iku tsumori desu"] },
      { type: "choice", prompt: "「〜ことが あります」の いみは?", options: ["pernah", "berencana", "mari", "jika"], answer: 0 },
      { type: "choice", prompt: "「はれ」の いみは?", kana: "はれ", options: ["cerah", "hujan", "salju", "mendung"], answer: 0 },
    ],
    reward: { xp: 380 },
  },

  {
    id: "n4-40", worldId: "n4", index: 40, chapter: 4,
    title: "Ujian Akhir Sertifikasi", subtitle: "Bos Akhir: Harbor Master",
    type: "boss",
    intro: [
      "**Gedung Sertifikasi - Aula Utama**",
      "**Harbor Master Minato** duduk di singgasana. «Pengelana, ini ujian akhir tingkat Madya Bawah!»",
      "«Semua soal dalam bahasa Jepang penuh. Lulus, dan kau naik ke tingkat Madya - Kage Clan!»",
      "**UJIAN AKHIR TINGKAT MADYA BAWAH DIMULAI**",
    ],
    outro: [
      "Harbor Master: «Kau lulus sempurna! Gelar «Sarjana Madya Bawah» adalah milikmu!»",
      "Ia menyerahkan sertifikat emas. «Lanjut ke Kage Clan - tingkat Madya menunggu!»",
      "**UJIAN AKHIR MADYA BAWAH SELESAI! +1200 XP, 800 koin, Badge: Sarjana Madya Bawah, Item: Sertifikat Minato**",
      "**Dunia baru terbuka: Kage Clan (Tingkat Madya)**",
    ],
    lesson: undefined,
    enemies: [{ id: "harbor-master", name: "Harbor Master Minato", sprite: "🎩", hp: 250, attack: 25, color: "#01579b", abilities: ["enrage", "heal", "crit", "shield", "multi-attack", "counter", "poison", "time-pressure"] }],
    questions: [
      { type: "typing", prompt: "te-form dari 食べる:", kana: "食べて", answer: ["tabete"] },
      { type: "typing", prompt: "nai-form のむ:", kana: "飲まない", answer: ["nomanai"] },
      { type: "choice", prompt: "「読む」の いみは?", kana: "読む", options: ["baca", "tulis", "lihat", "bicara"], answer: 0 },
      { type: "choice", prompt: "「びょうき」の いみは?", kana: "びょうき", options: ["sakit", "obat", "demam", "sehat"], answer: 0 },
      { type: "typing", prompt: "ロマジで: もう たべました (sudah makan)", kana: "もう たべました", answer: ["mou tabemashita"] },
      { type: "choice", prompt: "「きのう」の いみは?", kana: "きのう", options: ["kemarin", "besok", "hari ini", "sekarang"], answer: 0 },
      { type: "typing", prompt: "ロマジで: たべましょう (mari makan)", kana: "たべましょう", answer: ["tabemashou"] },
      { type: "choice", prompt: "「しゅみ」の いみは?", kana: "しゅみ", options: ["hobi", "musik", "film", "buku"], answer: 0 },
      { type: "typing", prompt: "ロマジで: いく つもり です", kana: "いく つもり です", answer: ["iku tsumori desu"] },
      { type: "choice", prompt: "「〜ことが あります」の いみは?", options: ["pernah", "berencana", "mari", "jika"], answer: 0 },
      { type: "choice", prompt: "「はれ」の いみは?", kana: "はれ", options: ["cerah", "hujan", "salju", "mendung"], answer: 0 },
      { type: "typing", prompt: "ロマジで: くすり (obat)", kana: "くすり", answer: ["kusuri"] },
    ],
    reward: { xp: 1200, badge: "Sarjana Madya Bawah", item: "Sertifikat Minato" },
  },
];
