import type { Stage } from "./types";

// ===== VASSAL KINGDOM - CHAPTER 1: Tingkat Dasar =====
// 10 stages covering: greetings, particles, basic grammar, first kanji, common vocab.
// Story: Player arrives at Vassal Kingdom after defeating Shadow King.
// The kingdom's market is in chaos - merchants can't speak properly.
// Player must restore communication by learning N5 Japanese.

export const N5_STAGES: Stage[] = [
  // ===== STAGE 1: GREETINGS =====
  {
    id: "n5-1",
    worldId: "n5",
    index: 1,
    chapter: 1,
    title: "Tiba di Vassal Kingdom",
    subtitle: "Salam & Percakapan Dasar",
    type: "lesson",
    intro: [
      "**Gerbang Vassal Kingdom - Pagi**",
      "Setelah perjalanan panjang dari desa Hajimari, kau tiba di gerbang besar Kerajaan Vassal.",
      "Penjaga gerbang menyapa: ããã¯ãããããã¾ã! Selamat pagi, pengelana!ã",
      "Yuki (yang ikut): ãDi sini orang berbicara dengan kalimat utuh. Kau harus belajar salam dasar.ã",
      "ãIni fondasi semua percakapan N5 - salam, terima kasih, permohonan maaf.ã",
    ],
    outro: [
      "Penjaga tersenyum. ããã¯ãããããã¾ã! Silakan masuk. Semoga harimu menyenangkan!ã",
      "Yuki: ÂÂ«Sekarang kau bisa menyapa siapa saja! Tapi pasar sedang kacau...ã",
      "**Stage 1 selesai! +70 XP, 25 koin**",
    ],
    lesson: {
      title: "Salam & Percakapan Dasar",
      rows: [
        { kana: "ãã¯ãã", romaji: "ohayou", meaning: "selamat pagi (santai)" },
        { kana: "ãã¯ãããããã¾ã", romaji: "ohayou gozaimasu", meaning: "selamat pagi (formal)" },
        { kana: "ãããÂ«ã¡ã¯", romaji: "konnichiwa", meaning: "halo / selamat siang" },
        { kana: "ããã°ãã¯", romaji: "konbanwa", meaning: "selamat malam" },
        { kana: "ããããªã", romaji: "sayounara", meaning: "selamat tinggal" },
        { kana: "ãããã¨ã", romaji: "arigatou", meaning: "terima kasih" },
        { kana: "ãã¿ã¾ãã", romaji: "sumimasen", meaning: "maaf / permisi" },
        { kana: "ã¯ããã¾ãã¦", romaji: "hajimemashite", meaning: "senang berkenalan" },
      ],
      note: "Formal: tambah 'gozaimasu' (ãããã¾ã). 'sumimasen' bisa berarti 'maaf' ATAU 'permisi' ATAU 'minta perhatian'.",
    },
    enemies: [
      {
        id: "confused-merchant",
        name: "Pedagang Bingung",
        nameJp: "åäºº",
        sprite: "ð§âð¾",
        hp: 12,
        attack: 3,
        description: "Tidak bisa menyapa dengan benar.",
        color: "#8d6e63",
        abilities: ["regen"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Apa arti 'ãã¯ãããããã¾ã'?",
        kana: "ãã¯ãããããã¾ã",
        options: ["selamat pagi (formal)", "selamat malam", "selamat tinggal", "terima kasih"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "'ãããÂ«ã¡ã¯' digunakan kapan?",
        kana: "ãããÂ«ã¡ã¯",
        options: ["pagi hari", "siang/sore", "malam hari", "selalu"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'terima kasih':",
        kana: "ãããã¨ã",
        answer: ["arigatou", "arigato"],
      },
      {
        type: "choice",
        prompt: "Saat meminta perhatian seseorang, kau bilang?",
        options: ["ãããã¨ã", "ãã¿ã¾ãã", "ããããªã", "ãããÂ«ã¡ã¯"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'senang berkenalan':",
        kana: "ã¯ããã¾ãã¦",
        answer: ["hajimemashite"],
      },
    ],
    reward: { xp: 70 },
  },

  // ===== STAGE 2: PRONOUNS =====
  {
    id: "n5-2",
    worldId: "n5",
    index: 2,
    chapter: 1,
    title: "Siapa Kau? Siapa Aku?",
    subtitle: "Kata Ganti Orang",
    type: "battle",
    intro: [
      "**Alun-alun Vassal Kingdom**",
      "Di alun-alun, kau melihat seorang anak kecil menangis. ãããªãã¯... ããªãã¯...ã",
      "Ia tidak bisa menyebut nama orang. ãAku tidak tahu kata ganti!ã",
      "Yuki: ãKata ganti orang penting untuk percakapan. ããã (saya), ããªã (kamu), ãã (dia laki-laki), ãã®ãã (dia perempuan).ã",
    ],
    outro: [
      "Anak itu tersenyum. ããããã¯ ãã¢ ã§ã! Nama saya Tomo! Terima kasih, pengelana!ã",
      "Yuki: ÂÂ«Bagus! Sekarang kau bisa memperkenalkan diri.ÂÂ»",
      "**Stage 2 selesai! +80 XP, 30 koin**",
    ],
    lesson: {
      title: "Kata Ganti Orang (Pronouns)",
      rows: [
        { kana: "ããã", romaji: "watashi", meaning: "saya (umum)" },
        { kana: "ã¼ã", romaji: "boku", meaning: "saya (laki-laki, santai)" },
        { kana: "ãã", romaji: "ore", meaning: "saya (laki-laki, kasual)" },
        { kana: "ããªã", romaji: "anata", meaning: "kamu" },
        { kana: "ãã", romaji: "kare", meaning: "dia (laki-laki) / pacar" },
        { kana: "ãã®ãã", romaji: "kanojo", meaning: "dia (perempuan) / pacar" },
        { kana: "ããããã¡", romaji: "watashitachi", meaning: "kami / kita" },
      ],
      note: "'watashi' paling aman dipakai semua orang. 'boku' & 'ore' untuk laki-laki. 'anata' jarang dipakai - lebih baik sebut nama orangnya!",
    },
    enemies: [
      {
        id: "name-thief",
        name: "Pencuri Nama",
        nameJp: "ååæ³¥æ£",
        sprite: "ð­",
        hp: 15,
        attack: 4,
        color: "#9c27b0",
        abilities: ["multi-attack", "poison"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Apa arti 'ããã'?",
        kana: "ããã",
        options: ["kamu", "saya", "dia", "kami"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "Kata ganti 'kamu' adalah?",
        options: ["ããã", "ããªã", "ãã", "ããããã¡"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'dia (perempuan)':",
        kana: "ãã®ãã",
        answer: ["kanojo"],
      },
      {
        type: "choice",
        prompt: "'ã¼ã' (boku) biasanya dipakai oleh?",
        options: ["perempuan saja", "laki-laki", "anak-anak saja", "orang tua"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'kami / kita':",
        kana: "ããããã¡",
        answer: ["watashitachi"],
      },
    ],
    reward: { xp: 80 },
  },

  // ===== STAGE 3: DESU (TO BE) =====
  {
    id: "n5-3",
    worldId: "n5",
    index: 3,
    chapter: 1,
    title: "Adalah, Adalah, Adalah",
    subtitle: "Polite Copula: ã§ã (desu)",
    type: "battle",
    intro: [
      "**Toko Roti Vassal**",
      "Kau masuk ke toko roti. Penjual: ãããã¯ ãã³ ã§ã!ã",
      "Tapi aneh - semua barang ditandai sebagai 'pan' (roti) meski bukan roti!",
      "Yuki: ãã§ã (desu) berarti 'adalah' - kata penghubung kalimat. Tapi salah dipakai, semua jadi roti!ã",
      "ãPelajari pola: A ã¯ B ã§ã (A adalah B).ã",
    ],
    outro: [
      "Toko roti kembali normal. Penjual: ãããã¯ ã±ã¼ã­ ã§ã!ã",
      "Yuki: ÂÂ«Sekarang kau bisa membuat kalimat sederhana!ÂÂ»",
      "**Stage 3 selesai! +90 XP, 35 koin**",
    ],
    lesson: {
      title: "Polite Copula ã§ã (desu)",
      rows: [
        { kana: "ã§ã", romaji: "desu", meaning: "adalah (formal, positif)" },
        { kana: "ãããªãã§ã", romaji: "ja nai desu", meaning: "bukan (formal, negatif)" },
        { kana: "ã¯", romaji: "wa", meaning: "partikel topik (dibaca 'wa')" },
        { kana: "ã", romaji: "mo", meaning: "juga" },
      ],
      note: "Pola dasar: A ã¯ B ã§ã = A adalah B. 'ã¯' ditulis 'ha' tapi dibaca 'wa' sebagai partikel topik!",
    },
    enemies: [
      {
        id: "is-bug",
        name: "Bug Adalah",
        nameJp: "ã§ããã°",
        sprite: "ð",
        hp: 18,
        attack: 4,
        color: "#76ff03",
        abilities: ["multi-attack", "crit"],
        critChance: 0.15,
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "ãããã¯ ãã³ ã§ãã artinya?",
        kana: "ããã¯ ãã³ ã§ã",
        options: ["Ini adalah roti", "Itu adalah roti", "Aku adalah roti", "Roti adalah ini"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "Partikel 'ã¯' dibaca sebagai?",
        options: ["ha", "wa", "ba", "pa"],
        answer: 1,
        hint: "Pengecualian partikel topik!",
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'adalah' (formal):",
        kana: "ã§ã",
        answer: ["desu"],
      },
      {
        type: "choice",
        prompt: "ããããã¯ ãããã ã§ãã artinya?",
        kana: "ãããã¯ ãããã ã§ã",
        options: ["Saya adalah murid", "Kamu adalah murid", "Dia adalah murid", "Murid adalah saya"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "ãããã ãã³ ã§ãã - 'ã' berarti?",
        options: ["adalah", "bukan", "juga", "atau"],
        answer: 2,
      },
    ],
    reward: { xp: 90 },
  },

  // ===== STAGE 4: NUMBERS 1-10 =====
  {
    id: "n5-4",
    worldId: "n5",
    index: 4,
    chapter: 1,
    title: "Menghitung Harta",
    subtitle: "Angka 1-10",
    type: "battle",
    intro: [
      "**Pasar Vassal - Sibuk**",
      "Pasar sedang kacau! Pedagang tidak bisa menyebut harga.",
      "ããã... ããã?ã (Ini berapa?) ÂÂ«Saya lupa angka!ÂÂ»",
      "Yuki: ãBelajar 1-10 dulu. Penting untuk transaksi!ã",
    ],
    outro: [
      "Pasar kembali ramai. Pedagang berseru: ããã ã¯ ããã³ãããã ã§ã! 300 yen!ã",
      "Yuki: ÂÂ«Bagus! Sekarang bisa bertransaksi.ÂÂ»",
      "**Stage 4 selesai! +100 XP, 40 koin**",
    ],
    lesson: {
      title: "Angka 1-10",
      rows: [
        { kana: "ãã¡", romaji: "ichi", meaning: "1" },
        { kana: "ãÂ«", romaji: "ni", meaning: "2" },
        { kana: "ãã", romaji: "san", meaning: "3" },
        { kana: "ã/ãã", romaji: "shi/yon", meaning: "4 (yon lebih umum)" },
        { kana: "ã", romaji: "go", meaning: "5" },
        { kana: "ãã", romaji: "roku", meaning: "6" },
        { kana: "ãã¡/ãªãª", romaji: "shichi/nana", meaning: "7 (nana lebih umum)" },
        { kana: "ã¯ã¡", romaji: "hachi", meaning: "8" },
        { kana: "ããã/ã", romaji: "kyuu/ku", meaning: "9" },
        { kana: "ããã", romaji: "juu", meaning: "10" },
      ],
      note: "4 (shi) & 7 (shichi) sering dihindari karena 'shi' juga berarti 'mati'. Pakai 'yon' & 'nana' lebih aman!",
    },
    enemies: [
      {
        id: "number-ghost",
        name: "Hantu Angka",
        nameJp: "æ°å­",
        sprite: "ð¢",
        hp: 20,
        attack: 6,
        color: "#ff9800",
        abilities: ["poison", "time-pressure"],
      },
    ],
    questions: [
      {
        type: "typing",
        prompt: "Romaji untuk '1':",
        kana: "ãã¡",
        answer: ["ichi"],
      },
      {
        type: "typing",
        prompt: "Romaji untuk '3':",
        kana: "ãã",
        answer: ["san"],
      },
      {
        type: "choice",
        prompt: "Angka '4' biasanya dibaca (lebih umum)?",
        options: ["shi", "yon", "suu", "yo"],
        answer: 1,
        hint: "'shi' juga berarti 'mati', jadi dihindari",
      },
      {
        type: "typing",
        prompt: "Romaji untuk '5':",
        kana: "ã",
        answer: ["go"],
      },
      {
        type: "typing",
        prompt: "Romaji untuk '7' (lebih umum):",
        kana: "ãªãª",
        answer: ["nana"],
      },
      {
        type: "typing",
        prompt: "Romaji untuk '10':",
        kana: "ããã",
        answer: ["juu", "ju"],
      },
    ],
    reward: { xp: 100 },
  },

  // ===== STAGE 5: MINI-BOSS - DAYS OF WEEK =====
  {
    id: "n5-5",
    worldId: "n5",
    index: 5,
    chapter: 1,
    title: "Ujian Penjaga Waktu",
    subtitle: "Mini-Boss: Hari & Bulan",
    type: "mini-boss",
    intro: [
      "**Menara Jam Vassal**",
      "Sesosok kurcaci berjanggut panjang menunggumu di puncak menara.",
      "ãAku **Tokkun**, penjaga waktu. Hari apa ini? Bulan apa ini? Kalau tidak tahu, kau tak boleh lewat!ã",
      "Yuki: ãHari dalam seminggu pakai 'youbi'. Bulan pakai 'gatsu'. Pelajari baik-baik!ã",
    ],
    outro: [
      "Tokkun tertawa puas. ãKau tahu waktuku! Silakan lanjut ke kastil dalam.ÂÂ»",
      "Ia memberimu kunci kecil. ÂÂ«Ini kunci menuju perpustakaan kerajaan.ÂÂ»",
      "**Stage 5 selesai! +150 XP, 50 koin, Item: Kunci Perpustakaan, Badge: Lulus Ujian Waktu**",
    ],
    lesson: {
      title: "Hari & Bulan",
      rows: [
        { kana: "ãã¤ããã³", romaji: "getsuyoubi", meaning: "Senin" },
        { kana: "ãããã³", romaji: "kayoubi", meaning: "Selasa" },
        { kana: "ããããã³", romaji: "suiyoubi", meaning: "Rabu" },
        { kana: "ããããã³", romaji: "mokuyoubi", meaning: "Kamis" },
        { kana: "ããããã³", romaji: "kinyoubi", meaning: "Jumat" },
        { kana: "ã©ããã³", romaji: "doyoubi", meaning: "Sabtu" },
        { kana: "ãÂ«ã¡ããã³", romaji: "nichiyoubi", meaning: "Minggu" },
        { kana: "ãã¡ãã¤", romaji: "ichigatsu", meaning: "Januari (bulan 1)" },
      ],
      note: "Hari: [nama] + youbi. Senin=getsu(bulan), Minggu=nichi(matahari). Bulan: [angka] + gatsu.",
    },
    enemies: [
      {
        id: "tokkun",
        name: "Tokkun Penjaga Waktu",
        nameJp: "ããã¯ã³",
        sprite: "â°",
        hp: 48,
        attack: 10,
        description: "Mini-boss: ujian hari & bulan.",
        color: "#cddc39",
        abilities: ["time-pressure", "shield", "enrage"],
      },
    ],
    questions: [
      {
        type: "typing",
        prompt: "Romaji untuk 'Senin':",
        kana: "ãã¤ããã³",
        answer: ["getsuyoubi", "getsuyobi"],
      },
      {
        type: "choice",
        prompt: "ãããããã³ã adalah hari?",
        kana: "ããããã³",
        options: ["Senin", "Selasa", "Rabu", "Kamis"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'Jumat':",
        kana: "ããããã³",
        answer: ["kinyoubi", "kinyobi"],
      },
      {
        type: "choice",
        prompt: "ããÂ«ã¡ããã³ã adalah?",
        kana: "ãÂ«ã¡ããã³",
        options: ["Sabtu", "Minggu", "Senin", "Kamis"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'Januari' (bulan 1):",
        kana: "ãã¡ãã¤",
        answer: ["ichigatsu"],
      },
      {
        type: "choice",
        prompt: "Suffix untuk hari adalah?",
        options: ["gatsu", "youbi", "nichi", "ka"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "Suffix untuk bulan adalah?",
        options: ["youbi", "gatsu", "nichi", "ka"],
        answer: 1,
      },
    ],
    reward: { xp: 150, item: "Kunci Perpustakaan", badge: "Lulus Ujian Waktu" },
  },

  // ===== STAGE 6: KANJI NUMBERS 1-10 =====
  {
    id: "n5-6",
    worldId: "n5",
    index: 6,
    chapter: 1,
    title: "Perpustakaan Kerajaan",
    subtitle: "Kanji Angka: ä¸äºä¸åäºå­ä¸åÂ«ä¹å",
    type: "lesson",
    intro: [
      "**Perpustakaan Kerajaan Vassal**",
      "Setelah membuka pintu perpustakaan dengan kuncimu, kau melihat ribuan buku.",
      "Tapi semua buku tertulis dalam karakter aneh - Kanji!",
      "Pustakawan: ãDi sini buku pakai Kanji, huruf Tionghoa yang diadopsi Jepang. Mulai dengan angka.ã",
      "Yuki: ãKanji angka paling dasar. Bentuknya sederhana - belajar dulu 1-10.ã",
    ],
    outro: [
      "Pustakawan tersenyum. ãKau cepat belajar! Tapi Kanji banyak sekali - di N5 sekitar 100.ÂÂ»",
      "Ia memberimu kamus Kanji. ÂÂ«Ini akan membantumu mengenali kanji dasar.ÂÂ»",
      "**Stage 6 selesai! +110 XP, 45 koin, Item: Kamus Kanji Dasar**",
    ],
    lesson: {
      title: "Kanji Angka 1-10",
      rows: [
        { kana: "ä¸", romaji: "ichi", meaning: "satu" },
        { kana: "äº", romaji: "ni", meaning: "dua" },
        { kana: "ä¸", romaji: "san", meaning: "tiga" },
        { kana: "å", romaji: "yon/yo", meaning: "empat" },
        { kana: "äº", romaji: "go", meaning: "lima" },
        { kana: "å­", romaji: "roku", meaning: "enam" },
        { kana: "ä¸", romaji: "nana/shichi", meaning: "tujuh" },
        { kana: "åÂ«", romaji: "hachi", meaning: "delapan" },
        { kana: "ä¹", romaji: "kyuu/ku", meaning: "sembilan" },
        { kana: "å", romaji: "juu", meaning: "sepuluh" },
      ],
      note: "Kanji angka sering muncul di alamat, tanggal, harga. ä¸äºä¸ = 123, kombinasi: åä¸ = 11, äºå = 20.",
    },
    enemies: [
      {
        id: "kanji-tutor",
        name: "Tutor Kanji",
        nameJp: "æ¼¢å­",
        sprite: "ð",
        hp: 22,
        attack: 6,
        color: "#3f51b5",
        abilities: ["shield", "counter"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Kanji 'ä¸' dibaca?",
        kana: "ä¸",
        options: ["ichi (1)", "ni (2)", "san (3)", "juu (10)"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "Kanji 'ä¸' adalah angka?",
        kana: "ä¸",
        options: ["1", "2", "3", "5"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "Romaji untuk Kanji 'ä¸':",
        kana: "ä¸",
        answer: ["nana", "shichi"],
      },
      {
        type: "choice",
        prompt: "Kanji 'å' berarti?",
        kana: "å",
        options: ["1", "5", "10", "100"],
        answer: 2,
      },
      {
        type: "choice",
        prompt: "ãåä¸ã artinya?",
        kana: "åä¸",
        options: ["9 (10-1)", "11 (10+1)", "20 (10Ã2)", "1 (10/10)"],
        answer: 1,
        hint: "Kanji digabung: å(10) + ä¸(1) = 11",
      },
      {
        type: "typing",
        prompt: "Romaji untuk Kanji 'äº':",
        kana: "äº",
        answer: ["go"],
      },
    ],
    reward: { xp: 110, item: "Kamus Kanji Dasar" },
  },

  // ===== STAGE 7: KANJI DASAR (orang, hari, bulan) =====
  {
    id: "n5-7",
    worldId: "n5",
    index: 7,
    chapter: 1,
    title: "Kanji Kehidupan Sehari-hari",
    subtitle: "äºº, æ¥, æ, çÂ«, æ°´",
    type: "battle",
    intro: [
      "**Lorong Perpustakaan**",
      "Buku-buku berkilau di rak. Satu buku melayang: ãPelajari kami, pemuda!ã",
      "ãKanji dasar yang sering muncul: äºº (orang), æ¥ (hari/matahari), æ (bulan), çÂ« (api), æ°´ (air).ã",
      "Yuki: ãIni kanji yang dipakai dalam nama hari! getsuyoubi = æ + youbi.ÂÂ»",
    ],
    outro: [
      "Buku-buku di rak berdenting senang. ãKau mengenal kami sekarang!ÂÂ»",
      "Yuki: ÂÂ«Bagus! Sekarang kau bisa membaca tanda-tanda dasar di kerajaan.ÂÂ»",
      "**Stage 7 selesai! +120 XP, 50 koin**",
    ],
    lesson: {
      title: "Kanji Dasar Kehidupan",
      rows: [
        { kana: "äºº", romaji: "hito/nin", meaning: "orang" },
        { kana: "æ¥", romaji: "hi/nichi", meaning: "hari/matahari" },
        { kana: "æ", romaji: "tsuki/getsu", meaning: "bulan/bulan(kalender)" },
        { kana: "çÂ«", romaji: "hi/ka", meaning: "api" },
        { kana: "æ°´", romaji: "mizu/sui", meaning: "air" },
        { kana: "æ¨", romaji: "ki/moku", meaning: "pohon/kayu" },
        { kana: "é", romaji: "kin/kane", meaning: "emas/uang" },
        { kana: "æ¬", romaji: "hon", meaning: "asal/buku" },
      ],
      note: "Hari dalam seminggu pakai kanji ini! æ(getsu=Senin), çÂ«(ka=Selasa), æ°´(sui=Rabu), æ¨(moku=Kamis), é(kin=Jumat), å(do=Sabtu), æ¥(nichi=Minggu).",
    },
    enemies: [
      {
        id: "kanji-book",
        name: "Buku Kanji Hidup",
        nameJp: "æ¬",
        sprite: "ð",
        hp: 25,
        attack: 6,
        color: "#795548",
        abilities: ["heal", "shield"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Kanji 'äºº' berarti?",
        kana: "äºº",
        options: ["pohon", "orang", "air", "api"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "Kanji 'æ¥' berarti?",
        kana: "æ¥",
        options: ["bulan", "matahari/hari", "orang", "uang"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk Kanji 'æ' (saat artinya bulan di langit):",
        kana: "æ",
        answer: ["tsuki"],
      },
      {
        type: "choice",
        prompt: "Kanji 'æ°´' berarti?",
        kana: "æ°´",
        options: ["api", "tanah", "air", "angin"],
        answer: 2,
      },
      {
        type: "choice",
        prompt: "Hari Senin 'ãã¤ããã³' pakai kanji?",
        kana: "ãã¤ããã³",
        options: ["æ¥", "æ", "çÂ«", "æ¨"],
        answer: 1,
        hint: "getsu = bulan",
      },
      {
        type: "typing",
        prompt: "Romaji untuk Kanji 'æ¬' (saat artinya buku):",
        kana: "æ¬",
        answer: ["hon"],
      },
    ],
    reward: { xp: 120 },
  },

  // ===== STAGE 8: VERB FORMS (masu) =====
  {
    id: "n5-8",
    worldId: "n5",
    index: 8,
    chapter: 1,
    title: "Aksi & Kehendak",
    subtitle: "Kata Kerja Bentuk ã¾ã (masu)",
    type: "battle",
    intro: [
      "**Halaman Kastil Dalam**",
      "Kau tiba di kastil dalam. Para penjaga sedang latihan pedang.",
      "Komandan: ããã¹ã¾ã! (makan!) ã®ã¿ã¾ã! (minum!) ããã¾ã! (pergi!)ã",
      "ãPelajari bentuk ã¾ã (masu) - bentuk sopan kata kerja. Ini dasar semua kalimat kerja!ÂÂ»",
      "Yuki: ãã¾ã (masu) = bentuk sopan positif. ã¾ãã (masen) = bentuk sopan negatif.ÂÂ»",
    ],
    outro: [
      "Komandan mengangguk. ãKau paham kata kerja! Sekarang bisa menyuruh dan menyatakan aksi.ÂÂ»",
      "**Stage 8 selesai! +130 XP, 55 koin**",
    ],
    lesson: {
      title: "Kata Kerja Bentuk ã¾ã (masu)",
      rows: [
        { kana: "ãã¹ã¾ã", romaji: "tabemasu", meaning: "makan (sopan)" },
        { kana: "ã®ã¿ã¾ã", romaji: "nomimasu", meaning: "minum (sopan)" },
        { kana: "ããã¾ã", romaji: "ikimasu", meaning: "pergi (sopan)" },
        { kana: "ãã¾ã", romaji: "kimasu", meaning: "datang (sopan)" },
        { kana: "ã¿ã¾ã", romaji: "mimasu", meaning: "melihat (sopan)" },
        { kana: "ããã¾ã", romaji: "kikimasu", meaning: "mendengar (sopan)" },
        { kana: "ãã¿ã¾ã", romaji: "yomimasu", meaning: "membaca (sopan)" },
        { kana: "ããã¾ã", romaji: "kakimasu", meaning: "menulis (sopan)" },
      ],
      note: "Polanya: [stem] + ã¾ã. Untuk negatif: [stem] + ã¾ãã. Bentuk lampau: [stem] + ã¾ãã.",
    },
    enemies: [
      {
        id: "verb-shadow",
        name: "Bayangan Kata Kerja",
        nameJp: "åè©",
        sprite: "â",
        hp: 28,
        attack: 8,
        color: "#e91e63",
        abilities: ["multi-attack", "crit"],
        critChance: 0.2,
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "ããã¹ã¾ãã artinya?",
        kana: "ãã¹ã¾ã",
        options: ["minum", "makan", "tidur", "berjalan"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "ãããã¾ãã artinya?",
        kana: "ããã¾ã",
        options: ["datang", "pergi", "lari", "duduk"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'membaca' (sopan):",
        kana: "ãã¿ã¾ã",
        answer: ["yomimasu"],
      },
      {
        type: "choice",
        prompt: "Negatif dari 'ãã¹ã¾ã' adalah?",
        options: ["ãã¹ã¾ãã", "ãã¹ã¾ãã", "ãã¹ãªãã¾ã", "ãã¹ã¾ããã"],
        answer: 0,
        hint: "Ganti ã¾ã â ã¾ãã",
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'mendengar' (sopan):",
        kana: "ããã¾ã",
        answer: ["kikimasu"],
      },
      {
        type: "choice",
        prompt: "ãã¿ã¾ãã artinya?",
        kana: "ã¿ã¾ã",
        options: ["melihat", "membaca", "menulis", "makan"],
        answer: 0,
      },
    ],
    reward: { xp: 130 },
  },

  // ===== STAGE 9: ADJECTIVES (i & na) =====
  {
    id: "n5-9",
    worldId: "n5",
    index: 9,
    chapter: 1,
    title: "Deskripsi & Sifat",
    subtitle: "Kata Sifat -i & -na",
    type: "battle",
    intro: [
      "**Taman Kastil Vassal**",
      "Di taman yang indah, kau bertemu seorang pelayan yang bingung.",
      "ãBunga ini... ããã? ããã? ããã? Saya bingung kata sifat mana yang dipakai!ÂÂ»",
      "Yuki: ãAda dua jenis kata sifat: -i (ãããããã) dan -na (ããããªãããããª). Pelajari!ÂÂ»",
    ],
    outro: [
      "Pelayan tersenyum. ãBunga ini ãããã§ãã­! Cantik ya!ã",
      "Yuki: ÂÂ«Sekarang kau bisa mendeskripsikan apapun!ÂÂ»",
      "**Stage 9 selesai! +140 XP, 60 koin**",
    ],
    lesson: {
      title: "Kata Sifat -i & -na",
      rows: [
        { kana: "ããã", romaji: "takai", meaning: "tinggi / mahal (-i)" },
        { kana: "ã²ãã", romaji: "hikui", meaning: "rendah (-i)" },
        { kana: "ãããã", romaji: "ookii", meaning: "besar (-i)" },
        { kana: "ã¡ããã", romaji: "chiisai", meaning: "kecil (-i)" },
        { kana: "ããã", romaji: "akai", meaning: "merah (-i)" },
        { kana: "ããã(ãª)", romaji: "kirei (na)", meaning: "cantik / bersih (-na)" },
        { kana: "ããã(ãª)", romaji: "shizuka (na)", meaning: "tenang (-na)" },
        { kana: "ããã(ãª)", romaji: "genki (na)", meaning: "sehat / energetik (-na)" },
      ],
      note: "Sifat -i: berakhiran ã, langsung pakai (ããã + ã§ã). Sifat -na: pakai 'na' sebelum kata benda (ããããª ãÂ»ã).",
    },
    enemies: [
      {
        id: "adjective-mist",
        name: "Kabut Sifat",
        nameJp: "å½¢å®¹è©",
        sprite: "ðÂ«",
        hp: 30,
        attack: 8,
        color: "#cfd8dc",
        abilities: ["poison", "regen", "counter"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "ããããã berarti?",
        kana: "ããã",
        options: ["rendah", "tinggi/mahal", "kecil", "merah"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "Mana yang merupakan kata sifat -na?",
        options: ["ããã", "ãããã", "ããã", "ããã"],
        answer: 2,
        hint: "Tidak berakhiran 'i'!",
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'merah':",
        kana: "ããã",
        answer: ["akai"],
      },
      {
        type: "choice",
        prompt: "Untuk mendeskripsikan buku yang cantik, kau bilang?",
        options: ["ããã ãÂ»ã", "ããããª ãÂ»ã", "ãããã® ãÂ»ã", "ãããã ãÂ»ã"],
        answer: 1,
        hint: "Sifat -na + na + kata benda",
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'sehat/energetik' (sifat -na):",
        kana: "ããã",
        answer: ["genki"],
      },
    ],
    reward: { xp: 140 },
  },

  // ===== STAGE 10: BOSS - LORD VASSAL =====
  {
    id: "n5-10",
    worldId: "n5",
    index: 10,
    chapter: 1,
    title: "Lord Vassal",
    subtitle: "Bos Akhir Bab N5",
    type: "boss",
    intro: [
      "**Tahta Kastil Vassal**",
      "Di aula tahta, sesosok pria berjanggut putih duduk di singgasana. **Lord Vassal**, penguasa kerajaan.",
      "ãPengelana dari Hajimari... Aku dengar kau membantu pendudukku. Tapi untuk kuasai kerajaanku, kau harus menguasaiku dulu dalam bahasa!ã",
      "Yuki: ÂÂ«Ini ujian akhir N5. Gabungkan semua yang kau pelajari - salam, kata ganti, desu, angka, hari, kanji, kata kerja, sifat!ÂÂ»",
      "Lord Vassal berdiri. ãPertarungan bahasa dimulai!ã",
      "**PERTARUNGAN AKHIR BAB N5**",
    ],
    outro: [
      "Lord Vassal tertawa lebar. ãHAHAHA! Kau menguasai dasar bahasa Jepang!ÂÂ»",
      "Ia menjabat tanganmu. ãSelamat, pahlawan. Kau pantas mendapat gelar ÂÂ«Pengelana DasarÂÂ».ÂÂ»",
      "Ia menyerahkan medali emas. Â«Dengan ini, kau lanjut ke Bab 2: Ujian Akademi!Â»",
      "Yuki: ÂÂ«Aku bangga padamu. Sekarang waktunya ujian resmi di Akademi!ÂÂ»",
      "**BAB 1 SELESAI! +800 XP, 300 koin, Badge: Pengelana Dasar, Item: Medali Vassal**",
      "**Bab 2 terbuka: Ujian Akademi (Stage 11-20)**",
    ],
    lesson: {
      title: "Ujian Akhir N5",
      rows: [
        { kana: "ãã¯ãã", romaji: "ohayou", meaning: "selamat pagi" },
        { kana: "ããã", romaji: "watashi", meaning: "saya" },
        { kana: "ã§ã", romaji: "desu", meaning: "adalah" },
        { kana: "ãã", romaji: "san", meaning: "3 (atau akhiran hormat)" },
        { kana: "ãã¹ã¾ã", romaji: "tabemasu", meaning: "makan" },
        { kana: "ããã", romaji: "takai", meaning: "tinggi/mahal" },
        { kana: "äºº", romaji: "hito", meaning: "orang" },
        { kana: "æ¥", romaji: "hi", meaning: "hari" },
      ],
      note: "Semua yang dipelajari di Bab N5 jadi fondasi N4 dan seterusnya. Selamat, Pengelana!",
    },
    enemies: [
      {
        id: "lord-vassal",
        name: "Lord Vassal",
        nameJp: "ã´ã¡ããµãÂ«å¿",
        sprite: "ð¤´",
        hp: 108,
        attack: 15,
        description: "Bos akhir N5. Penguasa Vassal Kingdom, ahli bahasa formal.",
        color: "#ff9800",
        abilities: ["enrage", "heal", "crit", "shield", "multi-attack", "counter"],
        critChance: 0.2,
      },
    ],
    questions: [
      // Comprehensive N5 review
      {
        type: "choice",
        prompt: "ããã¯ãããããã¾ãã dipakai kapan?",
        kana: "ãã¯ãããããã¾ã",
        options: ["pagi (formal)", "siang", "malam", "selamat tinggal"],
        answer: 0,
      },
      {
        type: "typing",
        prompt: "Romaji 'ããããã¡' (kami/kita):",
        kana: "ããããã¡",
        answer: ["watashitachi"],
      },
      {
        type: "choice",
        prompt: "ãããã¯ ãÂ»ã ã§ãã artinya?",
        kana: "ããã¯ ãÂ»ã ã§ã",
        options: ["Ini adalah buku", "Itu adalah buku", "Aku adalah buku", "Buku adalah ini"],
        answer: 0,
      },
      {
        type: "typing",
        prompt: "Romaji angka '7' (lebih umum):",
        kana: "ãªãª",
        answer: ["nana"],
      },
      {
        type: "choice",
        prompt: "Kanji 'äºº' dibaca saat artinya 'orang'?",
        kana: "äºº",
        options: ["hi", "hito", "tsuki", "hon"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "ãããããã³ã adalah hari?",
        kana: "ããããã³",
        options: ["Senin", "Rabu", "Jumat", "Minggu"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "Romaji 'ã®ã¿ã¾ã' (minum - sopan):",
        kana: "ã®ã¿ã¾ã",
        answer: ["nomimasu"],
      },
      {
        type: "choice",
        prompt: "ãããããª ã¯ãªã artinya?",
        kana: "ããããª ã¯ãª",
        options: ["Bunga yang cantik", "Bunga yang tinggi", "Bunga merah", "Bunga besar"],
        answer: 0,
      },
      {
        type: "typing",
        prompt: "Romaji 'ãã¿ã¾ãã' (maaf/permisi):",
        kana: "ãã¿ã¾ãã",
        answer: ["sumimasen"],
      },
      {
        type: "choice",
        prompt: "ãSelamat tinggalÂÂ» dalam bahasa Jepang?",
        options: ["ãããÂ«ã¡ã¯", "ãããã¨ã", "ããããªã", "ãã¿ã¾ãã"],
        answer: 2,
      },
    ],
    reward: { xp: 800, badge: "Pengelana Dasar", item: "Medali Vassal" },
  },

  // ===== STAGE 11: UJIAN DIMULAI - Kana dalam opsi =====
  {
    id: "n5-11",
    worldId: "n5",
    index: 11,
    chapter: 2,
    title: "Ujian Gerbang Akademi",
    subtitle: "Adaptasi: Kana mulai muncul di opsi",
    type: "lesson",
    intro: [
      "**Akademi Kerajaan Vassal - Pagi**",
      "Setelah menguasai dasar, kau diajak ke Akademi Kerajaan untuk ujian resmi.",
      "Penguji: ãSelamat datang. Ujian ini berbeda - mulai sekarang, opsi jawaban akan pakai huruf Jepang. Bukan romaji lagi.ã",
      "ãJangan khawatir, pelan-pelan. Kita mulai dari yang mudah.ã",
    ],
    outro: [
      "Penguji: ÂÂ«Bagus! Kau mulai terbiasa dengan kana di opsi. Lanjut!ÂÂ»",
      "**Stage 11 selesai! +120 XP**",
    ],
    lesson: {
      title: "Transisi ke Kana",
      rows: [
        { kana: "ããã", romaji: "watashi", meaning: "saya" },
        { kana: "ããªã", romaji: "anata", meaning: "kamu" },
        { kana: "ã¨ãã ã¡", romaji: "tomodachi", meaning: "teman" },
        { kana: "ãã£ãã", romaji: "gakkou", meaning: "sekolah" },
        { kana: "ãããã", romaji: "sensei", meaning: "guru" },
      ],
      note: "Ujian adaptif: opsi mulai pakai kana (ã²ãããª) bukan romaji. Latih membaca!",
    },
    enemies: [
      { id: "exam-proctor", name: "Pengawas Ujian", sprite: "ð", hp: 30, attack: 7, color: "#607d8b", abilities: ["time-pressure", "shield"] },
    ],
    questions: [
      { type: "choice", prompt: "ãããããã® ãã¿ã¯?", kana: "ããã", options: ["saya", "kamu", "teman", "guru"], answer: 0, hint: "kata ganti orang pertama" },
      { type: "choice", prompt: "Apa arti ãã£ãã?", kana: "ãã£ãã", options: ["sekolah", "rumah", "toko", "kuil"], answer: 0 },
      { type: "choice", prompt: "ãsenseiãã ãÂ«ãÂ»ããã§:", options: ["ãããã", "ãã£ãã", "ã¨ãã ã¡", "ããã"], answer: 0, hint: "guru dalam bahasa Jepang" },
      { type: "choice", prompt: "Teman = ?", options: ["ã¨ãã ã¡", "ãããã", "ããã", "ããªã"], answer: 0 },
      { type: "typing", prompt: "Ketik romaji untuk ãã£ãã:", kana: "ãã£ãã", answer: ["gakkou", "gakko"] },
      { type: "choice", prompt: "ããªãã® ãã¿ã¯?", kana: "ããªã", options: ["kamu", "saya", "dia", "kami"], answer: 0 },
    ],
    reward: { xp: 120 },
  },

  // ===== STAGE 12: Kana penuh di opsi =====
  {
    id: "n5-12",
    worldId: "n5",
    index: 12,
    chapter: 2,
    title: "Membaca Tanpa Romaji",
    subtitle: "Full kana di opsi jawaban",
    type: "battle",
    intro: [
      "**Ruang Ujian 1**",
      "Penguji: ãSekarang semua opsi pakai ã²ãããª. Tidak ada romaji lagi.ã",
      "ãKau harus bisa membaca huruf Jepang untuk menjawab. Fokus!ã",
    ],
    outro: ["Penguji: ÂÂ«Kau bisa baca kana tanpa romaji! Lanjut ke kanji!ÂÂ»", "**Stage 12 selesai! +140 XP**"],
    lesson: {
      title: "Kosakata Sehari-hari (Kana)",
      rows: [
        { kana: "ã¿ã", romaji: "mizu", meaning: "air" },
        { kana: "ãã¹ãã®", romaji: "tabemono", meaning: "makanan" },
        { kana: "ã®ã¿ãã®", romaji: "nomimono", meaning: "minuman" },
        { kana: "ãã", romaji: "asa", meaning: "pagi" },
        { kana: "ãã", romaji: "yoru", meaning: "malam" },
        { kana: "ã²ã", romaji: "hiru", meaning: "siang" },
      ],
      note: "Sekarang opsi jawaban full kana. Tidak ada bantuan romaji!",
    },
    enemies: [
      { id: "kana-reader", name: "Pembaca Kana", sprite: "ð", hp: 35, attack: 8, color: "#3f51b5", abilities: ["crit", "shield"] },
    ],
    questions: [
      { type: "choice", prompt: "ãã¿ããã® ãã¿ã¯?", kana: "ã¿ã", options: ["ã¿ã", "ãã¹ãã®", "ãã", "ãã"], answer: 0, hint: "yang diminum" },
      { type: "choice", prompt: "Apa arti ãã¹ãã®?", kana: "ãã¹ãã®", options: ["ã¿ã", "ãã¹ãã®", "ã®ã", "ãã"], answer: 1, hint: "yang dimakan" },
      { type: "choice", prompt: "ãmalamãã¯ ãÂ«ãÂ»ããã§?", options: ["ãã", "ã²ã", "ãã", "ã¿ã"], answer: 2 },
      { type: "choice", prompt: "ãsiangãã¯?", options: ["ãã", "ã²ã", "ãã", "ã¿ã"], answer: 1 },
      { type: "typing", prompt: "ã­ãã¸ã§ ããã¦ (ketik romaji): ã®ã¿ãã®", kana: "ã®ã¿ãã®", answer: ["nomimono"] },
      { type: "choice", prompt: "ãpagiãã¯ ãÂ«ãÂ»ããã§?", options: ["ãã", "ã²ã", "ãã", "ã¿ã"], answer: 0 },
    ],
    reward: { xp: 140 },
  },

  // ===== STAGE 13: Kanji mulai muncul =====
  {
    id: "n5-13",
    worldId: "n5",
    index: 13,
    chapter: 2,
    title: "Kanji Pertama",
    subtitle: "Kanji dasar di soal",
    type: "battle",
    intro: [
      "**Ruang Ujian 2**",
      "Penguji: ãSekarang kanji mulai muncul. Tapi jangan takut - itu kanji yang sudah kau pelajari!ã",
      "ãäºº, æ¥, æ, çÂ«, æ°´, æ¨, é - semua ini sudah kau kenal.ã",
    ],
    outro: ["Penguji: ÂÂ«Kanji pertama berhasil! Lanjut ke tingkat lebih sulit!ÂÂ»", "**Stage 13 selesai! +160 XP**"],
    lesson: undefined,
    enemies: [
      { id: "kanji-tester", name: "Penguji Kanji", sprite: "ð¤", hp: 40, attack: 9, color: "#e91e63", abilities: ["enrage", "crit"] },
    ],
    questions: [
      { type: "choice", prompt: "ãäººãã® ãã¿ããã¯?", kana: "äºº", options: ["ã²ã¨", "ã²", "ãÂ«ã¡", "ã¤ã"], answer: 0, hint: "orang" },
      { type: "choice", prompt: "ãæ¥ãã® ãã¿ã¯?", kana: "æ¥", options: ["hari/matahari", "bulan", "api", "air"], answer: 0 },
      { type: "choice", prompt: "ãæãã® ãã¿ã¯?", kana: "æ", options: ["hari", "bulan", "tahun", "jam"], answer: 1 },
      { type: "choice", prompt: "ãçÂ«ãã® ãã¿ã¯?", kana: "çÂ«", options: ["air", "tanah", "api", "angin"], answer: 2 },
      { type: "choice", prompt: "ãæ°´ãã® ãã¿ã¯?", kana: "æ°´", options: ["ã¿ã", "ã²", "ã¤ã", "ã²ã¨"], answer: 0, hint: "air" },
      { type: "typing", prompt: "ã­ãã¸ã§: äºº (orang)", kana: "äºº", answer: ["hito", "nin"] },
    ],
    reward: { xp: 160 },
  },

  // ===== STAGE 14: Kalimat pendek =====
  {
    id: "n5-14",
    worldId: "n5",
    index: 14,
    chapter: 2,
    title: "Kalimat Sederhana",
    subtitle: "Pahami kalimat pendek",
    type: "battle",
    intro: [
      "**Ruang Ujian 3**",
      "Penguji: ãSekarang kalimat! Bukan cuma kata tunggal.ã",
      "ããããã¯ ãããã ã§ã - kalimat seperti ini. Pahami artinya!ã",
    ],
    outro: ["Penguji: ÂÂ«Kau bisa baca kalimat! Hebat!ÂÂ»", "**Stage 14 selesai! +180 XP**"],
    lesson: {
      title: "Kalimat Dasar",
      rows: [
        { kana: "ãããã¯ ãããã ã§ã", romaji: "watashi wa gakusei desu", meaning: "saya adalah murid" },
        { kana: "ããã¯ ãÂ»ã ã§ã", romaji: "kore wa hon desu", meaning: "ini adalah buku" },
        { kana: "ããã¯ ããã´ã¤ ã§ã", romaji: "sore wa enpitsu desu", meaning: "itu adalah pensil" },
        { kana: "ããããÂ« ãã£ãã ã ããã¾ã", romaji: "asoko ni gakkou ga arimasu", meaning: "di sana ada sekolah" },
      ],
      note: "Kalimat dasar: A ã¯ B ã§ã (A adalah B). ãã = ini, ãã = itu (dekat lawan), ãã = itu (jauh).",
    },
    enemies: [
      { id: "sentence-spirit", name: "Roh Kalimat", sprite: "ð¬", hp: 45, attack: 10, color: "#7e57c2", abilities: ["poison", "multi-attack"] },
    ],
    questions: [
      { type: "choice", prompt: "ããããã¯ ãããã ã§ããã® ãã¿ã¯?", kana: "ãããã¯ ãããã ã§ã", options: ["saya murid", "kamu guru", "dia teman", "ini buku"], answer: 0 },
      { type: "choice", prompt: "ãããã¯ ãÂ»ã ã§ããã® ãã¿ã¯?", kana: "ããã¯ ãÂ»ã ã§ã", options: ["ini buku", "itu pensil", "saya murid", "ada sekolah"], answer: 0 },
      { type: "choice", prompt: "ããããã® ãã¿ã¯?", kana: "ãã", options: ["ini (dekat saya)", "itu (dekat lawan)", "itu (jauh)", "mana"], answer: 1 },
      { type: "choice", prompt: "ãããããÂ« ãã£ãã ã ããã¾ãã artinya?", kana: "ããããÂ« ãã£ãã ã ããã¾ã", options: ["di sana ada sekolah", "di sini ada buku", "saya ke sekolah", "sekolah jauh"], answer: 0 },
      { type: "typing", prompt: "ã­ãã¸ã§: ããã¯ ãÂ»ã ã§ã", kana: "ããã¯ ãÂ»ã ã§ã", answer: ["kore wa hon desu"] },
    ],
    reward: { xp: 180 },
  },

  // ===== STAGE 15: Mini-boss Ujian Tengah =====
  {
    id: "n5-15",
    worldId: "n5",
    index: 15,
    chapter: 2,
    title: "Ujian Tengah Semester",
    subtitle: "Mini-Boss: Professor Vassal",
    type: "mini-boss",
    intro: [
      "**Aula Besar Akademi**",
      "**Professor Vassal** duduk di meja ujian. ãSelamat, kau sampai ujian tengah! Tapi sekarang, aku yang menguji.ã",
      "ãSemua soal pakai huruf Jepang. Tidak ada romaji. Siap?ã",
    ],
    outro: [
      "Professor Vassal: ÂÂ«Kau lulus ujian tengah! Setengah jalan lagi!ÂÂ»",
      "**Stage 15 selesai! +250 XP, Badge: Lulus Ujian Tengah**",
    ],
    lesson: undefined,
    enemies: [
      { id: "professor-vassal", name: "Professor Vassal", sprite: "ð", hp: 60, attack: 10, color: "#ff9800", abilities: ["enrage", "shield", "counter", "time-pressure"] },
    ],
    questions: [
      { type: "choice", prompt: "ãããããã® ãã¿ã¯?", kana: "ããã", options: ["saya", "kamu", "dia", "kami"], answer: 0 },
      { type: "choice", prompt: "ãã²ã¨ãã ãããã§:", options: ["äºº", "æ¥", "æ", "çÂ«"], answer: 0 },
      { type: "choice", prompt: "ããããã¯ ãããã ã§ããã® ãã¿ã¯?", kana: "ãããã¯ ãããã ã§ã", options: ["saya murid", "kamu guru", "ini buku", "dia teman"], answer: 0 },
      { type: "choice", prompt: "ãã¿ããã® ãã¿ã¯?", kana: "ã¿ã", options: ["ã¿ã", "ã²", "ã¤ã", "ã²ã¨"], answer: 0 },
      { type: "typing", prompt: "ã­ãã¸ã§: ãã¹ãã®", kana: "ãã¹ãã®", answer: ["tabemono"] },
      { type: "choice", prompt: "ãæ¥ãã® ãã¿ããã¯? (bacaan)", kana: "æ¥", options: ["ã²/ãÂ«ã¡", "ã¤ã", "ã²ã¨", "ã¿ã"], answer: 0 },
      { type: "choice", prompt: "ããããã® ãã¿ã¯?", kana: "ãã", options: ["itu (dekat lawan)", "ini", "itu (jauh)", "mana"], answer: 0 },
      { type: "typing", prompt: "ã­ãã¸ã§: ãã (malam)", kana: "ãã", answer: ["yoru"] },
    ],
    reward: { xp: 250, badge: "Lulus Ujian Tengah" },
  },

  // ===== STAGE 16: Kosakata rumah =====
  {
    id: "n5-16",
    worldId: "n5",
    index: 16,
    chapter: 2,
    title: "Kosakata Rumah",
    subtitle: "Full kana + kanji",
    type: "battle",
    intro: [
      "**Ruang Ujian 4**",
      "Penguji: ãTema: rumah & kehidupan sehari-hari. Semua dalam bahasa Jepang!ã",
    ],
    outro: ["Penguji: ÂÂ«Kosakata rumah terkuasai!ÂÂ»", "**Stage 16 selesai! +200 XP**"],
    lesson: {
      title: "Kosakata Rumah",
      rows: [
        { kana: "ãã", romaji: "ie", meaning: "rumah" },
        { kana: "ã¸ã", romaji: "heya", meaning: "kamar" },
        { kana: "ãã¢", romaji: "doa", meaning: "pintu" },
        { kana: "ã¾ã©", romaji: "mado", meaning: "jendela" },
        { kana: "ããã", romaji: "beddo", meaning: "kasur" },
        { kana: "ãã¼ããÂ«", romaji: "teeburu", meaning: "meja" },
      ],
      note: "Kata serapan pakai Katakana: ãã¢ (doa), ããã (beddo), ãã¼ããÂ« (teeburu).",
    },
    enemies: [
      { id: "home-ghost", name: "Hantu Rumah", sprite: "ð ", hp: 50, attack: 11, color: "#795548", abilities: ["regen", "shield"] },
    ],
    questions: [
      { type: "choice", prompt: "ããããã® ãã¿ã¯?", kana: "ãã", options: ["ãã", "ã¸ã", "ã¾ã©", "ãã¢"], answer: 0, hint: "tempat tinggal" },
      { type: "choice", prompt: "ãjendelaãã¯ ãÂ«ãÂ»ããã§?", options: ["ã¾ã©", "ãã¢", "ããã", "ã¸ã"], answer: 0 },
      { type: "choice", prompt: "ãããããã® ãã¿ã¯?", kana: "ããã", options: ["kasur", "meja", "pintu", "jendela"], answer: 0 },
      { type: "typing", prompt: "ã­ãã¸ã§: ã¸ã (kamar)", kana: "ã¸ã", answer: ["heya"] },
      { type: "choice", prompt: "ããã¼ããÂ«ãã¯ ãªãÂ«?", kana: "ãã¼ããÂ«", options: ["meja", "kursi", "pintu", "jendela"], answer: 0 },
      { type: "typing", prompt: "ã­ãã¸ã§: ã¾ã©", kana: "ã¾ã©", answer: ["mado"] },
    ],
    reward: { xp: 200 },
  },

  // ===== STAGE 17: Kosakata makanan =====
  {
    id: "n5-17",
    worldId: "n5",
    index: 17,
    chapter: 2,
    title: "Kosakata Makanan",
    subtitle: "Makanan & minuman",
    type: "battle",
    intro: [
      "**Ruang Ujian 5**",
      "Penguji: ãTema: makanan. Semua dalam ã²ãããª ã¨ ãÂ«ã¿ãÂ«ã!ã",
    ],
    outro: ["Penguji: ÂÂ«Lapar juga bisa belajar!ÂÂ»", "**Stage 17 selesai! +220 XP**"],
    lesson: {
      title: "Kosakata Makanan",
      rows: [
        { kana: "ãã¯ã", romaji: "gohan", meaning: "nasi/makan" },
        { kana: "ãã³", romaji: "pan", meaning: "roti" },
        { kana: "ãÂ«ã", romaji: "niku", meaning: "daging" },
        { kana: "ããã", romaji: "yasai", meaning: "sayuran" },
        { kana: "ãã ãã®", romaji: "kudamono", meaning: "buah" },
        { kana: "ã³ã¼ãã¼", romaji: "koohii", meaning: "kopi" },
        { kana: "ãã¡ã", romaji: "ocha", meaning: "teh" },
      ],
      note: "Kata serapan: ãã³ (pan=roti), ã³ã¼ãã¼ (kopi). Kata asli: ãã¯ã (nasi), ãÂ«ã (daging).",
    },
    enemies: [
      { id: "food-critic", name: "Kritikus Kuliner", sprite: "ð£", hp: 55, attack: 12, color: "#ff5722", abilities: ["poison", "crit"] },
    ],
    questions: [
      { type: "choice", prompt: "ããã¯ããã® ãã¿ã¯?", kana: "ãã¯ã", options: ["nasi/makan", "roti", "daging", "sayur"], answer: 0 },
      { type: "choice", prompt: "ããã³ãã® ãã¿ã¯?", kana: "ãã³", options: ["roti", "nasi", "teh", "kopi"], answer: 0 },
      { type: "choice", prompt: "ãbuahãã¯ ãÂ«ãÂ»ããã§?", options: ["ãã ãã®", "ããã", "ãÂ«ã", "ãã³"], answer: 0 },
      { type: "choice", prompt: "ãã³ã¼ãã¼ãã® ãã¿ã¯?", kana: "ã³ã¼ãã¼", options: ["kopi", "teh", "susu", "jus"], answer: 0 },
      { type: "typing", prompt: "ã­ãã¸ã§: ãã¡ã (teh)", kana: "ãã¡ã", answer: ["ocha"] },
      { type: "choice", prompt: "ãããããã® ãã¿ã¯?", kana: "ããã", options: ["sayuran", "buah", "daging", "nasi"], answer: 0 },
    ],
    reward: { xp: 220 },
  },

  // ===== STAGE 18: Kosakata transport =====
  {
    id: "n5-18",
    worldId: "n5",
    index: 18,
    chapter: 2,
    title: "Kosakata Transportasi",
    subtitle: "Transportasi & arah",
    type: "battle",
    intro: [
      "**Ruang Ujian 6**",
      "Penguji: ãTema: transportasi. Banyak kata serapan pakai Katakana!ã",
    ],
    outro: ["Penguji: ÂÂ«Sekarang kau bisa navigasi kota!ÂÂ»", "**Stage 18 selesai! +240 XP**"],
    lesson: {
      title: "Kosakata Transportasi",
      rows: [
        { kana: "ã§ããã", romaji: "densha", meaning: "kereta listrik" },
        { kana: "ãã¹", romaji: "basu", meaning: "bus" },
        { kana: "ã¿ã¯ã·ã¼", romaji: "takushii", meaning: "taksi" },
        { kana: "ããã¾", romaji: "kuruma", meaning: "mobil" },
        { kana: "ã¿ã", romaji: "migi", meaning: "kanan" },
        { kana: "ã²ã ã", romaji: "hidari", meaning: "kiri" },
        { kana: "ã¾ã£ãã", romaji: "massugu", meaning: "lurus" },
      ],
      note: "Transportasi: ã§ããã (kereta), ãã¹ (bus), ã¿ã¯ã·ã¼ (taksi). Arah: ã¿ã (kanan), ã²ã ã (kiri), ã¾ã£ãã (lurus).",
    },
    enemies: [
      { id: "traffic-control", name: "Pengatur Lalu Lintas", sprite: "ð¦", hp: 60, attack: 13, color: "#4caf50", abilities: ["time-pressure", "multi-attack"] },
    ],
    questions: [
      { type: "choice", prompt: "ãã§ããããã® ãã¿ã¯?", kana: "ã§ããã", options: ["kereta", "bus", "taksi", "mobil"], answer: 0 },
      { type: "choice", prompt: "ããã¹ãã® ãã¿ã¯?", kana: "ãã¹", options: ["bus", "kereta", "mobil", "taksi"], answer: 0 },
      { type: "choice", prompt: "ãkananãã¯ ãÂ«ãÂ»ããã§?", options: ["ã¿ã", "ã²ã ã", "ã¾ã£ãã", "ããã¾"], answer: 0 },
      { type: "choice", prompt: "ãã²ã ããã® ãã¿ã¯?", kana: "ã²ã ã", options: ["kiri", "kanan", "lurus", "mundur"], answer: 0 },
      { type: "typing", prompt: "ã­ãã¸ã§: ã¾ã£ãã (lurus)", kana: "ã¾ã£ãã", answer: ["massugu", "massugu"] },
      { type: "choice", prompt: "ãã¿ã¯ã·ã¼ãã® ãã¿ã¯?", kana: "ã¿ã¯ã·ã¼", options: ["taksi", "bus", "kereta", "mobil"], answer: 0 },
    ],
    reward: { xp: 240 },
  },

  // ===== STAGE 19: Ujian pra-final =====
  {
    id: "n5-19",
    worldId: "n5",
    index: 19,
    chapter: 2,
    title: "Persiapan Ujian Akhir",
    subtitle: "Review menyeluruh - full Japanese",
    type: "battle",
    intro: [
      "**Ruang Ujian 7 - Terakhir sebelum Final**",
      "Penguji: ãIni review semua materi. Soal campuran: kana, kanji, kalimat, kosakata. Semua dalam bahasa Jepang!ã",
      "ãLulus ini, dan kau siap ujian akhirï¼ã",
    ],
    outro: ["Penguji: ÂÂ«Kau siap! Ujian akhir menunggu!ÂÂ»", "**Stage 19 selesai! +280 XP**"],
    lesson: undefined,
    enemies: [
      { id: "review-master", name: "Master Review", sprite: "ð", hp: 70, attack: 14, color: "#7c4dff", abilities: ["enrage", "shield", "counter", "crit"] },
    ],
    questions: [
      { type: "choice", prompt: "ãããããã® ãã¿ã¯?", kana: "ããã", options: ["saya", "kamu", "dia", "teman"], answer: 0 },
      { type: "choice", prompt: "ãã²ã¨ãã ãããã§:", options: ["äºº", "æ¥", "æ", "çÂ«"], answer: 0 },
      { type: "choice", prompt: "ããã¯ããã® ãã¿ã¯?", kana: "ãã¯ã", options: ["nasi/makan", "roti", "air", "sayur"], answer: 0 },
      { type: "choice", prompt: "ãã§ããããã® ãã¿ã¯?", kana: "ã§ããã", options: ["kereta", "bus", "mobil", "taksi"], answer: 0 },
      { type: "choice", prompt: "ãã¿ããã® ãã¿ã¯?", kana: "ã¿ã", options: ["kanan", "kiri", "lurus", "mundur"], answer: 0 },
      { type: "typing", prompt: "ã­ãã¸ã§: ãã¹ãã® (makanan)", kana: "ãã¹ãã®", answer: ["tabemono"] },
      { type: "choice", prompt: "ããããã¯ ãããã ã§ããã® ãã¿ã¯?", kana: "ãããã¯ ãããã ã§ã", options: ["saya murid", "kamu guru", "ini buku", "dia teman"], answer: 0 },
      { type: "choice", prompt: "ããã³ãã® ãã¿ã¯?", kana: "ãã³", options: ["roti", "nasi", "teh", "kopi"], answer: 0 },
    ],
    reward: { xp: 280 },
  },

  // ===== STAGE 20: UJIAN AKHIR - BOSS =====
  {
    id: "n5-20",
    worldId: "n5",
    index: 20,
    chapter: 2,
    title: "Ujian Akhir Vassal",
    subtitle: "Bos Akhir: Ujian Tingkat Dasar",
    type: "boss",
    intro: [
      "**Aula Utama Akademi - Ujian Akhir**",
      "Di aula utama, dewan penguji menunggu. **Chancellor Vassal** berdiri di tengah.",
      "ãPengelana, ini ujian akhir tingkat Dasar. Lulus, dan kau naik ke tingkat Madya Bawah - Minato Port!ã",
      "ãSemua soal dalam bahasa Jepang penuh. Tidak ada romaji. Tunjukkan kemampuanmu!ã",
      "**UJIAN AKHIR TINGKAT DASAR DIMULAI**",
    ],
    outro: [
      "Chancellor Vassal: ÂÂ«Kau lulus dengan sempurna! Gelar ÂÂ«Sarjana DasarÂÂ» adalah milikmu!ÂÂ»",
      "Ia menyerahkan sertifikat emas. ÂÂ«Lanjut ke Minato Port - tingkat Madya Bawah menunggu!ÂÂ»",
      "**UJIAN AKHIR DASAR SELESAI! +1000 XP, 500 koin, Badge: Sarjana Dasar, Item: Sertifikat Vassal**",
      "**Bab 2 terbuka: Ujian Akademi (Stage 11-20)**",
    ],
    lesson: undefined,
    enemies: [
      { id: "chancellor-vassal", name: "Chancellor Vassal", sprite: "ð©", hp: 150, attack: 15, color: "#ff9800", abilities: ["enrage", "heal", "crit", "shield", "multi-attack", "counter", "poison", "time-pressure"] },
    ],
    questions: [
      // Full Japanese exam - comprehensive
      { type: "choice", prompt: "ãããããã® ãã¿ã¯?", kana: "ããã", options: ["saya", "kamu", "dia", "kami"], answer: 0 },
      { type: "choice", prompt: "ãäººãã® ãã¿ããã¯?", kana: "äºº", options: ["ã²ã¨", "ã²", "ãÂ«ã¡", "ã¤ã"], answer: 0 },
      { type: "choice", prompt: "ããããã¯ ãããã ã§ããã® ãã¿ã¯?", kana: "ãããã¯ ãããã ã§ã", options: ["saya murid", "kamu guru", "ini buku", "dia teman"], answer: 0 },
      { type: "choice", prompt: "ããã¯ããã® ãã¿ã¯?", kana: "ãã¯ã", options: ["nasi/makan", "roti", "air", "daging"], answer: 0 },
      { type: "choice", prompt: "ãã§ããããã® ãã¿ã¯?", kana: "ã§ããã", options: ["kereta", "bus", "taksi", "mobil"], answer: 0 },
      { type: "typing", prompt: "ã­ãã¸ã§: ãã¹ãã® (makanan)", kana: "ãã¹ãã®", answer: ["tabemono"] },
      { type: "choice", prompt: "ãã¿ããã® ãã¿ã¯?", kana: "ã¿ã", options: ["kanan", "kiri", "lurus", "mundur"], answer: 0 },
      { type: "choice", prompt: "ããã³ãã® ãã¿ã¯?", kana: "ãã³", options: ["roti", "nasi", "teh", "kopi"], answer: 0 },
      { type: "choice", prompt: "ãããã¯ ãÂ»ã ã§ããã® ãã¿ã¯?", kana: "ããã¯ ãÂ»ã ã§ã", options: ["ini buku", "itu pensil", "saya murid", "ada sekolah"], answer: 0 },
      { type: "choice", prompt: "ãæ¥ãã® ãã¿ã¯?", kana: "æ¥", options: ["hari/matahari", "bulan", "api", "air"], answer: 0 },
      { type: "typing", prompt: "ã­ãã¸ã§: ãã (malam)", kana: "ãã", answer: ["yoru"] },
      { type: "choice", prompt: "ãã³ã¼ãã¼ãã® ãã¿ã¯?", kana: "ã³ã¼ãã¼", options: ["kopi", "teh", "susu", "jus"], answer: 0 },
    ],
    reward: { xp: 1000, badge: "Sarjana Dasar", item: "Sertifikat Vassal" },
  },
];
