import type { Stage } from "./types";

// ===== VASSAL KINGDOM - CHAPTER 1: Tingkat Dasar =====
// 10 stages covering: greetings, particles, basic grammar, first kanji, common vocab.
// Story: Player arrives at Vassal Kingdom after defeating Shadow King.
// The kingdom's market is in chaos - merchants can't speak properly.
// Player must restore communication by learning N5 Japanese.

export const N5_STAGES: Stage[] = [
  // ===== STAGE 1: GREETINGS =====
  {
    id: "n5-1",
    worldId: "n5",
    index: 1,
    chapter: 1,
    title: "Tiba di Vassal Kingdom",
    subtitle: "Salam & Percakapan Dasar",
    type: "lesson",
    intro: [
      "**Gerbang Vassal Kingdom - Pagi**",
      "Setelah perjalanan panjang dari desa Hajimari, kau tiba di gerbang besar Kerajaan Vassal.",
      "Penjaga gerbang menyapa: 「おはようございます! Selamat pagi, pengelana!」",
      "Yuki (yang ikut): 「Di sini orang berbicara dengan kalimat utuh. Kau harus belajar salam dasar.」",
      "「Ini fondasi semua percakapan N5 - salam, terima kasih, permohonan maaf.」",
    ],
    outro: [
      "Penjaga tersenyum. 「おはようございます! Silakan masuk. Semoga harimu menyenangkan!」",
      "Yuki: 「Sekarang kau bisa menyapa siapa saja! Tapi pasar sedang kacau...」",
      "**Stage 1 selesai! +70 XP, 25 koin**",
    ],
    lesson: {
      title: "Salam & Percakapan Dasar",
      rows: [
        { kana: "おはよう", romaji: "ohayou", meaning: "selamat pagi (santai)" },
        { kana: "おはようございます", romaji: "ohayou gozaimasu", meaning: "selamat pagi (formal)" },
        { kana: "こんにちは", romaji: "konnichiwa", meaning: "halo / selamat siang" },
        { kana: "こんばんは", romaji: "konbanwa", meaning: "selamat malam" },
        { kana: "さようなら", romaji: "sayounara", meaning: "selamat tinggal" },
        { kana: "ありがとう", romaji: "arigatou", meaning: "terima kasih" },
        { kana: "すみません", romaji: "sumimasen", meaning: "maaf / permisi" },
        { kana: "はじめまして", romaji: "hajimemashite", meaning: "senang berkenalan" },
      ],
      note: "💡 PENJELASAN: 'ohayou' = pagi (santai, untuk teman). 'ohayou gozaimasu' = pagi (sopan, untuk orang tua/atasan). 'konnichiwa' = halo (siang-sore). 'sumimasen' = maaf ATAU permisi ATAU minta perhatian (1 kata banyak arti!). 'arigatou' = terima kasih (tambah 'gozaimasu' untuk sopan).",
    },
    enemies: [
      {
        id: "confused-merchant",
        name: "Pedagang Bingung",
        nameJp: "商人",
        sprite: "🧑‍🌾",
        hp: 12,
        attack: 3,
        description: "Tidak bisa menyapa dengan benar.",
        color: "#8d6e63",
        abilities: ["regen"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Apa arti 'おはようございます'?",
        kana: "おはようございます",
        options: ["selamat pagi (formal)", "selamat malam", "selamat tinggal", "terima kasih"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "'こんにちは' digunakan kapan?",
        kana: "こんにちは",
        options: ["pagi hari", "siang/sore", "malam hari", "selalu"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'terima kasih':",
        kana: "ありがとう",
        answer: ["arigatou", "arigato"],
      },
      {
        type: "choice",
        prompt: "Saat meminta perhatian seseorang, kau bilang?",
        options: ["ありがとう", "すみません", "さようなら", "こんにちは"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'senang berkenalan':",
        kana: "はじめまして",
        answer: ["hajimemashite"],
      },
    ],
    reward: { xp: 70 },
  },

  // ===== STAGE 2: PRONOUNS =====
  {
    id: "n5-2",
    worldId: "n5",
    index: 2,
    chapter: 1,
    title: "Siapa Kau? Siapa Aku?",
    subtitle: "Kata Ganti Orang",
    type: "battle",
    intro: [
      "**Alun-alun Vassal Kingdom**",
      "Di alun-alun, kau melihat seorang anak kecil menangis. 「あなたは... あなたは...」",
      "Ia tidak bisa menyebut nama orang. 「Aku tidak tahu kata ganti!」",
      "Yuki: 「Kata ganti orang penting untuk percakapan. わたし (saya), あなた (kamu), かれ (dia laki-laki), かのじょ (dia perempuan).」",
    ],
    outro: [
      "Anak itu tersenyum. 「わたしは トモ です! Nama saya Tomo! Terima kasih, pengelana!」",
      "Yuki: 「Bagus! Sekarang kau bisa memperkenalkan diri.」",
      "**Stage 2 selesai! +80 XP, 30 koin**",
    ],
    lesson: {
      title: "Kata Ganti Orang (Pronouns)",
      rows: [
        { kana: "わたし", romaji: "watashi", meaning: "saya (umum)" },
        { kana: "ぼく", romaji: "boku", meaning: "saya (laki-laki, santai)" },
        { kana: "おれ", romaji: "ore", meaning: "saya (laki-laki, kasual)" },
        { kana: "あなた", romaji: "anata", meaning: "kamu" },
        { kana: "かれ", romaji: "kare", meaning: "dia (laki-laki) / pacar" },
        { kana: "かのじょ", romaji: "kanojo", meaning: "dia (perempuan) / pacar" },
        { kana: "わたしたち", romaji: "watashitachi", meaning: "kami / kita" },
      ],
      note: "'watashi' paling aman dipakai semua orang. 'boku' & 'ore' untuk laki-laki. 'anata' jarang dipakai - lebih baik sebut nama orangnya!",
    },
    enemies: [
      {
        id: "name-thief",
        name: "Pencuri Nama",
        nameJp: "名前泥棒",
        sprite: "🎭",
        hp: 15,
        attack: 4,
        color: "#9c27b0",
        abilities: ["multi-attack", "poison"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Apa arti 'わたし'?",
        kana: "わたし",
        options: ["kamu", "saya", "dia", "kami"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "Kata ganti 'kamu' adalah?",
        options: ["わたし", "あなた", "かれ", "わたしたち"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'dia (perempuan)':",
        kana: "かのじょ",
        answer: ["kanojo"],
      },
      {
        type: "choice",
        prompt: "'ぼく' (boku) biasanya dipakai oleh?",
        options: ["perempuan saja", "laki-laki", "anak-anak saja", "orang tua"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'kami / kita':",
        kana: "わたしたち",
        answer: ["watashitachi"],
      },
    ],
    reward: { xp: 80 },
  },

  // ===== STAGE 3: DESU (TO BE) =====
  {
    id: "n5-3",
    worldId: "n5",
    index: 3,
    chapter: 1,
    title: "Adalah, Adalah, Adalah",
    subtitle: "Polite Copula: です (desu)",
    type: "battle",
    intro: [
      "**Toko Roti Vassal**",
      "Kau masuk ke toko roti. Penjual: 「これは パン です!」",
      "Tapi aneh - semua barang ditandai sebagai 'pan' (roti) meski bukan roti!",
      "Yuki: 「です (desu) berarti 'adalah' - kata penghubung kalimat. Tapi salah dipakai, semua jadi roti!」",
      "「Pelajari pola: A は B です (A adalah B).」",
    ],
    outro: [
      "Toko roti kembali normal. Penjual: 「これは ケーキ です!」",
      "Yuki: 「Sekarang kau bisa membuat kalimat sederhana!」",
      "**Stage 3 selesai! +90 XP, 35 koin**",
    ],
    lesson: {
      title: "Polite Copula です (desu)",
      rows: [
        { kana: "です", romaji: "desu", meaning: "adalah (formal, positif)" },
        { kana: "じゃないです", romaji: "ja nai desu", meaning: "bukan (formal, negatif)" },
        { kana: "は", romaji: "wa", meaning: "partikel topik (dibaca 'wa')" },
        { kana: "も", romaji: "mo", meaning: "juga" },
      ],
      note: "Pola dasar: A は B です = A adalah B. 'は' ditulis 'ha' tapi dibaca 'wa' sebagai partikel topik!",
    },
    enemies: [
      {
        id: "is-bug",
        name: "Bug Adalah",
        nameJp: "ですバグ",
        sprite: "🐛",
        hp: 18,
        attack: 4,
        color: "#76ff03",
        abilities: ["multi-attack", "crit"],
        critChance: 0.15,
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "「これは パン です」 artinya?",
        kana: "これは パン です",
        options: ["Ini adalah roti", "Itu adalah roti", "Aku adalah roti", "Roti adalah ini"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "Partikel 'は' dibaca sebagai?",
        options: ["ha", "wa", "ba", "pa"],
        answer: 1,
        hint: "Pengecualian partikel topik!",
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'adalah' (formal):",
        kana: "です",
        answer: ["desu"],
      },
      {
        type: "choice",
        prompt: "「わたしは がくせい です」 artinya?",
        kana: "わたしは がくせい です",
        options: ["Saya adalah murid", "Kamu adalah murid", "Dia adalah murid", "Murid adalah saya"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "「これも パン です」 - 'も' berarti?",
        options: ["adalah", "bukan", "juga", "atau"],
        answer: 2,
      },
    ],
    reward: { xp: 90 },
  },

  // ===== STAGE 4: NUMBERS 1-10 =====
  {
    id: "n5-4",
    worldId: "n5",
    index: 4,
    chapter: 1,
    title: "Menghitung Harta",
    subtitle: "Angka 1-10",
    type: "battle",
    intro: [
      "**Pasar Vassal - Sibuk**",
      "Pasar sedang kacau! Pedagang tidak bisa menyebut harga.",
      "「これ... いくら?」 (Ini berapa?) 「Saya lupa angka!」",
      "Yuki: 「Belajar 1-10 dulu. Penting untuk transaksi!」",
    ],
    outro: [
      "Pasar kembali ramai. Pedagang berseru: 「これ は さんびゃくえん です! 300 yen!」",
      "Yuki: 「Bagus! Sekarang bisa bertransaksi.」",
      "**Stage 4 selesai! +100 XP, 40 koin**",
    ],
    lesson: {
      title: "Angka 1-10",
      rows: [
        { kana: "いち", romaji: "ichi", meaning: "1" },
        { kana: "に", romaji: "ni", meaning: "2" },
        { kana: "さん", romaji: "san", meaning: "3" },
        { kana: "し/よん", romaji: "shi/yon", meaning: "4 (yon lebih umum)" },
        { kana: "ご", romaji: "go", meaning: "5" },
        { kana: "ろく", romaji: "roku", meaning: "6" },
        { kana: "しち/なな", romaji: "shichi/nana", meaning: "7 (nana lebih umum)" },
        { kana: "はち", romaji: "hachi", meaning: "8" },
        { kana: "きゅう/く", romaji: "kyuu/ku", meaning: "9" },
        { kana: "じゅう", romaji: "juu", meaning: "10" },
      ],
      note: "4 (shi) & 7 (shichi) sering dihindari karena 'shi' juga berarti 'mati'. Pakai 'yon' & 'nana' lebih aman!",
    },
    enemies: [
      {
        id: "number-ghost",
        name: "Hantu Angka",
        nameJp: "数字",
        sprite: "🔢",
        hp: 20,
        attack: 6,
        color: "#ff9800",
        abilities: ["poison", "time-pressure"],
      },
    ],
    questions: [
      {
        type: "typing",
        prompt: "Romaji untuk '1':",
        kana: "いち",
        answer: ["ichi"],
      },
      {
        type: "typing",
        prompt: "Romaji untuk '3':",
        kana: "さん",
        answer: ["san"],
      },
      {
        type: "choice",
        prompt: "Angka '4' biasanya dibaca (lebih umum)?",
        options: ["shi", "yon", "suu", "yo"],
        answer: 1,
        hint: "'shi' juga berarti 'mati', jadi dihindari",
      },
      {
        type: "typing",
        prompt: "Romaji untuk '5':",
        kana: "ご",
        answer: ["go"],
      },
      {
        type: "typing",
        prompt: "Romaji untuk '7' (lebih umum):",
        kana: "なな",
        answer: ["nana"],
      },
      {
        type: "typing",
        prompt: "Romaji untuk '10':",
        kana: "じゅう",
        answer: ["juu", "ju"],
      },
    ],
    reward: { xp: 100 },
  },

  // ===== STAGE 5: MINI-BOSS - DAYS OF WEEK =====
  {
    id: "n5-5",
    worldId: "n5",
    index: 5,
    chapter: 1,
    title: "Ujian Penjaga Waktu",
    subtitle: "Mini-Boss: Hari & Bulan",
    type: "mini-boss",
    intro: [
      "**Menara Jam Vassal**",
      "Sesosok kurcaci berjanggut panjang menunggumu di puncak menara.",
      "「Aku **Tokkun**, penjaga waktu. Hari apa ini? Bulan apa ini? Kalau tidak tahu, kau tak boleh lewat!」",
      "Yuki: 「Hari dalam seminggu pakai 'youbi'. Bulan pakai 'gatsu'. Pelajari baik-baik!」",
    ],
    outro: [
      "Tokkun tertawa puas. 「Kau tahu waktuku! Silakan lanjut ke kastil dalam.」",
      "Ia memberimu kunci kecil. 「Ini kunci menuju perpustakaan kerajaan.」",
      "**Stage 5 selesai! +150 XP, 50 koin, Item: Kunci Perpustakaan, Badge: Lulus Ujian Waktu**",
    ],
    lesson: {
      title: "Hari & Bulan",
      rows: [
        { kana: "げつようび", romaji: "getsuyoubi", meaning: "Senin" },
        { kana: "かようび", romaji: "kayoubi", meaning: "Selasa" },
        { kana: "すいようび", romaji: "suiyoubi", meaning: "Rabu" },
        { kana: "もくようび", romaji: "mokuyoubi", meaning: "Kamis" },
        { kana: "きんようび", romaji: "kinyoubi", meaning: "Jumat" },
        { kana: "どようび", romaji: "doyoubi", meaning: "Sabtu" },
        { kana: "にちようび", romaji: "nichiyoubi", meaning: "Minggu" },
        { kana: "いちがつ", romaji: "ichigatsu", meaning: "Januari (bulan 1)" },
      ],
      note: "Hari: [nama] + youbi. Senin=getsu(bulan), Minggu=nichi(matahari). Bulan: [angka] + gatsu.",
    },
    enemies: [
      {
        id: "tokkun",
        name: "Tokkun Penjaga Waktu",
        nameJp: "トックン",
        sprite: "⏰",
        hp: 48,
        attack: 10,
        description: "Mini-boss: ujian hari & bulan.",
        color: "#cddc39",
        abilities: ["time-pressure", "shield", "enrage"],
      },
    ],
    questions: [
      {
        type: "typing",
        prompt: "Romaji untuk 'Senin':",
        kana: "げつようび",
        answer: ["getsuyoubi", "getsuyobi"],
      },
      {
        type: "choice",
        prompt: "「すいようび」 adalah hari?",
        kana: "すいようび",
        options: ["Senin", "Selasa", "Rabu", "Kamis"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'Jumat':",
        kana: "きんようび",
        answer: ["kinyoubi", "kinyobi"],
      },
      {
        type: "choice",
        prompt: "「にちようび」 adalah?",
        kana: "にちようび",
        options: ["Sabtu", "Minggu", "Senin", "Kamis"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'Januari' (bulan 1):",
        kana: "いちがつ",
        answer: ["ichigatsu"],
      },
      {
        type: "choice",
        prompt: "Suffix untuk hari adalah?",
        options: ["gatsu", "youbi", "nichi", "ka"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "Suffix untuk bulan adalah?",
        options: ["youbi", "gatsu", "nichi", "ka"],
        answer: 1,
      },
    ],
    reward: { xp: 150, item: "Kunci Perpustakaan", badge: "Lulus Ujian Waktu" },
  },

  // ===== STAGE 6: KANJI NUMBERS 1-10 =====
  {
    id: "n5-6",
    worldId: "n5",
    index: 6,
    chapter: 1,
    title: "Perpustakaan Kerajaan",
    subtitle: "Kanji Angka: 一二三四五六七八九十",
    type: "lesson",
    intro: [
      "**Perpustakaan Kerajaan Vassal**",
      "Setelah membuka pintu perpustakaan dengan kuncimu, kau melihat ribuan buku.",
      "Tapi semua buku tertulis dalam karakter aneh - Kanji!",
      "Pustakawan: 「Di sini buku pakai Kanji, huruf Tionghoa yang diadopsi Jepang. Mulai dengan angka.」",
      "Yuki: 「Kanji angka paling dasar. Bentuknya sederhana - belajar dulu 1-10.」",
    ],
    outro: [
      "Pustakawan tersenyum. 「Kau cepat belajar! Tapi Kanji banyak sekali - di N5 sekitar 100.」",
      "Ia memberimu kamus Kanji. 「Ini akan membantumu mengenali kanji dasar.」",
      "**Stage 6 selesai! +110 XP, 45 koin, Item: Kamus Kanji Dasar**",
    ],
    lesson: {
      title: "Kanji Angka 1-10",
      rows: [
        { kana: "一", romaji: "ichi", meaning: "satu" },
        { kana: "二", romaji: "ni", meaning: "dua" },
        { kana: "三", romaji: "san", meaning: "tiga" },
        { kana: "四", romaji: "yon/yo", meaning: "empat" },
        { kana: "五", romaji: "go", meaning: "lima" },
        { kana: "六", romaji: "roku", meaning: "enam" },
        { kana: "七", romaji: "nana/shichi", meaning: "tujuh" },
        { kana: "八", romaji: "hachi", meaning: "delapan" },
        { kana: "九", romaji: "kyuu/ku", meaning: "sembilan" },
        { kana: "十", romaji: "juu", meaning: "sepuluh" },
      ],
      note: "Kanji angka sering muncul di alamat, tanggal, harga. 一二三 = 123, kombinasi: 十一 = 11, 二十 = 20.",
    },
    enemies: [
      {
        id: "kanji-tutor",
        name: "Tutor Kanji",
        nameJp: "漢字",
        sprite: "📚",
        hp: 22,
        attack: 6,
        color: "#3f51b5",
        abilities: ["shield", "counter"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Kanji '一' dibaca?",
        kana: "一",
        options: ["ichi (1)", "ni (2)", "san (3)", "juu (10)"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "Kanji '三' adalah angka?",
        kana: "三",
        options: ["1", "2", "3", "5"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "Romaji untuk Kanji '七':",
        kana: "七",
        answer: ["nana", "shichi"],
      },
      {
        type: "choice",
        prompt: "Kanji '十' berarti?",
        kana: "十",
        options: ["1", "5", "10", "100"],
        answer: 2,
      },
      {
        type: "choice",
        prompt: "「十一」 artinya?",
        kana: "十一",
        options: ["9 (10-1)", "11 (10+1)", "20 (10×2)", "1 (10/10)"],
        answer: 1,
        hint: "Kanji digabung: 十(10) + 一(1) = 11",
      },
      {
        type: "typing",
        prompt: "Romaji untuk Kanji '五':",
        kana: "五",
        answer: ["go"],
      },
    ],
    reward: { xp: 110, item: "Kamus Kanji Dasar" },
  },

  // ===== STAGE 7: KANJI DASAR (orang, hari, bulan) =====
  {
    id: "n5-7",
    worldId: "n5",
    index: 7,
    chapter: 1,
    title: "Kanji Kehidupan Sehari-hari",
    subtitle: "人, 日, 月, 火, 水",
    type: "battle",
    intro: [
      "**Lorong Perpustakaan**",
      "Buku-buku berkilau di rak. Satu buku melayang: 「Pelajari kami, pemuda!」",
      "「Kanji dasar yang sering muncul: 人 (orang), 日 (hari/matahari), 月 (bulan), 「 (api), 水 (air).」",
      "Yuki: 「Ini kanji yang dipakai dalam nama hari! getsuyoubi = 月 + youbi.」",
    ],
    outro: [
      "Buku-buku di rak berdenting senang. 「Kau mengenal kami sekarang!」",
      "Yuki: 「Bagus! Sekarang kau bisa membaca tanda-tanda dasar di kerajaan.」",
      "**Stage 7 selesai! +120 XP, 50 koin**",
    ],
    lesson: {
      title: "Kanji Dasar Kehidupan",
      rows: [
        { kana: "人", romaji: "hito/nin", meaning: "orang" },
        { kana: "日", romaji: "hi/nichi", meaning: "hari/matahari" },
        { kana: "月", romaji: "tsuki/getsu", meaning: "bulan/bulan(kalender)" },
        { kana: "火", romaji: "hi/ka", meaning: "api" },
        { kana: "水", romaji: "mizu/sui", meaning: "air" },
        { kana: "木", romaji: "ki/moku", meaning: "pohon/kayu" },
        { kana: "金", romaji: "kin/kane", meaning: "emas/uang" },
        { kana: "本", romaji: "hon", meaning: "asal/buku" },
      ],
      note: "Hari dalam seminggu pakai kanji ini! 月(getsu=Senin), 「(ka=Selasa), 水(sui=Rabu), 木(moku=Kamis), 金(kin=Jumat), 土(do=Sabtu), 日(nichi=Minggu).",
    },
    enemies: [
      {
        id: "kanji-book",
        name: "Buku Kanji Hidup",
        nameJp: "本",
        sprite: "📖",
        hp: 25,
        attack: 6,
        color: "#795548",
        abilities: ["heal", "shield"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Kanji '人' berarti?",
        kana: "人",
        options: ["pohon", "orang", "air", "api"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "Kanji '日' berarti?",
        kana: "日",
        options: ["bulan", "matahari/hari", "orang", "uang"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk Kanji '月' (saat artinya bulan di langit):",
        kana: "月",
        answer: ["tsuki"],
      },
      {
        type: "choice",
        prompt: "Kanji '水' berarti?",
        kana: "水",
        options: ["api", "tanah", "air", "angin"],
        answer: 2,
      },
      {
        type: "choice",
        prompt: "Hari Senin 'げつようび' pakai kanji?",
        kana: "げつようび",
        options: ["日", "月", "「", "木"],
        answer: 1,
        hint: "getsu = bulan",
      },
      {
        type: "typing",
        prompt: "Romaji untuk Kanji '本' (saat artinya buku):",
        kana: "本",
        answer: ["hon"],
      },
    ],
    reward: { xp: 120 },
  },

  // ===== STAGE 8: VERB FORMS (masu) =====
  {
    id: "n5-8",
    worldId: "n5",
    index: 8,
    chapter: 1,
    title: "Aksi & Kehendak",
    subtitle: "Kata Kerja Bentuk ます (masu)",
    type: "battle",
    intro: [
      "**Halaman Kastil Dalam**",
      "Kau tiba di kastil dalam. Para penjaga sedang latihan pedang.",
      "Komandan: 「たべます! (makan!) のみます! (minum!) いきます! (pergi!)」",
      "「Pelajari bentuk ます (masu) - bentuk sopan kata kerja. Ini dasar semua kalimat kerja!」",
      "Yuki: 「ます (masu) = bentuk sopan positif. ません (masen) = bentuk sopan negatif.」",
    ],
    outro: [
      "Komandan mengangguk. 「Kau paham kata kerja! Sekarang bisa menyuruh dan menyatakan aksi.」",
      "**Stage 8 selesai! +130 XP, 55 koin**",
    ],
    lesson: {
      title: "Kata Kerja Bentuk ます (masu)",
      rows: [
        { kana: "たべます", romaji: "tabemasu", meaning: "makan (sopan)" },
        { kana: "のみます", romaji: "nomimasu", meaning: "minum (sopan)" },
        { kana: "いきます", romaji: "ikimasu", meaning: "pergi (sopan)" },
        { kana: "きます", romaji: "kimasu", meaning: "datang (sopan)" },
        { kana: "みます", romaji: "mimasu", meaning: "melihat (sopan)" },
        { kana: "ききます", romaji: "kikimasu", meaning: "mendengar (sopan)" },
        { kana: "よみます", romaji: "yomimasu", meaning: "membaca (sopan)" },
        { kana: "かきます", romaji: "kakimasu", meaning: "menulis (sopan)" },
      ],
      note: "Polanya: [stem] + ます. Untuk negatif: [stem] + ません. Bentuk lampau: [stem] + ました.",
    },
    enemies: [
      {
        id: "verb-shadow",
        name: "Bayangan Kata Kerja",
        nameJp: "動詞",
        sprite: "⚔",
        hp: 28,
        attack: 8,
        color: "#e91e63",
        abilities: ["multi-attack", "crit"],
        critChance: 0.2,
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "「たべます」 artinya?",
        kana: "たべます",
        options: ["minum", "makan", "tidur", "berjalan"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "「いきます」 artinya?",
        kana: "いきます",
        options: ["datang", "pergi", "lari", "duduk"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'membaca' (sopan):",
        kana: "よみます",
        answer: ["yomimasu"],
      },
      {
        type: "choice",
        prompt: "Negatif dari 'たべます' adalah?",
        options: ["たべません", "たべまさい", "たべないます", "たべませんた"],
        answer: 0,
        hint: "Ganti ます → ません",
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'mendengar' (sopan):",
        kana: "ききます",
        answer: ["kikimasu"],
      },
      {
        type: "choice",
        prompt: "「みます」 artinya?",
        kana: "みます",
        options: ["melihat", "membaca", "menulis", "makan"],
        answer: 0,
      },
    ],
    reward: { xp: 130 },
  },

  // ===== STAGE 9: ADJECTIVES (i & na) =====
  {
    id: "n5-9",
    worldId: "n5",
    index: 9,
    chapter: 1,
    title: "Deskripsi & Sifat",
    subtitle: "Kata Sifat -i & -na",
    type: "battle",
    intro: [
      "**Taman Kastil Vassal**",
      "Di taman yang indah, kau bertemu seorang pelayan yang bingung.",
      "「Bunga ini... あかい? たかい? きれい? Saya bingung kata sifat mana yang dipakai!」",
      "Yuki: 「Ada dua jenis kata sifat: -i (いい、たかい) dan -na (きれいな、しずかな). Pelajari!」",
    ],
    outro: [
      "Pelayan tersenyum. 「Bunga ini きれいですね! Cantik ya!」",
      "Yuki: 「Sekarang kau bisa mendeskripsikan apapun!」",
      "**Stage 9 selesai! +140 XP, 60 koin**",
    ],
    lesson: {
      title: "Kata Sifat -i & -na",
      rows: [
        { kana: "たかい", romaji: "takai", meaning: "tinggi / mahal (-i)" },
        { kana: "ひくい", romaji: "hikui", meaning: "rendah (-i)" },
        { kana: "おおきい", romaji: "ookii", meaning: "besar (-i)" },
        { kana: "ちいさい", romaji: "chiisai", meaning: "kecil (-i)" },
        { kana: "あかい", romaji: "akai", meaning: "merah (-i)" },
        { kana: "きれい(な)", romaji: "kirei (na)", meaning: "cantik / bersih (-na)" },
        { kana: "しずか(な)", romaji: "shizuka (na)", meaning: "tenang (-na)" },
        { kana: "げんき(な)", romaji: "genki (na)", meaning: "sehat / energetik (-na)" },
      ],
      note: "Sifat -i: berakhiran い, langsung pakai (たかい + です). Sifat -na: pakai 'na' sebelum kata benda (きれいな 」ん).",
    },
    enemies: [
      {
        id: "adjective-mist",
        name: "Kabut Sifat",
        nameJp: "形容詞",
        sprite: "「",
        hp: 30,
        attack: 8,
        color: "#cfd8dc",
        abilities: ["poison", "regen", "counter"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "「たかい」 berarti?",
        kana: "たかい",
        options: ["rendah", "tinggi/mahal", "kecil", "merah"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "Mana yang merupakan kata sifat -na?",
        options: ["たかい", "おおきい", "きれい", "あかい"],
        answer: 2,
        hint: "Tidak berakhiran 'i'!",
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'merah':",
        kana: "あかい",
        answer: ["akai"],
      },
      {
        type: "choice",
        prompt: "Untuk mendeskripsikan buku yang cantik, kau bilang?",
        options: ["きれい 」ん", "きれいな 」ん", "きれいの 」ん", "きれいい 」ん"],
        answer: 1,
        hint: "Sifat -na + na + kata benda",
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'sehat/energetik' (sifat -na):",
        kana: "げんき",
        answer: ["genki"],
      },
    ],
    reward: { xp: 140 },
  },

  // ===== STAGE 10: BOSS - LORD VASSAL =====
  {
    id: "n5-10",
    worldId: "n5",
    index: 10,
    chapter: 1,
    title: "Lord Vassal",
    subtitle: "Bos Akhir Bab N5",
    type: "boss",
    intro: [
      "**Tahta Kastil Vassal**",
      "Di aula tahta, sesosok pria berjanggut putih duduk di singgasana. **Lord Vassal**, penguasa kerajaan.",
      "「Pengelana dari Hajimari... Aku dengar kau membantu pendudukku. Tapi untuk kuasai kerajaanku, kau harus menguasaiku dulu dalam bahasa!」",
      "Yuki: 「Ini ujian akhir N5. Gabungkan semua yang kau pelajari - salam, kata ganti, desu, angka, hari, kanji, kata kerja, sifat!」",
      "Lord Vassal berdiri. 「Pertarungan bahasa dimulai!」",
      "**PERTARUNGAN AKHIR BAB N5**",
    ],
    outro: [
      "Lord Vassal tertawa lebar. 「HAHAHA! Kau menguasai dasar bahasa Jepang!」",
      "Ia menjabat tanganmu. 「Selamat, pahlawan. Kau pantas mendapat gelar 「Pengelana Dasar」.」",
      "Ia menyerahkan medali emas. 「Dengan ini, kau lanjut ke Bab 2: Ujian Akademi!」",
      "Yuki: 「Aku bangga padamu. Sekarang waktunya ujian resmi di Akademi!」",
      "**BAB 1 SELESAI! +800 XP, 300 koin, Badge: Pengelana Dasar, Item: Medali Vassal**",
      "**Bab 2 terbuka: Ujian Akademi (Stage 11-20)**",
    ],
    lesson: {
      title: "Ujian Akhir N5",
      rows: [
        { kana: "おはよう", romaji: "ohayou", meaning: "selamat pagi" },
        { kana: "わたし", romaji: "watashi", meaning: "saya" },
        { kana: "です", romaji: "desu", meaning: "adalah" },
        { kana: "さん", romaji: "san", meaning: "3 (atau akhiran hormat)" },
        { kana: "たべます", romaji: "tabemasu", meaning: "makan" },
        { kana: "たかい", romaji: "takai", meaning: "tinggi/mahal" },
        { kana: "人", romaji: "hito", meaning: "orang" },
        { kana: "日", romaji: "hi", meaning: "hari" },
      ],
      note: "Semua yang dipelajari di Bab N5 jadi fondasi N4 dan seterusnya. Selamat, Pengelana!",
    },
    enemies: [
      {
        id: "lord-vassal",
        name: "Lord Vassal",
        nameJp: "ヴァッサ「卿",
        sprite: "🤴",
        hp: 108,
        attack: 15,
        description: "Bos akhir N5. Penguasa Vassal Kingdom, ahli bahasa formal.",
        color: "#ff9800",
        abilities: ["enrage", "heal", "crit", "shield", "multi-attack", "counter"],
        critChance: 0.2,
      },
    ],
    questions: [
      // Comprehensive N5 review
      {
        type: "choice",
        prompt: "「おはようございます」 dipakai kapan?",
        kana: "おはようございます",
        options: ["pagi (formal)", "siang", "malam", "selamat tinggal"],
        answer: 0,
      },
      {
        type: "typing",
        prompt: "Romaji 'わたしたち' (kami/kita):",
        kana: "わたしたち",
        answer: ["watashitachi"],
      },
      {
        type: "choice",
        prompt: "「これは 」ん です」 artinya?",
        kana: "これは ほん です",
        options: ["Ini adalah buku", "Itu adalah buku", "Aku adalah buku", "Buku adalah ini"],
        answer: 0,
      },
      {
        type: "typing",
        prompt: "Romaji angka '7' (lebih umum):",
        kana: "なな",
        answer: ["nana"],
      },
      {
        type: "choice",
        prompt: "Kanji '人' dibaca saat artinya 'orang'?",
        kana: "人",
        options: ["hi", "hito", "tsuki", "hon"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "「きんようび」 adalah hari?",
        kana: "きんようび",
        options: ["Senin", "Rabu", "Jumat", "Minggu"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "Romaji 'のみます' (minum - sopan):",
        kana: "のみます",
        answer: ["nomimasu"],
      },
      {
        type: "choice",
        prompt: "「きれいな はな」 artinya?",
        kana: "きれいな はな",
        options: ["Bunga yang cantik", "Bunga yang tinggi", "Bunga merah", "Bunga besar"],
        answer: 0,
      },
      {
        type: "typing",
        prompt: "Romaji 'すみません' (maaf/permisi):",
        kana: "すみません",
        answer: ["sumimasen"],
      },
      {
        type: "choice",
        prompt: "「Selamat tinggal」 dalam bahasa Jepang?",
        options: ["こんにちは", "ありがとう", "さようなら", "すみません"],
        answer: 2,
      },
    ],
    reward: { xp: 800, badge: "Pengelana Dasar", item: "Medali Vassal" },
  },

  // ===== STAGE 11: UJIAN DIMULAI - Kana dalam opsi =====
  {
    id: "n5-11",
    worldId: "n5",
    index: 11,
    chapter: 2,
    title: "Ujian Gerbang Akademi",
    subtitle: "Adaptasi: Kana mulai muncul di opsi",
    type: "lesson",
    intro: [
      "**Akademi Kerajaan Vassal - Pagi**",
      "Setelah menguasai dasar, kau diajak ke Akademi Kerajaan untuk ujian resmi.",
      "Penguji: 「Selamat datang. Ujian ini berbeda - mulai sekarang, opsi jawaban akan pakai huruf Jepang. Bukan romaji lagi.」",
      "「Jangan khawatir, pelan-pelan. Kita mulai dari yang mudah.」",
    ],
    outro: [
      "Penguji: 「Bagus! Kau mulai terbiasa dengan kana di opsi. Lanjut!」",
      "**Stage 11 selesai! +120 XP**",
    ],
    lesson: {
      title: "Transisi ke Kana",
      rows: [
        { kana: "わたし", romaji: "watashi", meaning: "saya" },
        { kana: "あなた", romaji: "anata", meaning: "kamu" },
        { kana: "ともだち", romaji: "tomodachi", meaning: "teman" },
        { kana: "がっこう", romaji: "gakkou", meaning: "sekolah" },
        { kana: "せんせい", romaji: "sensei", meaning: "guru" },
      ],
      note: "Ujian adaptif: opsi mulai pakai kana (ひらがな) bukan romaji. Latih membaca!",
    },
    enemies: [
      { id: "exam-proctor", name: "Pengawas Ujian", sprite: "📋", hp: 30, attack: 7, color: "#607d8b", abilities: ["time-pressure", "shield"] },
    ],
    questions: [
      { type: "choice", prompt: "「わたし」の いみは?", kana: "わたし", options: ["saya", "kamu", "teman", "guru"], answer: 0, hint: "kata ganti orang pertama" },
      { type: "choice", prompt: "Apa arti がっこう?", kana: "がっこう", options: ["sekolah", "rumah", "toko", "kuil"], answer: 0 },
      { type: "choice", prompt: "「sensei」を 「」んごで:", options: ["せんせい", "がっこう", "ともだち", "わたし"], answer: 0, hint: "guru dalam bahasa Jepang" },
      { type: "choice", prompt: "Teman = ?", options: ["ともだち", "せんせい", "わたし", "あなた"], answer: 0 },
      { type: "typing", prompt: "Ketik romaji untuk がっこう:", kana: "がっこう", answer: ["gakkou", "gakko"] },
      { type: "choice", prompt: "あなたの いみは?", kana: "あなた", options: ["kamu", "saya", "dia", "kami"], answer: 0 },
    ],
    reward: { xp: 120 },
  },

  // ===== STAGE 12: Kana penuh di opsi =====
  {
    id: "n5-12",
    worldId: "n5",
    index: 12,
    chapter: 2,
    title: "Membaca Tanpa Romaji",
    subtitle: "Full kana di opsi jawaban",
    type: "battle",
    intro: [
      "**Ruang Ujian 1**",
      "Penguji: 「Sekarang semua opsi pakai ひらがな. Tidak ada romaji lagi.」",
      "「Kau harus bisa membaca huruf Jepang untuk menjawab. Fokus!」",
    ],
    outro: ["Penguji: 「Kau bisa baca kana tanpa romaji! Lanjut ke kanji!」", "**Stage 12 selesai! +140 XP**"],
    lesson: {
      title: "Kosakata Sehari-hari (Kana)",
      rows: [
        { kana: "みず", romaji: "mizu", meaning: "air" },
        { kana: "たべもの", romaji: "tabemono", meaning: "makanan" },
        { kana: "のみもの", romaji: "nomimono", meaning: "minuman" },
        { kana: "あさ", romaji: "asa", meaning: "pagi" },
        { kana: "よる", romaji: "yoru", meaning: "malam" },
        { kana: "ひる", romaji: "hiru", meaning: "siang" },
      ],
      note: "Sekarang opsi jawaban full kana. Tidak ada bantuan romaji!",
    },
    enemies: [
      { id: "kana-reader", name: "Pembaca Kana", sprite: "📖", hp: 35, attack: 8, color: "#3f51b5", abilities: ["crit", "shield"] },
    ],
    questions: [
      { type: "choice", prompt: "「みず」の いみは?", kana: "みず", options: ["みず", "たべもの", "よる", "あさ"], answer: 0, hint: "yang diminum" },
      { type: "choice", prompt: "Apa arti たべもの?", kana: "たべもの", options: ["みず", "たべもの", "のむ", "よる"], answer: 1, hint: "yang dimakan" },
      { type: "choice", prompt: "「malam」は 「」んごで?", options: ["あさ", "ひる", "よる", "みず"], answer: 2 },
      { type: "choice", prompt: "「siang」は?", options: ["あさ", "ひる", "よる", "みず"], answer: 1 },
      { type: "typing", prompt: "ロマジで かいて (ketik romaji): のみもの", kana: "のみもの", answer: ["nomimono"] },
      { type: "choice", prompt: "「pagi」は 「」んごで?", options: ["あさ", "ひる", "よる", "みず"], answer: 0 },
    ],
    reward: { xp: 140 },
  },

  // ===== STAGE 13: Kanji mulai muncul =====
  {
    id: "n5-13",
    worldId: "n5",
    index: 13,
    chapter: 2,
    title: "Kanji Pertama",
    subtitle: "Kanji dasar di soal",
    type: "battle",
    intro: [
      "**Ruang Ujian 2**",
      "Penguji: 「Sekarang kanji mulai muncul. Tapi jangan takut - itu kanji yang sudah kau pelajari!」",
      "「人, 日, 月, 火, 水, 木, 金 - semua ini sudah kau kenal.」",
    ],
    outro: ["Penguji: 「Kanji pertama berhasil! Lanjut ke tingkat lebih sulit!」", "**Stage 13 selesai! +160 XP**"],
    lesson: undefined,
    enemies: [
      { id: "kanji-tester", name: "Penguji Kanji", sprite: "🔤", hp: 40, attack: 9, color: "#e91e63", abilities: ["enrage", "crit"] },
    ],
    questions: [
      { type: "choice", prompt: "「人」の よみかたは?", kana: "人", options: ["ひと", "ひ", "「ち", "つき"], answer: 0, hint: "orang" },
      { type: "choice", prompt: "「日」の いみは?", kana: "日", options: ["hari/matahari", "bulan", "api", "air"], answer: 0 },
      { type: "choice", prompt: "「月」の いみは?", kana: "月", options: ["hari", "bulan", "tahun", "jam"], answer: 1 },
      { type: "choice", prompt: "「火」の いみは?", kana: "火", options: ["air", "tanah", "api", "angin"], answer: 2 },
      { type: "choice", prompt: "「水」の いみは?", kana: "水", options: ["みず", "ひ", "つき", "ひと"], answer: 0, hint: "air" },
      { type: "typing", prompt: "ロマジで: 人 (orang)", kana: "人", answer: ["hito", "nin"] },
    ],
    reward: { xp: 160 },
  },

  // ===== STAGE 14: Kalimat pendek =====
  {
    id: "n5-14",
    worldId: "n5",
    index: 14,
    chapter: 2,
    title: "Kalimat Sederhana",
    subtitle: "Pahami kalimat pendek",
    type: "battle",
    intro: [
      "**Ruang Ujian 3**",
      "Penguji: 「Sekarang kalimat! Bukan cuma kata tunggal.」",
      "「わたしは がくせい です - kalimat seperti ini. Pahami artinya!」",
    ],
    outro: ["Penguji: 「Kau bisa baca kalimat! Hebat!」", "**Stage 14 selesai! +180 XP**"],
    lesson: {
      title: "Kalimat Dasar",
      rows: [
        { kana: "わたしは がくせい です", romaji: "watashi wa gakusei desu", meaning: "saya adalah murid" },
        { kana: "これは ほん です", romaji: "kore wa hon desu", meaning: "ini adalah buku" },
        { kana: "それは えんぴつ です", romaji: "sore wa enpitsu desu", meaning: "itu adalah pensil" },
        { kana: "あそこに がっこう が あります", romaji: "asoko ni gakkou ga arimasu", meaning: "di sana ada sekolah" },
      ],
      note: "Kalimat dasar: A は B です (A adalah B). これ = ini, それ = itu (dekat lawan), あれ = itu (jauh).",
    },
    enemies: [
      { id: "sentence-spirit", name: "Roh Kalimat", sprite: "💬", hp: 45, attack: 10, color: "#7e57c2", abilities: ["poison", "multi-attack"] },
    ],
    questions: [
      { type: "choice", prompt: "「わたしは がくせい です」の いみは?", kana: "わたしは がくせい です", options: ["saya murid", "kamu guru", "dia teman", "ini buku"], answer: 0 },
      { type: "choice", prompt: "「これは 」ん です」の いみは?", kana: "これは ほん です", options: ["ini buku", "itu pensil", "saya murid", "ada sekolah"], answer: 0 },
      { type: "choice", prompt: "「それ」の いみは?", kana: "それ", options: ["ini (dekat saya)", "itu (dekat lawan)", "itu (jauh)", "mana"], answer: 1 },
      { type: "choice", prompt: "「あそこ「 がっこう が あります」 artinya?", kana: "あそこに がっこう が あります", options: ["di sana ada sekolah", "di sini ada buku", "saya ke sekolah", "sekolah jauh"], answer: 0 },
      { type: "typing", prompt: "ロマジで: これは 」ん です", kana: "これは ほん です", answer: ["kore wa hon desu"] },
    ],
    reward: { xp: 180 },
  },

  // ===== STAGE 15: Mini-boss Ujian Tengah =====
  {
    id: "n5-15",
    worldId: "n5",
    index: 15,
    chapter: 2,
    title: "Ujian Tengah Semester",
    subtitle: "Mini-Boss: Professor Vassal",
    type: "mini-boss",
    intro: [
      "**Aula Besar Akademi**",
      "**Professor Vassal** duduk di meja ujian. 「Selamat, kau sampai ujian tengah! Tapi sekarang, aku yang menguji.」",
      "「Semua soal pakai huruf Jepang. Tidak ada romaji. Siap?」",
    ],
    outro: [
      "Professor Vassal: 「Kau lulus ujian tengah! Setengah jalan lagi!」",
      "**Stage 15 selesai! +250 XP, Badge: Lulus Ujian Tengah**",
    ],
    lesson: undefined,
    enemies: [
      { id: "professor-vassal", name: "Professor Vassal", sprite: "🎓", hp: 60, attack: 10, color: "#ff9800", abilities: ["enrage", "shield", "counter", "time-pressure"] },
    ],
    questions: [
      { type: "choice", prompt: "「わたし」の いみは?", kana: "わたし", options: ["saya", "kamu", "dia", "kami"], answer: 0 },
      { type: "choice", prompt: "「ひと」を かんじで:", options: ["人", "日", "月", "「"], answer: 0 },
      { type: "choice", prompt: "「わたしは がくせい です」の いみは?", kana: "わたしは がくせい です", options: ["saya murid", "kamu guru", "ini buku", "dia teman"], answer: 0 },
      { type: "choice", prompt: "「みず」の いみは?", kana: "みず", options: ["みず", "ひ", "つき", "ひと"], answer: 0 },
      { type: "typing", prompt: "ロマジで: たべもの", kana: "たべもの", answer: ["tabemono"] },
      { type: "choice", prompt: "「日」の よみかたは? (bacaan)", kana: "日", options: ["ひ/「ち", "つき", "ひと", "みず"], answer: 0 },
      { type: "choice", prompt: "「それ」の いみは?", kana: "それ", options: ["itu (dekat lawan)", "ini", "itu (jauh)", "mana"], answer: 0 },
      { type: "typing", prompt: "ロマジで: よる (malam)", kana: "よる", answer: ["yoru"] },
    ],
    reward: { xp: 250, badge: "Lulus Ujian Tengah" },
  },

  // ===== STAGE 16: Kosakata rumah =====
  {
    id: "n5-16",
    worldId: "n5",
    index: 16,
    chapter: 2,
    title: "Kosakata Rumah",
    subtitle: "Full kana + kanji",
    type: "battle",
    intro: [
      "**Ruang Ujian 4**",
      "Penguji: 「Tema: rumah & kehidupan sehari-hari. Semua dalam bahasa Jepang!」",
    ],
    outro: ["Penguji: 「Kosakata rumah terkuasai!」", "**Stage 16 selesai! +200 XP**"],
    lesson: {
      title: "Kosakata Rumah",
      rows: [
        { kana: "いえ", romaji: "ie", meaning: "rumah" },
        { kana: "へや", romaji: "heya", meaning: "kamar" },
        { kana: "ドア", romaji: "doa", meaning: "pintu" },
        { kana: "まど", romaji: "mado", meaning: "jendela" },
        { kana: "ベッド", romaji: "beddo", meaning: "kasur" },
        { kana: "テーブル", romaji: "teeburu", meaning: "meja" },
      ],
      note: "Kata serapan pakai Katakana: ドア (doa), ベッド (beddo), テーブ「 (teeburu).",
    },
    enemies: [
      { id: "home-ghost", name: "Hantu Rumah", sprite: "🏠", hp: 50, attack: 11, color: "#795548", abilities: ["regen", "shield"] },
    ],
    questions: [
      { type: "choice", prompt: "「いえ」の いみは?", kana: "いえ", options: ["いえ", "へや", "まど", "ドア"], answer: 0, hint: "tempat tinggal" },
      { type: "choice", prompt: "「jendela」は 「」んごで?", options: ["まど", "ドア", "ベッド", "へや"], answer: 0 },
      { type: "choice", prompt: "「ベッド」の いみは?", kana: "ベッド", options: ["kasur", "meja", "pintu", "jendela"], answer: 0 },
      { type: "typing", prompt: "ロマジで: へや (kamar)", kana: "へや", answer: ["heya"] },
      { type: "choice", prompt: "「テーブ「」は な「?", kana: "テーブル", options: ["meja", "kursi", "pintu", "jendela"], answer: 0 },
      { type: "typing", prompt: "ロマジで: まど", kana: "まど", answer: ["mado"] },
    ],
    reward: { xp: 200 },
  },

  // ===== STAGE 17: Kosakata makanan =====
  {
    id: "n5-17",
    worldId: "n5",
    index: 17,
    chapter: 2,
    title: "Kosakata Makanan",
    subtitle: "Makanan & minuman",
    type: "battle",
    intro: [
      "**Ruang Ujian 5**",
      "Penguji: 「Tema: makanan. Semua dalam ひらがな と 「タ「ナ!」",
    ],
    outro: ["Penguji: 「Lapar juga bisa belajar!」", "**Stage 17 selesai! +220 XP**"],
    lesson: {
      title: "Kosakata Makanan",
      rows: [
        { kana: "ごはん", romaji: "gohan", meaning: "nasi/makan" },
        { kana: "パン", romaji: "pan", meaning: "roti" },
        { kana: "肉", romaji: "niku", meaning: "daging" },
        { kana: "やさい", romaji: "yasai", meaning: "sayuran" },
        { kana: "くだもの", romaji: "kudamono", meaning: "buah" },
        { kana: "コーヒー", romaji: "koohii", meaning: "kopi" },
        { kana: "おちゃ", romaji: "ocha", meaning: "teh" },
      ],
      note: "Kata serapan: パン (pan=roti), コーヒー (kopi). Kata asli: ごはん (nasi), 「く (daging).",
    },
    enemies: [
      { id: "food-critic", name: "Kritikus Kuliner", sprite: "🍣", hp: 55, attack: 12, color: "#ff5722", abilities: ["poison", "crit"] },
    ],
    questions: [
      { type: "choice", prompt: "「ごはん」の いみは?", kana: "ごはん", options: ["nasi/makan", "roti", "daging", "sayur"], answer: 0 },
      { type: "choice", prompt: "「パン」の いみは?", kana: "パン", options: ["roti", "nasi", "teh", "kopi"], answer: 0 },
      { type: "choice", prompt: "「buah」は 「」んごで?", options: ["くだもの", "やさい", "「く", "パン"], answer: 0 },
      { type: "choice", prompt: "「コーヒー」の いみは?", kana: "コーヒー", options: ["kopi", "teh", "susu", "jus"], answer: 0 },
      { type: "typing", prompt: "ロマジで: おちゃ (teh)", kana: "おちゃ", answer: ["ocha"] },
      { type: "choice", prompt: "「やさい」の いみは?", kana: "やさい", options: ["sayuran", "buah", "daging", "nasi"], answer: 0 },
    ],
    reward: { xp: 220 },
  },

  // ===== STAGE 18: Kosakata transport =====
  {
    id: "n5-18",
    worldId: "n5",
    index: 18,
    chapter: 2,
    title: "Kosakata Transportasi",
    subtitle: "Transportasi & arah",
    type: "battle",
    intro: [
      "**Ruang Ujian 6**",
      "Penguji: 「Tema: transportasi. Banyak kata serapan pakai Katakana!」",
    ],
    outro: ["Penguji: 「Sekarang kau bisa navigasi kota!」", "**Stage 18 selesai! +240 XP**"],
    lesson: {
      title: "Kosakata Transportasi",
      rows: [
        { kana: "でんしゃ", romaji: "densha", meaning: "kereta listrik" },
        { kana: "バス", romaji: "basu", meaning: "bus" },
        { kana: "タクシー", romaji: "takushii", meaning: "taksi" },
        { kana: "くるま", romaji: "kuruma", meaning: "mobil" },
        { kana: "みぎ", romaji: "migi", meaning: "kanan" },
        { kana: "ひだり", romaji: "hidari", meaning: "kiri" },
        { kana: "まっすぐ", romaji: "massugu", meaning: "lurus" },
      ],
      note: "Transportasi: でんしゃ (kereta), バス (bus), タクシー (taksi). Arah: みぎ (kanan), ひだり (kiri), まっすぐ (lurus).",
    },
    enemies: [
      { id: "traffic-control", name: "Pengatur Lalu Lintas", sprite: "🚦", hp: 60, attack: 13, color: "#4caf50", abilities: ["time-pressure", "multi-attack"] },
    ],
    questions: [
      { type: "choice", prompt: "「でんしゃ」の いみは?", kana: "でんしゃ", options: ["kereta", "bus", "taksi", "mobil"], answer: 0 },
      { type: "choice", prompt: "「バス」の いみは?", kana: "バス", options: ["bus", "kereta", "mobil", "taksi"], answer: 0 },
      { type: "choice", prompt: "「kanan」は 「」んごで?", options: ["みぎ", "ひだり", "まっすぐ", "くるま"], answer: 0 },
      { type: "choice", prompt: "「ひだり」の いみは?", kana: "ひだり", options: ["kiri", "kanan", "lurus", "mundur"], answer: 0 },
      { type: "typing", prompt: "ロマジで: まっすぐ (lurus)", kana: "まっすぐ", answer: ["massugu", "massugu"] },
      { type: "choice", prompt: "「タクシー」の いみは?", kana: "タクシー", options: ["taksi", "bus", "kereta", "mobil"], answer: 0 },
    ],
    reward: { xp: 240 },
  },

  // ===== STAGE 19: Ujian pra-final =====
  {
    id: "n5-19",
    worldId: "n5",
    index: 19,
    chapter: 2,
    title: "Persiapan Ujian Akhir",
    subtitle: "Review menyeluruh - full Japanese",
    type: "battle",
    intro: [
      "**Ruang Ujian 7 - Terakhir sebelum Final**",
      "Penguji: 「Ini review semua materi. Soal campuran: kana, kanji, kalimat, kosakata. Semua dalam bahasa Jepang!」",
      "「Lulus ini, dan kau siap ujian akhir！」",
    ],
    outro: ["Penguji: 「Kau siap! Ujian akhir menunggu!」", "**Stage 19 selesai! +280 XP**"],
    lesson: undefined,
    enemies: [
      { id: "review-master", name: "Master Review", sprite: "📚", hp: 70, attack: 14, color: "#7c4dff", abilities: ["enrage", "shield", "counter", "crit"] },
    ],
    questions: [
      { type: "choice", prompt: "「わたし」の いみは?", kana: "わたし", options: ["saya", "kamu", "dia", "teman"], answer: 0 },
      { type: "choice", prompt: "「ひと」を かんじで:", options: ["人", "日", "月", "「"], answer: 0 },
      { type: "choice", prompt: "「ごはん」の いみは?", kana: "ごはん", options: ["nasi/makan", "roti", "air", "sayur"], answer: 0 },
      { type: "choice", prompt: "「でんしゃ」の いみは?", kana: "でんしゃ", options: ["kereta", "bus", "mobil", "taksi"], answer: 0 },
      { type: "choice", prompt: "「みぎ」の いみは?", kana: "みぎ", options: ["kanan", "kiri", "lurus", "mundur"], answer: 0 },
      { type: "typing", prompt: "ロマジで: たべもの (makanan)", kana: "たべもの", answer: ["tabemono"] },
      { type: "choice", prompt: "「わたしは がくせい です」の いみは?", kana: "わたしは がくせい です", options: ["saya murid", "kamu guru", "ini buku", "dia teman"], answer: 0 },
      { type: "choice", prompt: "「パン」の いみは?", kana: "パン", options: ["roti", "nasi", "teh", "kopi"], answer: 0 },
    ],
    reward: { xp: 280 },
  },

  // ===== STAGE 20: UJIAN AKHIR - BOSS =====
  {
    id: "n5-20",
    worldId: "n5",
    index: 20,
    chapter: 2,
    title: "Ujian Akhir Vassal",
    subtitle: "Bos Akhir: Ujian Tingkat Dasar",
    type: "boss",
    intro: [
      "**Aula Utama Akademi - Ujian Akhir**",
      "Di aula utama, dewan penguji menunggu. **Chancellor Vassal** berdiri di tengah.",
      "「Pengelana, ini ujian akhir tingkat Dasar. Lulus, dan kau naik ke tingkat Madya Bawah - Minato Port!」",
      "「Semua soal dalam bahasa Jepang penuh. Tidak ada romaji. Tunjukkan kemampuanmu!」",
      "**UJIAN AKHIR TINGKAT DASAR DIMULAI**",
    ],
    outro: [
      "Chancellor Vassal: 「Kau lulus dengan sempurna! Gelar 「Sarjana Dasar」 adalah milikmu!」",
      "Ia menyerahkan sertifikat emas. 「Lanjut ke Minato Port - tingkat Madya Bawah menunggu!」",
      "**UJIAN AKHIR DASAR SELESAI! +1000 XP, 500 koin, Badge: Sarjana Dasar, Item: Sertifikat Vassal**",
      "**Bab 2 terbuka: Ujian Akademi (Stage 11-20)**",
    ],
    lesson: undefined,
    enemies: [
      { id: "chancellor-vassal", name: "Chancellor Vassal", sprite: "🎩", hp: 150, attack: 15, color: "#ff9800", abilities: ["enrage", "heal", "crit", "shield", "multi-attack", "counter", "poison", "time-pressure"] },
    ],
    questions: [
      // Full Japanese exam - comprehensive
      { type: "choice", prompt: "「わたし」の いみは?", kana: "わたし", options: ["saya", "kamu", "dia", "kami"], answer: 0 },
      { type: "choice", prompt: "「人」の よみかたは?", kana: "人", options: ["ひと", "ひ", "「ち", "つき"], answer: 0 },
      { type: "choice", prompt: "「わたしは がくせい です」の いみは?", kana: "わたしは がくせい です", options: ["saya murid", "kamu guru", "ini buku", "dia teman"], answer: 0 },
      { type: "choice", prompt: "「ごはん」の いみは?", kana: "ごはん", options: ["nasi/makan", "roti", "air", "daging"], answer: 0 },
      { type: "choice", prompt: "「でんしゃ」の いみは?", kana: "でんしゃ", options: ["kereta", "bus", "taksi", "mobil"], answer: 0 },
      { type: "typing", prompt: "ロマジで: たべもの (makanan)", kana: "たべもの", answer: ["tabemono"] },
      { type: "choice", prompt: "「みぎ」の いみは?", kana: "みぎ", options: ["kanan", "kiri", "lurus", "mundur"], answer: 0 },
      { type: "choice", prompt: "「パン」の いみは?", kana: "パン", options: ["roti", "nasi", "teh", "kopi"], answer: 0 },
      { type: "choice", prompt: "「これは 」ん です」の いみは?", kana: "これは ほん です", options: ["ini buku", "itu pensil", "saya murid", "ada sekolah"], answer: 0 },
      { type: "choice", prompt: "「日」の いみは?", kana: "日", options: ["hari/matahari", "bulan", "api", "air"], answer: 0 },
      { type: "typing", prompt: "ロマジで: よる (malam)", kana: "よる", answer: ["yoru"] },
      { type: "choice", prompt: "「コーヒー」の いみは?", kana: "コーヒー", options: ["kopi", "teh", "susu", "jus"], answer: 0 },
    ],
    reward: { xp: 1000, badge: "Sarjana Dasar", item: "Sertifikat Vassal" },
  },
];
