import type { Stage } from "./types";

// ===== VASSAL KINGDOM - CHAPTER 1: JLPT N5 =====
// 10 stages covering: greetings, particles, basic grammar, first kanji, common vocab.
// Story: Player arrives at Vassal Kingdom after defeating Shadow King.
// The kingdom's market is in chaos - merchants can't speak properly.
// Player must restore communication by learning N5 Japanese.

export const N5_STAGES: Stage[] = [
  // ===== STAGE 1: GREETINGS =====
  {
    id: "n5-1",
    worldId: "n5",
    index: 1,
    chapter: 1,
    title: "Tiba di Vassal Kingdom",
    subtitle: "Salam & Percakapan Dasar",
    type: "lesson",
    intro: [
      "**Gerbang Vassal Kingdom - Pagi**",
      "Setelah perjalanan panjang dari desa Hajimari, kau tiba di gerbang besar Kerajaan Vassal.",
      "Penjaga gerbang menyapa: 「おはようございます! Selamat pagi, pengelana!」",
      "Yuki (yang ikut): 「Di sini orang berbicara dengan kalimat utuh. Kau harus belajar salam dasar.」",
      "「Ini fondasi semua percakapan N5 - salam, terima kasih, permohonan maaf.」",
    ],
    outro: [
      "Penjaga tersenyum. 「おはようございます! Silakan masuk. Semoga harimu menyenangkan!」",
      "Yuki: «Sekarang kau bisa menyapa siapa saja! Tapi pasar sedang kacau...」",
      "**Stage 1 selesai! +70 XP, 25 koin**",
    ],
    lesson: {
      title: "Salam & Percakapan Dasar",
      rows: [
        { kana: "おはよう", romaji: "ohayou", meaning: "selamat pagi (santai)" },
        { kana: "おはようございます", romaji: "ohayou gozaimasu", meaning: "selamat pagi (formal)" },
        { kana: "こんにちは", romaji: "konnichiwa", meaning: "halo / selamat siang" },
        { kana: "こんばんは", romaji: "konbanwa", meaning: "selamat malam" },
        { kana: "さようなら", romaji: "sayounara", meaning: "selamat tinggal" },
        { kana: "ありがとう", romaji: "arigatou", meaning: "terima kasih" },
        { kana: "すみません", romaji: "sumimasen", meaning: "maaf / permisi" },
        { kana: "はじめまして", romaji: "hajimemashite", meaning: "senang berkenalan" },
      ],
      note: "Formal: tambah 'gozaimasu' (ございます). 'sumimasen' bisa berarti 'maaf' ATAU 'permisi' ATAU 'minta perhatian'.",
    },
    enemies: [
      {
        id: "confused-merchant",
        name: "Pedagang Bingung",
        nameJp: "商人",
        sprite: "🧑‍🌾",
        hp: 5,
        attack: 2,
        description: "Tidak bisa menyapa dengan benar.",
        color: "#8d6e63",
        abilities: ["regen"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Apa arti 'おはようございます'?",
        kana: "おはようございます",
        options: ["selamat pagi (formal)", "selamat malam", "selamat tinggal", "terima kasih"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "'こんにちは' digunakan kapan?",
        kana: "こんにちは",
        options: ["pagi hari", "siang/sore", "malam hari", "selalu"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'terima kasih':",
        kana: "ありがとう",
        answer: ["arigatou", "arigato"],
      },
      {
        type: "choice",
        prompt: "Saat meminta perhatian seseorang, kau bilang?",
        options: ["ありがとう", "すみません", "さようなら", "こんにちは"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'senang berkenalan':",
        kana: "はじめまして",
        answer: ["hajimemashite"],
      },
    ],
    reward: { xp: 70 },
  },

  // ===== STAGE 2: PRONOUNS =====
  {
    id: "n5-2",
    worldId: "n5",
    index: 2,
    chapter: 1,
    title: "Siapa Kau? Siapa Aku?",
    subtitle: "Kata Ganti Orang",
    type: "battle",
    intro: [
      "**Alun-alun Vassal Kingdom**",
      "Di alun-alun, kau melihat seorang anak kecil menangis. 「あなたは... あなたは...」",
      "Ia tidak bisa menyebut nama orang. 「Aku tidak tahu kata ganti!」",
      "Yuki: 「Kata ganti orang penting untuk percakapan. わたし (saya), あなた (kamu), かれ (dia laki-laki), かのじょ (dia perempuan).」",
    ],
    outro: [
      "Anak itu tersenyum. 「わたしは トモ です! Nama saya Tomo! Terima kasih, pengelana!」",
      "Yuki: «Bagus! Sekarang kau bisa memperkenalkan diri.»",
      "**Stage 2 selesai! +80 XP, 30 koin**",
    ],
    lesson: {
      title: "Kata Ganti Orang (Pronouns)",
      rows: [
        { kana: "わたし", romaji: "watashi", meaning: "saya (umum)" },
        { kana: "ぼく", romaji: "boku", meaning: "saya (laki-laki, santai)" },
        { kana: "おれ", romaji: "ore", meaning: "saya (laki-laki, kasual)" },
        { kana: "あなた", romaji: "anata", meaning: "kamu" },
        { kana: "かれ", romaji: "kare", meaning: "dia (laki-laki) / pacar" },
        { kana: "かのじょ", romaji: "kanojo", meaning: "dia (perempuan) / pacar" },
        { kana: "わたしたち", romaji: "watashitachi", meaning: "kami / kita" },
      ],
      note: "'watashi' paling aman dipakai semua orang. 'boku' & 'ore' untuk laki-laki. 'anata' jarang dipakai - lebih baik sebut nama orangnya!",
    },
    enemies: [
      {
        id: "name-thief",
        name: "Pencuri Nama",
        nameJp: "名前泥棒",
        sprite: "🎭",
        hp: 6,
        attack: 3,
        color: "#9c27b0",
        abilities: ["multi-attack", "poison"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Apa arti 'わたし'?",
        kana: "わたし",
        options: ["kamu", "saya", "dia", "kami"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "Kata ganti 'kamu' adalah?",
        options: ["わたし", "あなた", "かれ", "わたしたち"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'dia (perempuan)':",
        kana: "かのじょ",
        answer: ["kanojo"],
      },
      {
        type: "choice",
        prompt: "'ぼく' (boku) biasanya dipakai oleh?",
        options: ["perempuan saja", "laki-laki", "anak-anak saja", "orang tua"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'kami / kita':",
        kana: "わたしたち",
        answer: ["watashitachi"],
      },
    ],
    reward: { xp: 80 },
  },

  // ===== STAGE 3: DESU (TO BE) =====
  {
    id: "n5-3",
    worldId: "n5",
    index: 3,
    chapter: 1,
    title: "Adalah, Adalah, Adalah",
    subtitle: "Polite Copula: です (desu)",
    type: "battle",
    intro: [
      "**Toko Roti Vassal**",
      "Kau masuk ke toko roti. Penjual: 「これは パン です!」",
      "Tapi aneh - semua barang ditandai sebagai 'pan' (roti) meski bukan roti!",
      "Yuki: 「です (desu) berarti 'adalah' - kata penghubung kalimat. Tapi salah dipakai, semua jadi roti!」",
      "「Pelajari pola: A は B です (A adalah B).」",
    ],
    outro: [
      "Toko roti kembali normal. Penjual: 「これは ケーキ です!」",
      "Yuki: «Sekarang kau bisa membuat kalimat sederhana!»",
      "**Stage 3 selesai! +90 XP, 35 koin**",
    ],
    lesson: {
      title: "Polite Copula です (desu)",
      rows: [
        { kana: "です", romaji: "desu", meaning: "adalah (formal, positif)" },
        { kana: "じゃないです", romaji: "ja nai desu", meaning: "bukan (formal, negatif)" },
        { kana: "は", romaji: "wa", meaning: "partikel topik (dibaca 'wa')" },
        { kana: "も", romaji: "mo", meaning: "juga" },
      ],
      note: "Pola dasar: A は B です = A adalah B. 'は' ditulis 'ha' tapi dibaca 'wa' sebagai partikel topik!",
    },
    enemies: [
      {
        id: "is-bug",
        name: "Bug Adalah",
        nameJp: "ですバグ",
        sprite: "🐛",
        hp: 7,
        attack: 3,
        color: "#76ff03",
        abilities: ["multi-attack", "crit"],
        critChance: 0.15,
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "「これは パン です」 artinya?",
        kana: "これは パン です",
        options: ["Ini adalah roti", "Itu adalah roti", "Aku adalah roti", "Roti adalah ini"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "Partikel 'は' dibaca sebagai?",
        options: ["ha", "wa", "ba", "pa"],
        answer: 1,
        hint: "Pengecualian partikel topik!",
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'adalah' (formal):",
        kana: "です",
        answer: ["desu"],
      },
      {
        type: "choice",
        prompt: "「わたしは がくせい です」 artinya?",
        kana: "わたしは がくせい です",
        options: ["Saya adalah murid", "Kamu adalah murid", "Dia adalah murid", "Murid adalah saya"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "「これも パン です」 - 'も' berarti?",
        options: ["adalah", "bukan", "juga", "atau"],
        answer: 2,
      },
    ],
    reward: { xp: 90 },
  },

  // ===== STAGE 4: NUMBERS 1-10 =====
  {
    id: "n5-4",
    worldId: "n5",
    index: 4,
    chapter: 1,
    title: "Menghitung Harta",
    subtitle: "Angka 1-10",
    type: "battle",
    intro: [
      "**Pasar Vassal - Sibuk**",
      "Pasar sedang kacau! Pedagang tidak bisa menyebut harga.",
      "「これ... いくら?」 (Ini berapa?) «Saya lupa angka!»",
      "Yuki: 「Belajar 1-10 dulu. Penting untuk transaksi!」",
    ],
    outro: [
      "Pasar kembali ramai. Pedagang berseru: 「これ は さんびゃくえん です! 300 yen!」",
      "Yuki: «Bagus! Sekarang bisa bertransaksi.»",
      "**Stage 4 selesai! +100 XP, 40 koin**",
    ],
    lesson: {
      title: "Angka 1-10",
      rows: [
        { kana: "いち", romaji: "ichi", meaning: "1" },
        { kana: "に", romaji: "ni", meaning: "2" },
        { kana: "さん", romaji: "san", meaning: "3" },
        { kana: "し/よん", romaji: "shi/yon", meaning: "4 (yon lebih umum)" },
        { kana: "ご", romaji: "go", meaning: "5" },
        { kana: "ろく", romaji: "roku", meaning: "6" },
        { kana: "しち/なな", romaji: "shichi/nana", meaning: "7 (nana lebih umum)" },
        { kana: "はち", romaji: "hachi", meaning: "8" },
        { kana: "きゅう/く", romaji: "kyuu/ku", meaning: "9" },
        { kana: "じゅう", romaji: "juu", meaning: "10" },
      ],
      note: "4 (shi) & 7 (shichi) sering dihindari karena 'shi' juga berarti 'mati'. Pakai 'yon' & 'nana' lebih aman!",
    },
    enemies: [
      {
        id: "number-ghost",
        name: "Hantu Angka",
        nameJp: "数字",
        sprite: "🔢",
        hp: 8,
        attack: 4,
        color: "#ff9800",
        abilities: ["poison", "time-pressure"],
      },
    ],
    questions: [
      {
        type: "typing",
        prompt: "Romaji untuk '1':",
        kana: "いち",
        answer: ["ichi"],
      },
      {
        type: "typing",
        prompt: "Romaji untuk '3':",
        kana: "さん",
        answer: ["san"],
      },
      {
        type: "choice",
        prompt: "Angka '4' biasanya dibaca (lebih umum)?",
        options: ["shi", "yon", "suu", "yo"],
        answer: 1,
        hint: "'shi' juga berarti 'mati', jadi dihindari",
      },
      {
        type: "typing",
        prompt: "Romaji untuk '5':",
        kana: "ご",
        answer: ["go"],
      },
      {
        type: "typing",
        prompt: "Romaji untuk '7' (lebih umum):",
        kana: "なな",
        answer: ["nana"],
      },
      {
        type: "typing",
        prompt: "Romaji untuk '10':",
        kana: "じゅう",
        answer: ["juu", "ju"],
      },
    ],
    reward: { xp: 100 },
  },

  // ===== STAGE 5: MINI-BOSS - DAYS OF WEEK =====
  {
    id: "n5-5",
    worldId: "n5",
    index: 5,
    chapter: 1,
    title: "Ujian Penjaga Waktu",
    subtitle: "Mini-Boss: Hari & Bulan",
    type: "mini-boss",
    intro: [
      "**Menara Jam Vassal**",
      "Sesosok kurcaci berjanggut panjang menunggumu di puncak menara.",
      "「Aku **Tokkun**, penjaga waktu. Hari apa ini? Bulan apa ini? Kalau tidak tahu, kau tak boleh lewat!」",
      "Yuki: 「Hari dalam seminggu pakai 'youbi'. Bulan pakai 'gatsu'. Pelajari baik-baik!」",
    ],
    outro: [
      "Tokkun tertawa puas. 「Kau tahu waktuku! Silakan lanjut ke kastil dalam.»",
      "Ia memberimu kunci kecil. «Ini kunci menuju perpustakaan kerajaan.»",
      "**Stage 5 selesai! +150 XP, 50 koin, Item: Kunci Perpustakaan, Badge: Lulus Ujian Waktu**",
    ],
    lesson: {
      title: "Hari & Bulan",
      rows: [
        { kana: "げつようび", romaji: "getsuyoubi", meaning: "Senin" },
        { kana: "かようび", romaji: "kayoubi", meaning: "Selasa" },
        { kana: "すいようび", romaji: "suiyoubi", meaning: "Rabu" },
        { kana: "もくようび", romaji: "mokuyoubi", meaning: "Kamis" },
        { kana: "きんようび", romaji: "kinyoubi", meaning: "Jumat" },
        { kana: "どようび", romaji: "doyoubi", meaning: "Sabtu" },
        { kana: "にちようび", romaji: "nichiyoubi", meaning: "Minggu" },
        { kana: "いちがつ", romaji: "ichigatsu", meaning: "Januari (bulan 1)" },
      ],
      note: "Hari: [nama] + youbi. Senin=getsu(bulan), Minggu=nichi(matahari). Bulan: [angka] + gatsu.",
    },
    enemies: [
      {
        id: "tokkun",
        name: "Tokkun Penjaga Waktu",
        nameJp: "トックン",
        sprite: "⏰",
        hp: 12,
        attack: 5,
        description: "Mini-boss: ujian hari & bulan.",
        color: "#cddc39",
        abilities: ["time-pressure", "shield", "enrage"],
      },
    ],
    questions: [
      {
        type: "typing",
        prompt: "Romaji untuk 'Senin':",
        kana: "げつようび",
        answer: ["getsuyoubi", "getsuyobi"],
      },
      {
        type: "choice",
        prompt: "「すいようび」 adalah hari?",
        kana: "すいようび",
        options: ["Senin", "Selasa", "Rabu", "Kamis"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'Jumat':",
        kana: "きんようび",
        answer: ["kinyoubi", "kinyobi"],
      },
      {
        type: "choice",
        prompt: "「にちようび」 adalah?",
        kana: "にちようび",
        options: ["Sabtu", "Minggu", "Senin", "Kamis"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'Januari' (bulan 1):",
        kana: "いちがつ",
        answer: ["ichigatsu"],
      },
      {
        type: "choice",
        prompt: "Suffix untuk hari adalah?",
        options: ["gatsu", "youbi", "nichi", "ka"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "Suffix untuk bulan adalah?",
        options: ["youbi", "gatsu", "nichi", "ka"],
        answer: 1,
      },
    ],
    reward: { xp: 150, item: "Kunci Perpustakaan", badge: "Lulus Ujian Waktu" },
  },

  // ===== STAGE 6: KANJI NUMBERS 1-10 =====
  {
    id: "n5-6",
    worldId: "n5",
    index: 6,
    chapter: 1,
    title: "Perpustakaan Kerajaan",
    subtitle: "Kanji Angka: 一二三四五六七八九十",
    type: "lesson",
    intro: [
      "**Perpustakaan Kerajaan Vassal**",
      "Setelah membuka pintu perpustakaan dengan kuncimu, kau melihat ribuan buku.",
      "Tapi semua buku tertulis dalam karakter aneh - Kanji!",
      "Pustakawan: 「Di sini buku pakai Kanji, huruf Tionghoa yang diadopsi Jepang. Mulai dengan angka.」",
      "Yuki: 「Kanji angka paling dasar. Bentuknya sederhana - belajar dulu 1-10.」",
    ],
    outro: [
      "Pustakawan tersenyum. 「Kau cepat belajar! Tapi Kanji banyak sekali - di N5 sekitar 100.»",
      "Ia memberimu kamus Kanji. «Ini akan membantumu mengenali kanji dasar.»",
      "**Stage 6 selesai! +110 XP, 45 koin, Item: Kamus Kanji Dasar**",
    ],
    lesson: {
      title: "Kanji Angka 1-10",
      rows: [
        { kana: "一", romaji: "ichi", meaning: "satu" },
        { kana: "二", romaji: "ni", meaning: "dua" },
        { kana: "三", romaji: "san", meaning: "tiga" },
        { kana: "四", romaji: "yon/yo", meaning: "empat" },
        { kana: "五", romaji: "go", meaning: "lima" },
        { kana: "六", romaji: "roku", meaning: "enam" },
        { kana: "七", romaji: "nana/shichi", meaning: "tujuh" },
        { kana: "八", romaji: "hachi", meaning: "delapan" },
        { kana: "九", romaji: "kyuu/ku", meaning: "sembilan" },
        { kana: "十", romaji: "juu", meaning: "sepuluh" },
      ],
      note: "Kanji angka sering muncul di alamat, tanggal, harga. 一二三 = 123, kombinasi: 十一 = 11, 二十 = 20.",
    },
    enemies: [
      {
        id: "kanji-tutor",
        name: "Tutor Kanji",
        nameJp: "漢字",
        sprite: "📚",
        hp: 9,
        attack: 4,
        color: "#3f51b5",
        abilities: ["shield", "counter"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Kanji '一' dibaca?",
        kana: "一",
        options: ["ichi (1)", "ni (2)", "san (3)", "juu (10)"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: "Kanji '三' adalah angka?",
        kana: "三",
        options: ["1", "2", "3", "5"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "Romaji untuk Kanji '七':",
        kana: "七",
        answer: ["nana", "shichi"],
      },
      {
        type: "choice",
        prompt: "Kanji '十' berarti?",
        kana: "十",
        options: ["1", "5", "10", "100"],
        answer: 2,
      },
      {
        type: "choice",
        prompt: "「十一」 artinya?",
        kana: "十一",
        options: ["9 (10-1)", "11 (10+1)", "20 (10×2)", "1 (10/10)"],
        answer: 1,
        hint: "Kanji digabung: 十(10) + 一(1) = 11",
      },
      {
        type: "typing",
        prompt: "Romaji untuk Kanji '五':",
        kana: "五",
        answer: ["go"],
      },
    ],
    reward: { xp: 110, item: "Kamus Kanji Dasar" },
  },

  // ===== STAGE 7: KANJI DASAR (orang, hari, bulan) =====
  {
    id: "n5-7",
    worldId: "n5",
    index: 7,
    chapter: 1,
    title: "Kanji Kehidupan Sehari-hari",
    subtitle: "人, 日, 月, 火, 水",
    type: "battle",
    intro: [
      "**Lorong Perpustakaan**",
      "Buku-buku berkilau di rak. Satu buku melayang: 「Pelajari kami, pemuda!」",
      "「Kanji dasar yang sering muncul: 人 (orang), 日 (hari/matahari), 月 (bulan), 火 (api), 水 (air).」",
      "Yuki: 「Ini kanji yang dipakai dalam nama hari! getsuyoubi = 月 + youbi.»",
    ],
    outro: [
      "Buku-buku di rak berdenting senang. 「Kau mengenal kami sekarang!»",
      "Yuki: «Bagus! Sekarang kau bisa membaca tanda-tanda dasar di kerajaan.»",
      "**Stage 7 selesai! +120 XP, 50 koin**",
    ],
    lesson: {
      title: "Kanji Dasar Kehidupan",
      rows: [
        { kana: "人", romaji: "hito/nin", meaning: "orang" },
        { kana: "日", romaji: "hi/nichi", meaning: "hari/matahari" },
        { kana: "月", romaji: "tsuki/getsu", meaning: "bulan/bulan(kalender)" },
        { kana: "火", romaji: "hi/ka", meaning: "api" },
        { kana: "水", romaji: "mizu/sui", meaning: "air" },
        { kana: "木", romaji: "ki/moku", meaning: "pohon/kayu" },
        { kana: "金", romaji: "kin/kane", meaning: "emas/uang" },
        { kana: "本", romaji: "hon", meaning: "asal/buku" },
      ],
      note: "Hari dalam seminggu pakai kanji ini! 月(getsu=Senin), 火(ka=Selasa), 水(sui=Rabu), 木(moku=Kamis), 金(kin=Jumat), 土(do=Sabtu), 日(nichi=Minggu).",
    },
    enemies: [
      {
        id: "kanji-book",
        name: "Buku Kanji Hidup",
        nameJp: "本",
        sprite: "📖",
        hp: 10,
        attack: 4,
        color: "#795548",
        abilities: ["heal", "shield"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "Kanji '人' berarti?",
        kana: "人",
        options: ["pohon", "orang", "air", "api"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "Kanji '日' berarti?",
        kana: "日",
        options: ["bulan", "matahari/hari", "orang", "uang"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk Kanji '月' (saat artinya bulan di langit):",
        kana: "月",
        answer: ["tsuki"],
      },
      {
        type: "choice",
        prompt: "Kanji '水' berarti?",
        kana: "水",
        options: ["api", "tanah", "air", "angin"],
        answer: 2,
      },
      {
        type: "choice",
        prompt: "Hari Senin 'げつようび' pakai kanji?",
        kana: "げつようび",
        options: ["日", "月", "火", "木"],
        answer: 1,
        hint: "getsu = bulan",
      },
      {
        type: "typing",
        prompt: "Romaji untuk Kanji '本' (saat artinya buku):",
        kana: "本",
        answer: ["hon"],
      },
    ],
    reward: { xp: 120 },
  },

  // ===== STAGE 8: VERB FORMS (masu) =====
  {
    id: "n5-8",
    worldId: "n5",
    index: 8,
    chapter: 1,
    title: "Aksi & Kehendak",
    subtitle: "Kata Kerja Bentuk ます (masu)",
    type: "battle",
    intro: [
      "**Halaman Kastil Dalam**",
      "Kau tiba di kastil dalam. Para penjaga sedang latihan pedang.",
      "Komandan: 「たべます! (makan!) のみます! (minum!) いきます! (pergi!)」",
      "「Pelajari bentuk ます (masu) - bentuk sopan kata kerja. Ini dasar semua kalimat kerja!»",
      "Yuki: 「ます (masu) = bentuk sopan positif. ません (masen) = bentuk sopan negatif.»",
    ],
    outro: [
      "Komandan mengangguk. 「Kau paham kata kerja! Sekarang bisa menyuruh dan menyatakan aksi.»",
      "**Stage 8 selesai! +130 XP, 55 koin**",
    ],
    lesson: {
      title: "Kata Kerja Bentuk ます (masu)",
      rows: [
        { kana: "たべます", romaji: "tabemasu", meaning: "makan (sopan)" },
        { kana: "のみます", romaji: "nomimasu", meaning: "minum (sopan)" },
        { kana: "いきます", romaji: "ikimasu", meaning: "pergi (sopan)" },
        { kana: "きます", romaji: "kimasu", meaning: "datang (sopan)" },
        { kana: "みます", romaji: "mimasu", meaning: "melihat (sopan)" },
        { kana: "ききます", romaji: "kikimasu", meaning: "mendengar (sopan)" },
        { kana: "よみます", romaji: "yomimasu", meaning: "membaca (sopan)" },
        { kana: "かきます", romaji: "kakimasu", meaning: "menulis (sopan)" },
      ],
      note: "Polanya: [stem] + ます. Untuk negatif: [stem] + ません. Bentuk lampau: [stem] + ました.",
    },
    enemies: [
      {
        id: "verb-shadow",
        name: "Bayangan Kata Kerja",
        nameJp: "動詞",
        sprite: "⚔",
        hp: 11,
        attack: 5,
        color: "#e91e63",
        abilities: ["multi-attack", "crit"],
        critChance: 0.2,
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "「たべます」 artinya?",
        kana: "たべます",
        options: ["minum", "makan", "tidur", "berjalan"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "「いきます」 artinya?",
        kana: "いきます",
        options: ["datang", "pergi", "lari", "duduk"],
        answer: 1,
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'membaca' (sopan):",
        kana: "よみます",
        answer: ["yomimasu"],
      },
      {
        type: "choice",
        prompt: "Negatif dari 'たべます' adalah?",
        options: ["たべません", "たべまさい", "たべないます", "たべませんた"],
        answer: 0,
        hint: "Ganti ます → ません",
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'mendengar' (sopan):",
        kana: "ききます",
        answer: ["kikimasu"],
      },
      {
        type: "choice",
        prompt: "「みます」 artinya?",
        kana: "みます",
        options: ["melihat", "membaca", "menulis", "makan"],
        answer: 0,
      },
    ],
    reward: { xp: 130 },
  },

  // ===== STAGE 9: ADJECTIVES (i & na) =====
  {
    id: "n5-9",
    worldId: "n5",
    index: 9,
    chapter: 1,
    title: "Deskripsi & Sifat",
    subtitle: "Kata Sifat -i & -na",
    type: "battle",
    intro: [
      "**Taman Kastil Vassal**",
      "Di taman yang indah, kau bertemu seorang pelayan yang bingung.",
      "「Bunga ini... あかい? たかい? きれい? Saya bingung kata sifat mana yang dipakai!»",
      "Yuki: 「Ada dua jenis kata sifat: -i (いい、たかい) dan -na (きれいな、しずかな). Pelajari!»",
    ],
    outro: [
      "Pelayan tersenyum. 「Bunga ini きれいですね! Cantik ya!」",
      "Yuki: «Sekarang kau bisa mendeskripsikan apapun!»",
      "**Stage 9 selesai! +140 XP, 60 koin**",
    ],
    lesson: {
      title: "Kata Sifat -i & -na",
      rows: [
        { kana: "たかい", romaji: "takai", meaning: "tinggi / mahal (-i)" },
        { kana: "ひくい", romaji: "hikui", meaning: "rendah (-i)" },
        { kana: "おおきい", romaji: "ookii", meaning: "besar (-i)" },
        { kana: "ちいさい", romaji: "chiisai", meaning: "kecil (-i)" },
        { kana: "あかい", romaji: "akai", meaning: "merah (-i)" },
        { kana: "きれい(な)", romaji: "kirei (na)", meaning: "cantik / bersih (-na)" },
        { kana: "しずか(な)", romaji: "shizuka (na)", meaning: "tenang (-na)" },
        { kana: "げんき(な)", romaji: "genki (na)", meaning: "sehat / energetik (-na)" },
      ],
      note: "Sifat -i: berakhiran い, langsung pakai (たかい + です). Sifat -na: pakai 'na' sebelum kata benda (きれいな ほん).",
    },
    enemies: [
      {
        id: "adjective-mist",
        name: "Kabut Sifat",
        nameJp: "形容詞",
        sprite: "🌫",
        hp: 12,
        attack: 5,
        color: "#cfd8dc",
        abilities: ["poison", "regen", "counter"],
      },
    ],
    questions: [
      {
        type: "choice",
        prompt: "「たかい」 berarti?",
        kana: "たかい",
        options: ["rendah", "tinggi/mahal", "kecil", "merah"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "Mana yang merupakan kata sifat -na?",
        options: ["たかい", "おおきい", "きれい", "あかい"],
        answer: 2,
        hint: "Tidak berakhiran 'i'!",
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'merah':",
        kana: "あかい",
        answer: ["akai"],
      },
      {
        type: "choice",
        prompt: "Untuk mendeskripsikan buku yang cantik, kau bilang?",
        options: ["きれい ほん", "きれいな ほん", "きれいの ほん", "きれいい ほん"],
        answer: 1,
        hint: "Sifat -na + na + kata benda",
      },
      {
        type: "typing",
        prompt: "Romaji untuk 'sehat/energetik' (sifat -na):",
        kana: "げんき",
        answer: ["genki"],
      },
    ],
    reward: { xp: 140 },
  },

  // ===== STAGE 10: BOSS - LORD VASSAL =====
  {
    id: "n5-10",
    worldId: "n5",
    index: 10,
    chapter: 1,
    title: "Lord Vassal",
    subtitle: "Bos Akhir Bab N5",
    type: "boss",
    intro: [
      "**Tahta Kastil Vassal**",
      "Di aula tahta, sesosok pria berjanggut putih duduk di singgasana. **Lord Vassal**, penguasa kerajaan.",
      "「Pengelana dari Hajimari... Aku dengar kau membantu pendudukku. Tapi untuk kuasai kerajaanku, kau harus menguasaiku dulu dalam bahasa!」",
      "Yuki: «Ini ujian akhir N5. Gabungkan semua yang kau pelajari - salam, kata ganti, desu, angka, hari, kanji, kata kerja, sifat!»",
      "Lord Vassal berdiri. 「Pertarungan bahasa dimulai!」",
      "**PERTARUNGAN AKHIR BAB N5**",
    ],
    outro: [
      "Lord Vassal tertawa lebar. 「HAHAHA! Kau menguasai dasar bahasa Jepang!»",
      "Ia menjabat tanganmu. 「Selamat, pahlawan. Kau pantas mendapat gelar «Pengelana N5».»",
      "Ia menyerahkan medali emas. «Dengan ini, kau bisa lanjut ke Minato Port - JLPT N4 menunggumu!»",
      "Yuki: «Aku bangga padamu. Tapi petualangan belum selesai...»",
      "**BAB N5 SELESAI! +800 XP, 300 koin, Badge: Pengelana N5, Item: Medali Vassal**",
      "**Dunia baru terbuka: Minato Port (JLPT N4)**",
    ],
    lesson: {
      title: "Ujian Akhir N5",
      rows: [
        { kana: "おはよう", romaji: "ohayou", meaning: "selamat pagi" },
        { kana: "わたし", romaji: "watashi", meaning: "saya" },
        { kana: "です", romaji: "desu", meaning: "adalah" },
        { kana: "さん", romaji: "san", meaning: "3 (atau akhiran hormat)" },
        { kana: "たべます", romaji: "tabemasu", meaning: "makan" },
        { kana: "たかい", romaji: "takai", meaning: "tinggi/mahal" },
        { kana: "人", romaji: "hito", meaning: "orang" },
        { kana: "日", romaji: "hi", meaning: "hari" },
      ],
      note: "Semua yang dipelajari di Bab N5 jadi fondasi N4 dan seterusnya. Selamat, Pengelana!",
    },
    enemies: [
      {
        id: "lord-vassal",
        name: "Lord Vassal",
        nameJp: "ヴァッサル卿",
        sprite: "🤴",
        hp: 18,
        attack: 6,
        description: "Bos akhir N5. Penguasa Vassal Kingdom, ahli bahasa formal.",
        color: "#ff9800",
        abilities: ["enrage", "heal", "crit", "shield", "multi-attack", "counter"],
        critChance: 0.2,
      },
    ],
    questions: [
      // Comprehensive N5 review
      {
        type: "choice",
        prompt: "「おはようございます」 dipakai kapan?",
        kana: "おはようございます",
        options: ["pagi (formal)", "siang", "malam", "selamat tinggal"],
        answer: 0,
      },
      {
        type: "typing",
        prompt: "Romaji 'わたしたち' (kami/kita):",
        kana: "わたしたち",
        answer: ["watashitachi"],
      },
      {
        type: "choice",
        prompt: "「これは ほん です」 artinya?",
        kana: "これは ほん です",
        options: ["Ini adalah buku", "Itu adalah buku", "Aku adalah buku", "Buku adalah ini"],
        answer: 0,
      },
      {
        type: "typing",
        prompt: "Romaji angka '7' (lebih umum):",
        kana: "なな",
        answer: ["nana"],
      },
      {
        type: "choice",
        prompt: "Kanji '人' dibaca saat artinya 'orang'?",
        kana: "人",
        options: ["hi", "hito", "tsuki", "hon"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: "「きんようび」 adalah hari?",
        kana: "きんようび",
        options: ["Senin", "Rabu", "Jumat", "Minggu"],
        answer: 2,
      },
      {
        type: "typing",
        prompt: "Romaji 'のみます' (minum - sopan):",
        kana: "のみます",
        answer: ["nomimasu"],
      },
      {
        type: "choice",
        prompt: "「きれいな はな」 artinya?",
        kana: "きれいな はな",
        options: ["Bunga yang cantik", "Bunga yang tinggi", "Bunga merah", "Bunga besar"],
        answer: 0,
      },
      {
        type: "typing",
        prompt: "Romaji 'すみません' (maaf/permisi):",
        kana: "すみません",
        answer: ["sumimasen"],
      },
      {
        type: "choice",
        prompt: "「Selamat tinggal» dalam bahasa Jepang?",
        options: ["こんにちは", "ありがとう", "さようなら", "すみません"],
        answer: 2,
      },
    ],
    reward: { xp: 800, badge: "Pengelana N5", item: "Medali Vassal" },
  },
];
